plugins {
	id 'fabric-loom' version '1.17.+'
}

loom {
	noIntermediateMappings()
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraftVersion}"
	mappings loom.layered {
	}
	modImplementation "net.fabricmc:fabric-loader:${fabricLoaderVersion}"
}

sourceSets {
	main {
		java.srcDir project(':common').sourceSets.main.java.srcDirs
		resources.srcDir project(':common').sourceSets.main.resources.srcDirs
	}
}
