plugins {
	id 'fabric-loom' version '1.12-SNAPSHOT'
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraftVersion}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${fabricLoaderVersion}"
	implementation project(':common')
}

sourceSets {
	main {
		java.srcDir project(':common').sourceSets.main.java.srcDirs
		resources.srcDir project(':common').sourceSets.main.resources.srcDirs
	}
}
