plugins {
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
}

subprojects {
	apply plugin: 'java-library'
	apply plugin: 'maven-publish'

	version = "${minecraftVersion}-${modVersion}"
	group = 'com.blackout.extendedslabs'
	base.archivesName = "${modId}-${project.name}"

	java.toolchain.languageVersion = JavaLanguageVersion.of(26)

	tasks.withType(JavaCompile).configureEach {
		options.encoding = 'UTF-8'
		options.release = 26
	}

	tasks.withType(ProcessResources).configureEach {
		var replaceProperties = [
				minecraftVersion: minecraftVersion,
				minecraftVersionRange: minecraftVersionRange,
				neoVersion: neoVersion,
				neoVersionRange: neoVersionRange,
				neoLoaderVersionRange: neoLoaderVersionRange,
				fabricLoaderVersion: fabricLoaderVersion,
				fabricApiVersion: fabricApiVersion,
				modId: modId,
				modName: modName,
				modLicense: modLicense,
				modVersion: modVersion,
				modAuthor: modAuthor,
				modDescription: modDescription,
				packVersion: packVersion,
		]

		inputs.properties replaceProperties

		filesMatching(['fabric.mod.json', 'META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
			expand replaceProperties
		}

		exclude '**/.cache/'
		duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	}
}
