org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

minecraftVersion=1.20.1
minecraftVersionRange=[1.20,1.21)
neoVersion=47.1.25
neoVersionRange=[47.1,)
loaderVersionRange=[47,)
packVersion=15

mappingsChannel=parchment
mappingsVersion=1.19.3-2023.06.25-1.20.1

modName=Extended Slabs +
modId=extendedslabs
modVersion=3.0.1
modAuthor=Blackout
modLicense=All Rights Reserved
modDescription=This mod adds vertical slabs and more to Minecraft.

# https://www.curseforge.com/minecraft/mc-mods/jei/files?version=1.20.1&gameVersionTypeId=1
jeiVersion=15.2.0.23
# https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files?version=1.20.1&gameVersionTypeId=1
jerVersion=4092965
# https://www.curseforge.com/minecraft/mc-mods/configured/files?version=1.20.1&gameVersionTypeId=1
configuredVersion=4462894
# https://www.curseforge.com/minecraft/mc-mods/catalogue/files?version=1.20.1&gameVersionTypeId=1
catalogueVersion=4590890
# https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files?version=1.20.1&gameVersionTypeId=1
topVersion=4629624
