org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
org.gradle.debug=false

minecraftVersion=1.20.2
neoVersion=20.2.88

neogradle.subsystems.parchment.minecraftVersion=1.20.2
neogradle.subsystems.parchment.mappingsVersion=2023.12.10

modName=Extended Slabs +
modId=extendedslabs
modVersion=3.1.0

# https://www.curseforge.com/minecraft/mc-mods/jei/files?version=1.20.2&gameVersionTypeId=6
jeiVersion=15.2.0.25
# https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files?version=1.20.2&gameVersionTypeId=6
jerVersion=4092965
# https://www.curseforge.com/minecraft/mc-mods/configured/files?version=1.20.2&gameVersionTypeId=6
configuredVersion=4462894
# https://www.curseforge.com/minecraft/mc-mods/catalogue/files?version=1.20.2&gameVersionTypeId=6
catalogueVersion=4590890
# https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files?version=1.20.2&gameVersionTypeId=6
topVersion=4629624
