modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/thinkverse/vertical_slabs/issues"

[[mods]]
    modId="verticalslabsmod"
    version="${file.jarVersion}"
    displayName="Vertical Slabs Mod"
    displayURL="https://thinkverse.dev"
    updateJSONURL="https://thinkverse.dev/vertical_slabs/update"
    logoFile="examplemod.png"
    credits="Clownvin, HarryTechRevs & SilentChaos512"
    authors="Thinkverse"
    description='''
    This mod adds vertical slabs to minecraft.

    Have fun!
    '''

[[dependencies.versecraft]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.versecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"