modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Blackout03/extended-slabs/issues"

[[mods]]
    modId="extendedslabs"
    version="${file.jarVersion}"
    displayName="Extended Slabs"
    displayURL="https://blackout03.c1.biz"
    updateJSONURL="http://blackout03.c1.biz/mods/extendedslabs/update.json"
    logoFile="icon.png"
    credits="Thinkverse"
    authors="Blackout03"
    description='''This mod adds vertical slabs and more to Minecraft.'''

[[dependencies.versecraft]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.versecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
