modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Blackout03/extended-slabs/issues"
displayURL=""
license="MIT License"

[[mods]]
    modId="extendedslabs"
    version="${file.jarVersion}"
    displayName="Extended Slabs"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/extended-slabs-1-15"
    updateJSONURL="https://raw.githubusercontent.com/Blackout03/Version/master/extendedslabs_update.json"
    logoFile="icon.png"
    credits="Thinkverse"
    authors="Blackout03"
    description='''This mod adds vertical slabs and more to Minecraft.'''

[[dependencies.extendedslabs]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extendedslabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
