modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Blackout03/extended-slabs/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extended-slabs-plus"
license="MIT License"

[[mods]]
modId="extendedslabs"
version="${file.jarVersion}"
displayName="Extended Slabs +"
authors="Blackout03"
description='''This mod adds vertical slabs and more to Minecraft.'''
itemIcon="extendedslabs:vertical_dirt_path_slab"
logoFile="icon.png"
credits="Thinkverse"

[[dependencies.extendedslabs]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

[[dependencies.extendedslabs]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18]"
ordering="NONE"
side="BOTH"
