modLoader="javafml"
loaderVersion="${loaderVersionRange}"
issueTrackerURL="https://github.com/Blackout03/extended-slabs/issues"
license="${modLicense}"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
updateJSONURL="https://forge.curseupdate.com/374492/extendedslabs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extended-slabs-plus"
authors="${modAuthor}"
description='''${modDescription}'''
itemIcon="extendedslabs:vertical_dirt_path_slab"
logoFile="icon.png"
credits="Thinkverse"

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="${neoVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"
