package com.blackout.extendedslabs.datagen;

import biomesoplenty.api.block.BOPBlocks;
import com.blackout.extendedslabs.ExtendedSlabs;
import com.blackout.extendedslabs.init.ESPSlabs;
import com.blackout.extendedslabs.init.ESPVerticalSlabs;
import com.blackout.extendedslabs.init.modded.BOPSlabs;
import com.blackout.extendedslabs.init.modded.BOPVerticalSlabs;
import net.minecraft.block.Blocks;
import net.minecraft.data.*;
import net.minecraft.item.Item;
import net.minecraft.item.crafting.Ingredient;

import java.util.function.Consumer;

public class ESPVerticalSlabRecipeProvider extends RecipeProvider {

	public ESPVerticalSlabRecipeProvider(DataGenerator generator) {
		super(generator);
	}

	@Override
	public void buildShapelessRecipes(Consumer<IFinishedRecipe> consumer) {
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRASS_BLOCK_VERTICAL.get().asItem(), ESPSlabs.GRASS_BLOCK_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.DIRT_VERTICAL.get().asItem(), ESPSlabs.DIRT_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.COARSE_DIRT_VERTICAL.get().asItem(), ESPSlabs.COARSE_DIRT_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PODZOL_VERTICAL.get().asItem(), ESPSlabs.PODZOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MYCELIUM_VERTICAL.get().asItem(), ESPSlabs.MYCELIUM_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRASS_PATH_VERTICAL.get().asItem(), ESPSlabs.GRASS_PATH_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.SAND_VERTICAL.get().asItem(), ESPSlabs.SAND_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_SAND_VERTICAL.get().asItem(), ESPSlabs.RED_SAND_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRAVEL_VERTICAL.get().asItem(), ESPSlabs.GRAVEL_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.STONE_VERTICAL.get().asItem(), Blocks.STONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.COBBLESTONE_VERTICAL.get().asItem(), Blocks.COBBLESTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.STONE_BRICK_VERTICAL.get().asItem(), Blocks.STONE_BRICK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.SMOOTH_STONE_VERTICAL.get().asItem(), Blocks.SMOOTH_STONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MOSSY_COBBLESTONE_VERTICAL.get().asItem(), Blocks.MOSSY_COBBLESTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MOSSY_STONE_BRICK_VERTICAL.get().asItem(), Blocks.MOSSY_STONE_BRICK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.ANDESITE_VERTICAL.get().asItem(), Blocks.ANDESITE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.POLISHED_ANDESITE_VERTICAL.get().asItem(), Blocks.POLISHED_ANDESITE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.DIORITE_VERTICAL.get().asItem(), Blocks.DIORITE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.POLISHED_DIORITE_VERTICAL.get().asItem(), Blocks.POLISHED_DIORITE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRANITE_VERTICAL.get().asItem(), Blocks.GRANITE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.POLISHED_GRANITE_VERTICAL.get().asItem(), Blocks.POLISHED_GRANITE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BRICK_VERTICAL.get().asItem(), Blocks.BRICK_SLAB.asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.WHITE_WOOL_VERTICAL.get().asItem(), ESPSlabs.WHITE_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.ORANGE_WOOL_VERTICAL.get().asItem(), ESPSlabs.ORANGE_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MAGENTA_WOOL_VERTICAL.get().asItem(), ESPSlabs.MAGENTA_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_BLUE_WOOL_VERTICAL.get().asItem(), ESPSlabs.LIGHT_BLUE_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.YELLOW_WOOL_VERTICAL.get().asItem(), ESPSlabs.YELLOW_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIME_WOOL_VERTICAL.get().asItem(), ESPSlabs.LIME_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PINK_WOOL_VERTICAL.get().asItem(), ESPSlabs.PINK_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRAY_WOOL_VERTICAL.get().asItem(), ESPSlabs.GRAY_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_GRAY_WOOL_VERTICAL.get().asItem(), ESPSlabs.LIGHT_GRAY_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CYAN_WOOL_VERTICAL.get().asItem(), ESPSlabs.CYAN_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PURPLE_WOOL_VERTICAL.get().asItem(), ESPSlabs.PURPLE_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLUE_WOOL_VERTICAL.get().asItem(), ESPSlabs.BLUE_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BROWN_WOOL_VERTICAL.get().asItem(), ESPSlabs.BROWN_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GREEN_WOOL_VERTICAL.get().asItem(), ESPSlabs.GREEN_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_WOOL_VERTICAL.get().asItem(), ESPSlabs.RED_WOOL_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLACK_WOOL_VERTICAL.get().asItem(), ESPSlabs.BLACK_WOOL_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.WHITE_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.WHITE_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.ORANGE_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.ORANGE_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MAGENTA_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.MAGENTA_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_BLUE_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.LIGHT_BLUE_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.YELLOW_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.YELLOW_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIME_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.LIME_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PINK_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.PINK_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRAY_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.GRAY_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_GRAY_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.LIGHT_GRAY_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CYAN_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.CYAN_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PURPLE_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.PURPLE_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLUE_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.BLUE_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BROWN_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.BROWN_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GREEN_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.GREEN_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.RED_CONCRETE_POWDER_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLACK_CONCRETE_POWDER_VERTICAL.get().asItem(), ESPSlabs.BLACK_CONCRETE_POWDER_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.WHITE_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.WHITE_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.ORANGE_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.ORANGE_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MAGENTA_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.MAGENTA_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_BLUE_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.LIGHT_BLUE_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.YELLOW_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.YELLOW_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIME_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.LIME_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PINK_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.PINK_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRAY_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.GRAY_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_GRAY_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.LIGHT_GRAY_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CYAN_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.CYAN_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PURPLE_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.PURPLE_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLUE_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.BLUE_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BROWN_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.BROWN_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GREEN_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.GREEN_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.RED_CONCRETE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLACK_CONCRETE_VERTICAL.get().asItem(), ESPSlabs.BLACK_CONCRETE_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.CLAY_VERTICAL.get().asItem(), ESPSlabs.CLAY_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.WHITE_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.WHITE_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.ORANGE_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.ORANGE_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MAGENTA_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.MAGENTA_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_BLUE_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.LIGHT_BLUE_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.YELLOW_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.YELLOW_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIME_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.LIME_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PINK_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.PINK_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRAY_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.GRAY_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_GRAY_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.LIGHT_GRAY_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CYAN_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.CYAN_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PURPLE_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.PURPLE_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLUE_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.BLUE_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BROWN_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.BROWN_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GREEN_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.GREEN_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.RED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLACK_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.BLACK_TERRACOTTA_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.WHITE_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.WHITE_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.ORANGE_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.ORANGE_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MAGENTA_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.MAGENTA_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.YELLOW_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.YELLOW_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIME_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.LIME_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PINK_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.PINK_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRAY_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.GRAY_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CYAN_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.CYAN_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PURPLE_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.PURPLE_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLUE_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.BLUE_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BROWN_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.BROWN_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GREEN_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.GREEN_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.RED_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLACK_GLAZED_TERRACOTTA_VERTICAL.get().asItem(), ESPSlabs.BLACK_GLAZED_TERRACOTTA_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.GLASS_VERTICAL.get().asItem(), ESPSlabs.GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.WHITE_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.WHITE_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.ORANGE_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.ORANGE_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.MAGENTA_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.MAGENTA_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_BLUE_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.LIGHT_BLUE_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.YELLOW_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.YELLOW_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIME_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.LIME_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PINK_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.PINK_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GRAY_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.GRAY_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.LIGHT_GRAY_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.LIGHT_GRAY_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CYAN_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.CYAN_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PURPLE_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.PURPLE_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLUE_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.BLUE_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BROWN_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.BROWN_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.GREEN_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.GREEN_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.RED_STAINED_GLASS_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLACK_STAINED_GLASS_VERTICAL.get().asItem(), ESPSlabs.BLACK_STAINED_GLASS_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.SANDSTONE_VERTICAL.get().asItem(), Blocks.SANDSTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.SMOOTH_SANDSTONE_VERTICAL.get().asItem(), Blocks.SMOOTH_SANDSTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CUT_SANDSTONE_VERTICAL.get().asItem(), Blocks.CUT_SANDSTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_SANDSTONE_VERTICAL.get().asItem(), Blocks.RED_SANDSTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.SMOOTH_RED_SANDSTONE_VERTICAL.get().asItem(), Blocks.SMOOTH_RED_SANDSTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CUT_RED_SANDSTONE_VERTICAL.get().asItem(), Blocks.CUT_RED_SANDSTONE_SLAB.asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.NETHERRACK_VERTICAL.get().asItem(), ESPSlabs.NETHERRACK_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CRIMSON_NYLIUM_VERTICAL.get().asItem(), ESPSlabs.CRIMSON_NYLIUM_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.WARPED_NYLIUM_VERTICAL.get().asItem(), ESPSlabs.WARPED_NYLIUM_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.NETHER_BRICK_VERTICAL.get().asItem(), Blocks.NETHER_BRICK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.RED_NETHER_BRICK_VERTICAL.get().asItem(), Blocks.RED_NETHER_BRICK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BLACKSTONE_VERTICAL.get().asItem(), Blocks.BLACKSTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.POLISHED_BLACKSTONE_VERTICAL.get().asItem(), Blocks.POLISHED_BLACKSTONE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.POLISHED_BLACKSTONE_BRICK_VERTICAL.get().asItem(), Blocks.POLISHED_BLACKSTONE_BRICK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.QUARTZ_VERTICAL.get().asItem(), Blocks.QUARTZ_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.SMOOTH_QUARTZ_VERTICAL.get().asItem(), Blocks.SMOOTH_QUARTZ_SLAB.asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.END_STONE_VERTICAL.get().asItem(), ESPSlabs.END_STONE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.END_STONE_BRICK_VERTICAL.get().asItem(), Blocks.END_STONE_BRICK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PURPUR_VERTICAL.get().asItem(), Blocks.PURPUR_SLAB.asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.PRISMARINE_VERTICAL.get().asItem(), Blocks.PRISMARINE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PRISMARINE_BRICK_VERTICAL.get().asItem(), Blocks.PRISMARINE_BRICK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.DARK_PRISMARINE_VERTICAL.get().asItem(), Blocks.DARK_PRISMARINE_SLAB.asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.ACACIA_VERTICAL.get().asItem(), Blocks.ACACIA_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BIRCH_VERTICAL.get().asItem(), Blocks.BIRCH_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CRIMSON_VERTICAL.get().asItem(), Blocks.CRIMSON_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.DARK_OAK_VERTICAL.get().asItem(), Blocks.DARK_OAK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.JUNGLE_VERTICAL.get().asItem(), Blocks.JUNGLE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.OAK_VERTICAL.get().asItem(), Blocks.OAK_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.SPRUCE_VERTICAL.get().asItem(), Blocks.SPRUCE_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.WARPED_VERTICAL.get().asItem(), Blocks.WARPED_SLAB.asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.PETRIFIED_OAK_VERTICAL.get().asItem(), Blocks.PETRIFIED_OAK_SLAB.asItem(), consumer);

		generateVerticalSlabRecipes(ESPVerticalSlabs.ACACIA_WOOD_VERTICAL.get().asItem(), ESPSlabs.ACACIA_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.BIRCH_WOOD_VERTICAL.get().asItem(), ESPSlabs.BIRCH_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.CRIMSON_HYPHAE_VERTICAL.get().asItem(), ESPSlabs.CRIMSON_HYPHAE_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.DARK_OAK_WOOD_VERTICAL.get().asItem(), ESPSlabs.DARK_OAK_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.JUNGLE_WOOD_VERTICAL.get().asItem(), ESPSlabs.JUNGLE_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.OAK_WOOD_VERTICAL.get().asItem(), ESPSlabs.OAK_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.SPRUCE_WOOD_VERTICAL.get().asItem(), ESPSlabs.SPRUCE_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(ESPVerticalSlabs.WARPED_HYPHAE_VERTICAL.get().asItem(), ESPSlabs.WARPED_HYPHAE_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(BOPVerticalSlabs.CHERRY_VERTICAL.get().asItem(), BOPBlocks.cherry_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.DEAD_VERTICAL.get().asItem(), BOPBlocks.dead_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.FIR_VERTICAL.get().asItem(), BOPBlocks.fir_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.HELLBARK_VERTICAL.get().asItem(), BOPBlocks.hellbark_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.JACARANDA_VERTICAL.get().asItem(), BOPBlocks.jacaranda_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.MAGIC_VERTICAL.get().asItem(), BOPBlocks.magic_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.MAHOGANY_VERTICAL.get().asItem(), BOPBlocks.mahogany_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.PALM_VERTICAL.get().asItem(), BOPBlocks.palm_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.REDWOOD_VERTICAL.get().asItem(), BOPBlocks.redwood_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.UMBRAN_VERTICAL.get().asItem(), BOPBlocks.umbran_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.WILLOW_VERTICAL.get().asItem(), BOPBlocks.willow_slab.asItem(), consumer);

		generateVerticalSlabRecipes(BOPVerticalSlabs.CHERRY_WOOD_VERTICAL.get().asItem(), BOPSlabs.CHERRY_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.DEAD_WOOD_VERTICAL.get().asItem(), BOPSlabs.DEAD_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.FIR_WOOD_VERTICAL.get().asItem(), BOPSlabs.FIR_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.HELLBARK_WOOD_VERTICAL.get().asItem(), BOPSlabs.HELLBARK_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.JACARANDA_WOOD_VERTICAL.get().asItem(), BOPSlabs.JACARANDA_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.MAGIC_WOOD_VERTICAL.get().asItem(), BOPSlabs.MAGIC_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.MAHOGANY_WOOD_VERTICAL.get().asItem(), BOPSlabs.MAHOGANY_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.PALM_WOOD_VERTICAL.get().asItem(), BOPSlabs.PALM_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.REDWOOD_WOOD_VERTICAL.get().asItem(), BOPSlabs.REDWOOD_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.UMBRAN_WOOD_VERTICAL.get().asItem(), BOPSlabs.UMBRAN_WOOD_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.WILLOW_WOOD_VERTICAL.get().asItem(), BOPSlabs.WILLOW_WOOD_SLAB.get().asItem(), consumer);

		generateVerticalSlabRecipes(BOPVerticalSlabs.MUD_BRICK_VERTICAL.get().asItem(), BOPBlocks.mud_brick_slab.asItem(), consumer);

		generateVerticalSlabRecipes(BOPVerticalSlabs.BLACK_SAND_VERTICAL.get().asItem(), BOPSlabs.BLACK_SAND_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.BLACK_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.black_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.SMOOTH_BLACK_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.smooth_black_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.CUT_BLACK_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.cut_black_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.ORANGE_SAND_VERTICAL.get().asItem(), BOPSlabs.ORANGE_SAND_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.ORANGE_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.orange_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.SMOOTH_ORANGE_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.smooth_orange_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.CUT_ORANGE_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.cut_orange_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.WHITE_SAND_VERTICAL.get().asItem(), BOPSlabs.WHITE_SAND_SLAB.get().asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.WHITE_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.white_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.SMOOTH_WHITE_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.smooth_white_sandstone_slab.asItem(), consumer);
		generateVerticalSlabRecipes(BOPVerticalSlabs.CUT_WHITE_SANDSTONE_VERTICAL.get().asItem(), BOPBlocks.cut_white_sandstone_slab.asItem(), consumer);

		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRASS_BLOCK_VERTICAL.get(), 6).define('#', Blocks.GRASS_BLOCK).pattern("#").pattern("#").pattern("#").unlockedBy("has_grass_block", has(Blocks.GRASS_BLOCK)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.DIRT_VERTICAL.get(), 6).define('#', Blocks.DIRT).pattern("#").pattern("#").pattern("#").unlockedBy("has_dirt", has(Blocks.DIRT)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.COARSE_DIRT_VERTICAL.get(), 6).define('#', Blocks.COARSE_DIRT).pattern("#").pattern("#").pattern("#").unlockedBy("has_coarse_dirt", has(Blocks.COARSE_DIRT)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PODZOL_VERTICAL.get(), 6).define('#', Blocks.PODZOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_podzol", has(Blocks.PODZOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MYCELIUM_VERTICAL.get(), 6).define('#', Blocks.MYCELIUM).pattern("#").pattern("#").pattern("#").unlockedBy("has_mycelium", has(Blocks.MYCELIUM)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRASS_PATH_VERTICAL.get(), 6).define('#', Blocks.GRASS_PATH).pattern("#").pattern("#").pattern("#").unlockedBy("has_grass_path", has(Blocks.GRASS_PATH)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SAND_VERTICAL.get(), 6).define('#', Blocks.SAND).pattern("#").pattern("#").pattern("#").unlockedBy("has_sand", has(Blocks.SAND)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_SAND_VERTICAL.get(), 6).define('#', Blocks.RED_SAND).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_sand", has(Blocks.RED_SAND)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRAVEL_VERTICAL.get(), 6).define('#', Blocks.GRAVEL).pattern("#").pattern("#").pattern("#").unlockedBy("has_gravel", has(Blocks.GRAVEL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WHITE_WOOL_VERTICAL.get(), 6).define('#', Blocks.WHITE_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_wool", has(Blocks.WHITE_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ORANGE_WOOL_VERTICAL.get(), 6).define('#', Blocks.ORANGE_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_wool", has(Blocks.ORANGE_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MAGENTA_WOOL_VERTICAL.get(), 6).define('#', Blocks.MAGENTA_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_magenta_wool", has(Blocks.MAGENTA_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_BLUE_WOOL_VERTICAL.get(), 6).define('#', Blocks.LIGHT_BLUE_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_blue_wool", has(Blocks.LIGHT_BLUE_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.YELLOW_WOOL_VERTICAL.get(), 6).define('#', Blocks.YELLOW_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_yellow_wool", has(Blocks.YELLOW_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIME_WOOL_VERTICAL.get(), 6).define('#', Blocks.LIME_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_lime_wool", has(Blocks.LIME_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PINK_WOOL_VERTICAL.get(), 6).define('#', Blocks.PINK_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_pink_wool", has(Blocks.PINK_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRAY_WOOL_VERTICAL.get(), 6).define('#', Blocks.GRAY_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_gray_wool", has(Blocks.GRAY_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_GRAY_WOOL_VERTICAL.get(), 6).define('#', Blocks.LIGHT_GRAY_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_gray_wool", has(Blocks.LIGHT_GRAY_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CYAN_WOOL_VERTICAL.get(), 6).define('#', Blocks.CYAN_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_cyan_wool", has(Blocks.CYAN_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PURPLE_WOOL_VERTICAL.get(), 6).define('#', Blocks.PURPLE_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_purple_wool", has(Blocks.PURPLE_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLUE_WOOL_VERTICAL.get(), 6).define('#', Blocks.BLUE_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_blue_wool", has(Blocks.BLUE_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BROWN_WOOL_VERTICAL.get(), 6).define('#', Blocks.BROWN_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_brown_wool", has(Blocks.BROWN_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GREEN_WOOL_VERTICAL.get(), 6).define('#', Blocks.GREEN_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_green_wool", has(Blocks.GREEN_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_WOOL_VERTICAL.get(), 6).define('#', Blocks.RED_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_wool", has(Blocks.RED_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLACK_WOOL_VERTICAL.get(), 6).define('#', Blocks.BLACK_WOOL).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_wool", has(Blocks.BLACK_WOOL)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WHITE_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.WHITE_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_concrete_powder", has(Blocks.WHITE_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ORANGE_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.ORANGE_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_concrete_powder", has(Blocks.ORANGE_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MAGENTA_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.MAGENTA_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_magenta_concrete_powder", has(Blocks.MAGENTA_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_BLUE_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.LIGHT_BLUE_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_blue_concrete_powder", has(Blocks.LIGHT_BLUE_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.YELLOW_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.YELLOW_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_yellow_concrete_powder", has(Blocks.YELLOW_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIME_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.LIME_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_lime_concrete_powder", has(Blocks.LIME_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PINK_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.PINK_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_pink_concrete_powder", has(Blocks.PINK_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRAY_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.GRAY_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_gray_concrete_powder", has(Blocks.GRAY_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_GRAY_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.LIGHT_GRAY_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_gray_concrete_powder", has(Blocks.LIGHT_GRAY_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CYAN_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.CYAN_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_cyan_concrete_powder", has(Blocks.CYAN_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PURPLE_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.PURPLE_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_purple_concrete_powder", has(Blocks.PURPLE_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLUE_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.BLUE_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_blue_concrete_powder", has(Blocks.BLUE_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BROWN_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.BROWN_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_brown_concrete_powder", has(Blocks.BROWN_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GREEN_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.GREEN_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_green_concrete_powder", has(Blocks.GREEN_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.RED_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_concrete_powder", has(Blocks.RED_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLACK_CONCRETE_POWDER_VERTICAL.get(), 6).define('#', Blocks.BLACK_CONCRETE_POWDER).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_concrete_powder", has(Blocks.BLACK_CONCRETE_POWDER)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WHITE_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.WHITE_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_concrete", has(Blocks.WHITE_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ORANGE_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.ORANGE_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_concrete", has(Blocks.ORANGE_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MAGENTA_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.MAGENTA_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_magenta_concrete", has(Blocks.MAGENTA_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_BLUE_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.LIGHT_BLUE_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_blue_concrete", has(Blocks.LIGHT_BLUE_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.YELLOW_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.YELLOW_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_yellow_concrete", has(Blocks.YELLOW_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIME_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.LIME_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_lime_concrete", has(Blocks.LIME_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PINK_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.PINK_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_pink_concrete", has(Blocks.PINK_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRAY_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.GRAY_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_gray_concrete", has(Blocks.GRAY_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_GRAY_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.LIGHT_GRAY_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_gray_concrete", has(Blocks.LIGHT_GRAY_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CYAN_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.CYAN_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_cyan_concrete", has(Blocks.CYAN_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PURPLE_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.PURPLE_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_purple_concrete", has(Blocks.PURPLE_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLUE_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.BLUE_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_blue_concrete", has(Blocks.BLUE_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BROWN_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.BROWN_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_brown_concrete", has(Blocks.BROWN_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GREEN_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.GREEN_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_green_concrete", has(Blocks.GREEN_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.RED_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_concrete", has(Blocks.RED_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLACK_CONCRETE_VERTICAL.get(), 6).define('#', Blocks.BLACK_CONCRETE).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_concrete", has(Blocks.BLACK_CONCRETE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CLAY_VERTICAL.get(), 6).define('#', Blocks.CLAY).pattern("#").pattern("#").pattern("#").unlockedBy("has_clay", has(Blocks.CLAY)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_terracotta", has(Blocks.TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WHITE_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.WHITE_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_terracotta", has(Blocks.WHITE_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ORANGE_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.ORANGE_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_terracotta", has(Blocks.ORANGE_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MAGENTA_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.MAGENTA_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_magenta_terracotta", has(Blocks.MAGENTA_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_BLUE_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.LIGHT_BLUE_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_blue_terracotta", has(Blocks.LIGHT_BLUE_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.YELLOW_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.YELLOW_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_yellow_terracotta", has(Blocks.YELLOW_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIME_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.LIME_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_lime_terracotta", has(Blocks.LIME_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PINK_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.PINK_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_pink_terracotta", has(Blocks.PINK_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRAY_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.GRAY_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_gray_terracotta", has(Blocks.GRAY_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_GRAY_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.LIGHT_GRAY_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_gray_terracotta", has(Blocks.LIGHT_GRAY_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CYAN_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.CYAN_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_cyan_terracotta", has(Blocks.CYAN_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PURPLE_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.PURPLE_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_purple_terracotta", has(Blocks.PURPLE_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLUE_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.BLUE_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_blue_terracotta", has(Blocks.BLUE_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BROWN_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.BROWN_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_brown_terracotta", has(Blocks.BROWN_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GREEN_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.GREEN_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_green_terracotta", has(Blocks.GREEN_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.RED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_terracotta", has(Blocks.RED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLACK_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.BLACK_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_terracotta", has(Blocks.BLACK_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WHITE_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.WHITE_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_glazed_terracotta", has(Blocks.WHITE_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ORANGE_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.ORANGE_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_glazed_terracotta", has(Blocks.ORANGE_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MAGENTA_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.MAGENTA_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_magenta_glazed_terracotta", has(Blocks.MAGENTA_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_blue_glazed_terracotta", has(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.YELLOW_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.YELLOW_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_yellow_glazed_terracotta", has(Blocks.YELLOW_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIME_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.LIME_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_lime_glazed_terracotta", has(Blocks.LIME_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PINK_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.PINK_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_pink_glazed_terracotta", has(Blocks.PINK_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRAY_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.GRAY_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_gray_glazed_terracotta", has(Blocks.GRAY_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_gray_glazed_terracotta", has(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CYAN_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.CYAN_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_cyan_glazed_terracotta", has(Blocks.CYAN_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PURPLE_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.PURPLE_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_purple_glazed_terracotta", has(Blocks.PURPLE_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLUE_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.BLUE_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_blue_glazed_terracotta", has(Blocks.BLUE_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BROWN_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.BROWN_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_brown_glazed_terracotta", has(Blocks.BROWN_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GREEN_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.GREEN_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_green_glazed_terracotta", has(Blocks.GREEN_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.RED_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_glazed_terracotta", has(Blocks.RED_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLACK_GLAZED_TERRACOTTA_VERTICAL.get(), 6).define('#', Blocks.BLACK_GLAZED_TERRACOTTA).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_glazed_terracotta", has(Blocks.BLACK_GLAZED_TERRACOTTA)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GLASS_VERTICAL.get(), 6).define('#', Blocks.GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_glass", has(Blocks.GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WHITE_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.WHITE_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_stained_glass", has(Blocks.WHITE_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ORANGE_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.ORANGE_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_stained_glass", has(Blocks.ORANGE_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MAGENTA_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.MAGENTA_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_magenta_stained_glass", has(Blocks.MAGENTA_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_BLUE_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.LIGHT_BLUE_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_blue_stained_glass", has(Blocks.LIGHT_BLUE_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.YELLOW_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.YELLOW_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_yellow_stained_glass", has(Blocks.YELLOW_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIME_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.LIME_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_lime_stained_glass", has(Blocks.LIME_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PINK_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.PINK_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_pink_stained_glass", has(Blocks.PINK_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRAY_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.GRAY_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_gray_stained_glass", has(Blocks.GRAY_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.LIGHT_GRAY_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.LIGHT_GRAY_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_light_gray_stained_glass", has(Blocks.LIGHT_GRAY_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CYAN_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.CYAN_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_cyan_stained_glass", has(Blocks.CYAN_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PURPLE_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.PURPLE_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_purple_stained_glass", has(Blocks.PURPLE_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLUE_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.BLUE_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_blue_stained_glass", has(Blocks.BLUE_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BROWN_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.BROWN_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_brown_stained_glass", has(Blocks.BROWN_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GREEN_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.GREEN_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_green_stained_glass", has(Blocks.GREEN_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.RED_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_stained_glass", has(Blocks.RED_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLACK_STAINED_GLASS_VERTICAL.get(), 6).define('#', Blocks.BLACK_STAINED_GLASS).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_stained_glass", has(Blocks.BLACK_STAINED_GLASS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.OAK_VERTICAL.get(), 6).define('#', Blocks.OAK_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_oak_planks", has(Blocks.OAK_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SPRUCE_VERTICAL.get(), 6).define('#', Blocks.SPRUCE_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_spruce_planks", has(Blocks.SPRUCE_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BIRCH_VERTICAL.get(), 6).define('#', Blocks.BIRCH_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_birch_planks", has(Blocks.BIRCH_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.JUNGLE_VERTICAL.get(), 6).define('#', Blocks.JUNGLE_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_jungle_planks", has(Blocks.JUNGLE_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ACACIA_VERTICAL.get(), 6).define('#', Blocks.ACACIA_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_acacia_planks", has(Blocks.ACACIA_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.DARK_OAK_VERTICAL.get(), 6).define('#', Blocks.DARK_OAK_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_dark_oak_planks", has(Blocks.DARK_OAK_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CRIMSON_VERTICAL.get(), 6).define('#', Blocks.CRIMSON_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_crimson_planks", has(Blocks.CRIMSON_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WARPED_VERTICAL.get(), 6).define('#', Blocks.WARPED_PLANKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_warped_planks", has(Blocks.WARPED_PLANKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.OAK_WOOD_VERTICAL.get(), 6).define('#', Blocks.OAK_WOOD).pattern("#").pattern("#").pattern("#").unlockedBy("has_oak_wood", has(Blocks.OAK_WOOD)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SPRUCE_WOOD_VERTICAL.get(), 6).define('#', Blocks.SPRUCE_WOOD).pattern("#").pattern("#").pattern("#").unlockedBy("has_spruce_wood", has(Blocks.SPRUCE_WOOD)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BIRCH_WOOD_VERTICAL.get(), 6).define('#', Blocks.BIRCH_WOOD).pattern("#").pattern("#").pattern("#").unlockedBy("has_birch_wood", has(Blocks.BIRCH_WOOD)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.JUNGLE_WOOD_VERTICAL.get(), 6).define('#', Blocks.JUNGLE_WOOD).pattern("#").pattern("#").pattern("#").unlockedBy("has_jungle_wood", has(Blocks.JUNGLE_WOOD)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ACACIA_WOOD_VERTICAL.get(), 6).define('#', Blocks.ACACIA_WOOD).pattern("#").pattern("#").pattern("#").unlockedBy("has_acacia_wood", has(Blocks.ACACIA_WOOD)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.DARK_OAK_WOOD_VERTICAL.get(), 6).define('#', Blocks.DARK_OAK_WOOD).pattern("#").pattern("#").pattern("#").unlockedBy("has_dark_oak_wood", has(Blocks.DARK_OAK_WOOD)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CRIMSON_HYPHAE_VERTICAL.get(), 6).define('#', Blocks.CRIMSON_HYPHAE).pattern("#").pattern("#").pattern("#").unlockedBy("has_crimson_hyphae", has(Blocks.CRIMSON_HYPHAE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WARPED_HYPHAE_VERTICAL.get(), 6).define('#', Blocks.WARPED_HYPHAE).pattern("#").pattern("#").pattern("#").unlockedBy("has_warped_hyphae", has(Blocks.WARPED_HYPHAE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.NETHERRACK_VERTICAL.get(), 6).define('#', Blocks.NETHERRACK).pattern("#").pattern("#").pattern("#").unlockedBy("has_netherrack", has(Blocks.NETHERRACK)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CRIMSON_NYLIUM_VERTICAL.get(), 6).define('#', Blocks.CRIMSON_NYLIUM).pattern("#").pattern("#").pattern("#").unlockedBy("has_crimson_nylium", has(Blocks.CRIMSON_NYLIUM)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.WARPED_NYLIUM_VERTICAL.get(), 6).define('#', Blocks.WARPED_NYLIUM).pattern("#").pattern("#").pattern("#").unlockedBy("has_warped_nylium", has(Blocks.WARPED_NYLIUM)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.NETHER_BRICK_VERTICAL.get(), 6).define('#', Blocks.NETHER_BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_nether_bricks", has(Blocks.NETHER_BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_NETHER_BRICK_VERTICAL.get(), 6).define('#', Blocks.RED_NETHER_BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_nether_bricks", has(Blocks.RED_NETHER_BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BLACKSTONE_VERTICAL.get(), 6).define('#', Blocks.BLACKSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_blackstone", has(Blocks.BLACKSTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.POLISHED_BLACKSTONE_VERTICAL.get(), 6).define('#', Blocks.POLISHED_BLACKSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_polished_blackstone", has(Blocks.POLISHED_BLACKSTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.POLISHED_BLACKSTONE_BRICK_VERTICAL.get(), 6).define('#', Blocks.POLISHED_BLACKSTONE_BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_polished_blackstone_bricks", has(Blocks.POLISHED_BLACKSTONE_BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.QUARTZ_VERTICAL.get(), 6).define('#', Blocks.QUARTZ_BLOCK).pattern("#").pattern("#").pattern("#").unlockedBy("has_quartz_block", has(Blocks.QUARTZ_BLOCK)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SMOOTH_QUARTZ_VERTICAL.get(), 6).define('#', Blocks.SMOOTH_QUARTZ).pattern("#").pattern("#").pattern("#").unlockedBy("has_smooth_quartz", has(Blocks.SMOOTH_QUARTZ)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.END_STONE_VERTICAL.get(), 6).define('#', Blocks.END_STONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_end_stone", has(Blocks.END_STONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.END_STONE_BRICK_VERTICAL.get(), 6).define('#', Blocks.END_STONE_BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_end_stone_bricks", has(Blocks.END_STONE_BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PURPUR_VERTICAL.get(), 6).define('#', Blocks.PURPUR_BLOCK).pattern("#").pattern("#").pattern("#").unlockedBy("has_purpur_block", has(Blocks.PURPUR_BLOCK)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.STONE_VERTICAL.get(), 6).define('#', Blocks.STONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_stone", has(Blocks.STONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.COBBLESTONE_VERTICAL.get(), 6).define('#', Blocks.COBBLESTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_cobblestone", has(Blocks.COBBLESTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.STONE_BRICK_VERTICAL.get(), 6).define('#', Blocks.STONE_BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_stone_bricks", has(Blocks.STONE_BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SMOOTH_STONE_VERTICAL.get(), 6).define('#', Blocks.SMOOTH_STONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_smooth_stone", has(Blocks.SMOOTH_STONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MOSSY_COBBLESTONE_VERTICAL.get(), 6).define('#', Blocks.MOSSY_COBBLESTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_mossy_cobblestone", has(Blocks.MOSSY_COBBLESTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.MOSSY_STONE_BRICK_VERTICAL.get(), 6).define('#', Blocks.MOSSY_STONE_BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_mossy_stone_bricks", has(Blocks.MOSSY_STONE_BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.ANDESITE_VERTICAL.get(), 6).define('#', Blocks.ANDESITE).pattern("#").pattern("#").pattern("#").unlockedBy("has_andesite", has(Blocks.ANDESITE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.POLISHED_ANDESITE_VERTICAL.get(), 6).define('#', Blocks.POLISHED_ANDESITE).pattern("#").pattern("#").pattern("#").unlockedBy("has_polished_andesite", has(Blocks.POLISHED_ANDESITE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.DIORITE_VERTICAL.get(), 6).define('#', Blocks.DIORITE).pattern("#").pattern("#").pattern("#").unlockedBy("has_diorite", has(Blocks.DIORITE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.POLISHED_DIORITE_VERTICAL.get(), 6).define('#', Blocks.POLISHED_DIORITE).pattern("#").pattern("#").pattern("#").unlockedBy("has_polished_diorite", has(Blocks.POLISHED_DIORITE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.GRANITE_VERTICAL.get(), 6).define('#', Blocks.GRANITE).pattern("#").pattern("#").pattern("#").unlockedBy("has_granite", has(Blocks.GRANITE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.POLISHED_GRANITE_VERTICAL.get(), 6).define('#', Blocks.POLISHED_GRANITE).pattern("#").pattern("#").pattern("#").unlockedBy("has_polished_granite", has(Blocks.POLISHED_GRANITE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.BRICK_VERTICAL.get(), 6).define('#', Blocks.BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_bricks", has(Blocks.BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PRISMARINE_VERTICAL.get(), 6).define('#', Blocks.PRISMARINE).pattern("#").pattern("#").pattern("#").unlockedBy("has_prismarine", has(Blocks.PRISMARINE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.PRISMARINE_BRICK_VERTICAL.get(), 6).define('#', Blocks.PRISMARINE_BRICKS).pattern("#").pattern("#").pattern("#").unlockedBy("has_prismarine_bricks", has(Blocks.PRISMARINE_BRICKS)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.DARK_PRISMARINE_VERTICAL.get(), 6).define('#', Blocks.DARK_PRISMARINE).pattern("#").pattern("#").pattern("#").unlockedBy("has_dark_prismarine", has(Blocks.DARK_PRISMARINE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SANDSTONE_VERTICAL.get(), 6).define('#', Blocks.SANDSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_sandstone", has(Blocks.SANDSTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SMOOTH_SANDSTONE_VERTICAL.get(), 6).define('#', Blocks.SMOOTH_SANDSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_smooth_sandstone", has(Blocks.SMOOTH_SANDSTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CUT_SANDSTONE_VERTICAL.get(), 6).define('#', Blocks.CUT_SANDSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_cut_sandstone", has(Blocks.CUT_SANDSTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.RED_SANDSTONE_VERTICAL.get(), 6).define('#', Blocks.RED_SANDSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_red_sandstone", has(Blocks.RED_SANDSTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.SMOOTH_RED_SANDSTONE_VERTICAL.get(), 6).define('#', Blocks.SMOOTH_RED_SANDSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_smooth_red_sandstone", has(Blocks.SMOOTH_RED_SANDSTONE)).save(consumer);
		ShapedRecipeBuilder.shaped(ESPVerticalSlabs.CUT_RED_SANDSTONE_VERTICAL.get(), 6).define('#', Blocks.CUT_RED_SANDSTONE).pattern("#").pattern("#").pattern("#").unlockedBy("has_cut_red_sandstone", has(Blocks.CUT_RED_SANDSTONE)).save(consumer);

		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.CHERRY_VERTICAL.get(), 6).define('#', BOPBlocks.cherry_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_cherry_planks", has(BOPBlocks.cherry_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.DEAD_VERTICAL.get(), 6).define('#', BOPBlocks.dead_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_dead_planks", has(BOPBlocks.dead_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.FIR_VERTICAL.get(), 6).define('#', BOPBlocks.fir_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_fir_planks", has(BOPBlocks.fir_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.HELLBARK_VERTICAL.get(), 6).define('#', BOPBlocks.hellbark_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_hellbark_planks", has(BOPBlocks.hellbark_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.JACARANDA_VERTICAL.get(), 6).define('#', BOPBlocks.jacaranda_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_jacaranda_planks", has(BOPBlocks.jacaranda_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.MAGIC_VERTICAL.get(), 6).define('#', BOPBlocks.magic_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_magic_planks", has(BOPBlocks.magic_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.MAHOGANY_VERTICAL.get(), 6).define('#', BOPBlocks.mahogany_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_mahogany_planks", has(BOPBlocks.mahogany_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.PALM_VERTICAL.get(), 6).define('#', BOPBlocks.palm_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_palm_planks", has(BOPBlocks.palm_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.REDWOOD_VERTICAL.get(), 6).define('#', BOPBlocks.redwood_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_redwood_planks", has(BOPBlocks.redwood_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.UMBRAN_VERTICAL.get(), 6).define('#', BOPBlocks.umbran_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_umbran_planks", has(BOPBlocks.umbran_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.WILLOW_VERTICAL.get(), 6).define('#', BOPBlocks.willow_planks).pattern("#").pattern("#").pattern("#").unlockedBy("has_willow_planks", has(BOPBlocks.willow_planks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.CHERRY_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.cherry_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_cherry_wood", has(BOPBlocks.cherry_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.DEAD_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.dead_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_dead_wood", has(BOPBlocks.dead_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.FIR_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.fir_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_fir_wood", has(BOPBlocks.fir_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.HELLBARK_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.hellbark_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_hellbark_wood", has(BOPBlocks.hellbark_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.JACARANDA_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.jacaranda_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_jacaranda_wood", has(BOPBlocks.jacaranda_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.MAGIC_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.magic_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_magic_wood", has(BOPBlocks.magic_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.MAHOGANY_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.mahogany_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_mahogany_wood", has(BOPBlocks.mahogany_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.PALM_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.palm_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_palm_wood", has(BOPBlocks.palm_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.REDWOOD_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.redwood_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_redwood_wood", has(BOPBlocks.redwood_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.UMBRAN_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.umbran_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_umbran_wood", has(BOPBlocks.umbran_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.WILLOW_WOOD_VERTICAL.get(), 6).define('#', BOPBlocks.willow_wood).pattern("#").pattern("#").pattern("#").unlockedBy("has_willow_wood", has(BOPBlocks.willow_wood)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.MUD_BRICK_VERTICAL.get(), 6).define('#', BOPBlocks.mud_bricks).pattern("#").pattern("#").pattern("#").unlockedBy("has_mud_bricks", has(BOPBlocks.mud_bricks)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.BLACK_SAND_VERTICAL.get(), 6).define('#', BOPBlocks.black_sand).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_sand", has(BOPBlocks.black_sand)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.BLACK_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.black_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_black_sandstone", has(BOPBlocks.black_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.SMOOTH_BLACK_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.smooth_black_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_smooth_black_sandstone", has(BOPBlocks.smooth_black_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.CUT_BLACK_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.cut_black_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_cut_black_sandstone", has(BOPBlocks.cut_black_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.ORANGE_SAND_VERTICAL.get(), 6).define('#', BOPBlocks.orange_sand).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_sand", has(BOPBlocks.orange_sand)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.ORANGE_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.orange_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_orange_sandstone", has(BOPBlocks.orange_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.SMOOTH_ORANGE_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.smooth_orange_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_smooth_orange_sandstone", has(BOPBlocks.smooth_orange_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.CUT_ORANGE_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.cut_orange_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_cut_orange_sandstone", has(BOPBlocks.cut_orange_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.WHITE_SAND_VERTICAL.get(), 6).define('#', BOPBlocks.white_sand).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_sand", has(BOPBlocks.white_sand)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.WHITE_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.white_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_white_sandstone", has(BOPBlocks.white_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.SMOOTH_WHITE_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.smooth_white_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_smooth_white_sandstone", has(BOPBlocks.smooth_white_sandstone)).save(consumer);
		ShapedRecipeBuilder.shaped(BOPVerticalSlabs.CUT_WHITE_SANDSTONE_VERTICAL.get(), 6).define('#', BOPBlocks.cut_white_sandstone).pattern("#").pattern("#").pattern("#").unlockedBy("has_cut_white_sandstone", has(BOPBlocks.cut_white_sandstone)).save(consumer);

		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.STONE), ESPVerticalSlabs.STONE_VERTICAL.get(), 2).unlocks("has_stone", has(Blocks.STONE)).save(consumer, "stone_vertical_slab_from_stone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.STONE), ESPVerticalSlabs.STONE_BRICK_VERTICAL.get(), 2).unlocks("has_stone", has(Blocks.STONE)).save(consumer, "stone_brick_vertical_slab_from_stone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.SANDSTONE), ESPVerticalSlabs.SANDSTONE_VERTICAL.get(), 2).unlocks("has_sandstone", has(Blocks.SANDSTONE)).save(consumer, "sandstone_vertical_slab_from_sandstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.SANDSTONE), ESPVerticalSlabs.CUT_SANDSTONE_VERTICAL.get(), 2).unlocks("has_sandstone", has(Blocks.SANDSTONE)).save(consumer, "cut_sandstone_vertical_slab_from_sandstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.CUT_SANDSTONE), ESPVerticalSlabs.CUT_SANDSTONE_VERTICAL.get(), 2).unlocks("has_sandstone", has(Blocks.SANDSTONE)).save(consumer, "cut_sandstone_vertical_slab_from_cut_sandstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.RED_SANDSTONE), ESPVerticalSlabs.RED_SANDSTONE_VERTICAL.get(), 2).unlocks("has_red_sandstone", has(Blocks.RED_SANDSTONE)).save(consumer, "red_sandstone_vertical_slab_from_red_sandstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.RED_SANDSTONE), ESPVerticalSlabs.CUT_RED_SANDSTONE_VERTICAL.get(), 2).unlocks("has_red_sandstone", has(Blocks.RED_SANDSTONE)).save(consumer, "cut_red_sandstone_vertical_slab_from_red_sandstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.CUT_RED_SANDSTONE), ESPVerticalSlabs.CUT_RED_SANDSTONE_VERTICAL.get(), 2).unlocks("has_cut_red_sandstone", has(Blocks.CUT_RED_SANDSTONE)).save(consumer, "cut_red_sandstone_vertical_slab_from_cut_red_sandstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.COBBLESTONE), ESPVerticalSlabs.COBBLESTONE_VERTICAL.get(), 2).unlocks("has_cobblestone", has(Blocks.COBBLESTONE)).save(consumer, "cobblestone_vertical_slab_from_cobblestone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.STONE_BRICKS), ESPVerticalSlabs.STONE_BRICK_VERTICAL.get(), 2).unlocks("has_stone_bricks", has(Blocks.STONE_BRICKS)).save(consumer, "stone_brick_vertical_slab_from_stone_bricks_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BRICKS), ESPVerticalSlabs.BRICK_VERTICAL.get(), 2).unlocks("has_bricks", has(Blocks.BRICKS)).save(consumer, "brick_vertical_slab_from_bricks_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.ANDESITE), ESPVerticalSlabs.ANDESITE_VERTICAL.get(), 2).unlocks("has_andesite", has(Blocks.ANDESITE)).save(consumer, "andesite_vertical_slab_from_andesite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.ANDESITE), ESPVerticalSlabs.POLISHED_ANDESITE_VERTICAL.get(), 2).unlocks("has_andesite", has(Blocks.ANDESITE)).save(consumer, "polished_andesite_vertical_slab_from_andesite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_ANDESITE), ESPVerticalSlabs.POLISHED_ANDESITE_VERTICAL.get(), 2).unlocks("has_polished_andesite", has(Blocks.POLISHED_ANDESITE)).save(consumer, "polished_andesite_vertical_slab_from_polished_andesite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.DIORITE), ESPVerticalSlabs.DIORITE_VERTICAL.get(), 2).unlocks("has_diorite", has(Blocks.DIORITE)).save(consumer, "diorite_vertical_slab_from_diorite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.DIORITE), ESPVerticalSlabs.POLISHED_DIORITE_VERTICAL.get(), 2).unlocks("has_diorite", has(Blocks.DIORITE)).save(consumer, "polished_diorite_vertical_slab_from_diorite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_DIORITE), ESPVerticalSlabs.POLISHED_DIORITE_VERTICAL.get(), 2).unlocks("has_polished_diorite", has(Blocks.POLISHED_DIORITE)).save(consumer, "polished_diorite_vertical_slab_from_polished_diorite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.GRANITE), ESPVerticalSlabs.GRANITE_VERTICAL.get(), 2).unlocks("has_granite", has(Blocks.GRANITE)).save(consumer, "granite_vertical_slab_from_granite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.GRANITE), ESPVerticalSlabs.POLISHED_GRANITE_VERTICAL.get(), 2).unlocks("has_granite", has(Blocks.GRANITE)).save(consumer, "polished_granite_vertical_slab_from_granite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_GRANITE), ESPVerticalSlabs.POLISHED_GRANITE_VERTICAL.get(), 2).unlocks("has_polished_granite", has(Blocks.POLISHED_GRANITE)).save(consumer, "polished_granite_vertical_slab_from_polished_granite_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.MOSSY_STONE_BRICKS), ESPVerticalSlabs.MOSSY_STONE_BRICK_VERTICAL.get(), 2).unlocks("has_mossy_stone_bricks", has(Blocks.MOSSY_STONE_BRICKS)).save(consumer, "mossy_stone_brick_vertical_slab_from_stone_bricks_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.MOSSY_COBBLESTONE), ESPVerticalSlabs.MOSSY_COBBLESTONE_VERTICAL.get(), 2).unlocks("has_mossy_cobblestone", has(Blocks.MOSSY_COBBLESTONE)).save(consumer, "mossy_cobblestone_vertical_slab_from_cobblestone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.SMOOTH_STONE), ESPVerticalSlabs.SMOOTH_STONE_VERTICAL.get(), 2).unlocks("has_smooth_stone", has(Blocks.SMOOTH_STONE)).save(consumer, "smooth_stone_vertical_slab_from_smooth_stone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.NETHERRACK), ESPVerticalSlabs.NETHERRACK_VERTICAL.get(), 2).unlocks("has_netherrack", has(Blocks.NETHERRACK)).save(consumer, "netherrack_vertical_slab_from_netherrack_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.NETHER_BRICKS), ESPVerticalSlabs.NETHER_BRICK_VERTICAL.get(), 2).unlocks("has_nether_bricks", has(Blocks.NETHER_BRICKS)).save(consumer, "nether_brick_vertical_slab_from_nether_bricks_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.RED_NETHER_BRICKS), ESPVerticalSlabs.RED_NETHER_BRICK_VERTICAL.get(), 2).unlocks("has_red_nether_bricks", has(Blocks.RED_NETHER_BRICKS)).save(consumer, "red_nether_brick_vertical_slab_from_red_nether_bricks_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BLACKSTONE), ESPVerticalSlabs.BLACKSTONE_VERTICAL.get(), 2).unlocks("has_blackstone", has(Blocks.BLACKSTONE)).save(consumer, "blackstone_vertical_slab_from_blackstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_BLACKSTONE), ESPVerticalSlabs.POLISHED_BLACKSTONE_VERTICAL.get(), 2).unlocks("has_polished_blackstone", has(Blocks.POLISHED_BLACKSTONE)).save(consumer, "polished_blackstone_vertical_slab_from_polished_blackstone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_BLACKSTONE_BRICKS), ESPVerticalSlabs.POLISHED_BLACKSTONE_BRICK_VERTICAL.get(), 2).unlocks("has_polished_blackstone_bricks", has(Blocks.POLISHED_BLACKSTONE_BRICKS)).save(consumer, "polished_blackstone_brick_vertical_slab_from_polished_blackstone_bricks_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.QUARTZ_BLOCK), ESPVerticalSlabs.QUARTZ_VERTICAL.get(), 2).unlocks("has_quartz_block", has(Blocks.QUARTZ_BLOCK)).save(consumer, "quartz_vertical_slab_from_quartz_block_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.SMOOTH_QUARTZ), ESPVerticalSlabs.SMOOTH_QUARTZ_VERTICAL.get(), 2).unlocks("has_smooth_quartz", has(Blocks.SMOOTH_QUARTZ)).save(consumer, "smooth_quartz_vertical_slab_from_smooth_quartz_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.END_STONE), ESPVerticalSlabs.END_STONE_VERTICAL.get(), 2).unlocks("has_end_stone", has(Blocks.END_STONE)).save(consumer, "end_stone_vertical_slab_from_end_stone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.END_STONE), ESPVerticalSlabs.END_STONE_BRICK_VERTICAL.get(), 2).unlocks("has_end_stone", has(Blocks.END_STONE)).save(consumer, "end_stone_brick_vertical_slab_from_end_stone_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.END_STONE_BRICKS), ESPVerticalSlabs.END_STONE_BRICK_VERTICAL.get(), 2).unlocks("has_end_stone_bricks", has(Blocks.END_STONE_BRICKS)).save(consumer, "end_stone_brick_vertical_slab_from_end_stone_brick_stonecutting");
		SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.PURPUR_BLOCK), ESPVerticalSlabs.PURPUR_VERTICAL.get(), 2).unlocks("has_purpur_block", has(Blocks.PURPUR_BLOCK)).save(consumer, "purpur_block_vertical_slab_from_purpur_block_stonecutting");
	}

	public void generateVerticalSlabRecipes(Item output, Item input, Consumer<IFinishedRecipe> consumer) {
		ExtendedSlabs.LOGGER.info(input.getRegistryName());

		ShapelessRecipeBuilder.shapeless(output)
				.requires(input)
				.unlockedBy("has_item", has(output))
				.save(consumer, input + "_to_" + output);
	}
}
