plugins {
	id 'net.fabricmc.fabric-loom' version '1.17.+'
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraftVersion}"
}

sourceSets {
	main {
		resources.srcDirs += ['src/main/generated']
	}
}

tasks.withType(JavaCompile).configureEach {
	enabled = false
}

tasks.withType(ProcessResources).configureEach {
	enabled = false
}

tasks.withType(Jar).configureEach {
	enabled = false
}

tasks.withType(Javadoc).configureEach {
	enabled = false
}
