plugins {
	id 'net.neoforged.moddev' version '2.0.0-beta'
}

neoForge {
	version = neoVersion

	runs {
		client {
			client()
			gameDirectory = file('run')
		}
		server {
			server()
			gameDirectory = file('run')
		}
		data {
			data()
			gameDirectory = file('run')
			programArguments.addAll '--mod', modId, '--all', '--output', file('src/main/generated/').absolutePath, '--existing', file('src/main/resources/').absolutePath
		}
	}

	mods {
		"${modId}" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	implementation project(':common')
}

sourceSets {
	main {
		java.srcDir project(':common').sourceSets.main.java.srcDirs
		resources.srcDir project(':common').sourceSets.main.resources.srcDirs
	}
}
