plugins {
	id 'net.neoforged.moddev' version '2.0.0-beta'
}

neoForge {
	version = neoVersion

	mods {
		"${modId}" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	implementation project(':common')
}

sourceSets {
	main {
		java.srcDir project(':common').sourceSets.main.java.srcDirs
		resources.srcDir project(':common').sourceSets.main.resources.srcDirs
	}
}
