package com.blackout.extendedslabs.init;

import com.blackout.extendedslabs.ExtendedSlabs;
import com.blackout.extendedslabs.blocks.ESPStairBlock;
import com.blackout.extendedslabs.blocks.falling.FallingStairBlock;
import com.blackout.extendedslabs.blocks.glass.GlassStairBlock;
import com.blackout.extendedslabs.blocks.glass.StainedGlassStairBlock;
import com.blackout.extendedslabs.blocks.glass.TintedGlassStairBlock;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.StairBlock;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.Collection;
import java.util.function.Supplier;

import static com.blackout.extendedslabs.blocks.IBlockCharacteristics.tag;

@Mod.EventBusSubscriber(modid = ExtendedSlabs.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ESPStairs {
	public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, ExtendedSlabs.MODID);
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ExtendedSlabs.MODID);

	// DIRT
	public static final RegistryObject<Block> DIRT_STAIRS = registerBlock("dirt_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.DIRT, () -> ESPCorners.DIRT_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.DIRT)));
	public static final RegistryObject<Block> COARSE_DIRT_STAIRS = registerBlock("coarse_dirt_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.COARSE_DIRT, () -> ESPCorners.COARSE_DIRT_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.COARSE_DIRT)));
	public static final RegistryObject<Block> ROOTED_DIRT_STAIRS = registerBlock("rooted_dirt_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.ROOTED_DIRT, () -> ESPCorners.ROOTED_DIRT_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.ROOTED_DIRT)));
	public static final RegistryObject<Block> SAND_STAIRS = registerBlock("sand_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.SAND, () -> ESPCorners.SAND_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.SAND)));
	public static final RegistryObject<Block> RED_SAND_STAIRS = registerBlock("red_sand_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.RED_SAND, () -> ESPCorners.RED_SAND_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.RED_SAND)));
	public static final RegistryObject<Block> GRAVEL_STAIRS = registerBlock("gravel_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GRAVEL, () -> ESPCorners.GRAVEL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GRAVEL)));

	// STONE
	public static final RegistryObject<Block> SMOOTH_STONE_STAIRS = registerBlock("smooth_stone_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_STONE, () -> ESPCorners.SMOOTH_STONE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.SMOOTH_STONE)));
	public static final RegistryObject<Block> TUFF_STAIRS = registerBlock("tuff_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.TUFF, () -> ESPCorners.TUFF_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.TUFF)));
	public static final RegistryObject<Block> CALCITE_STAIRS = registerBlock("calcite_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CALCITE, () -> ESPCorners.CALCITE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CALCITE)));
	public static final RegistryObject<Block> DRIPSTONE_STAIRS = registerBlock("dripstone_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DRIPSTONE_BLOCK, () -> ESPCorners.DRIPSTONE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.DRIPSTONE_BLOCK)));
	public static final RegistryObject<Block> MUD_STAIRS = registerBlock("mud_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.MUD, () -> ESPCorners.MUD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.MUD)));
	public static final RegistryObject<Block> PACKED_MUD_STAIRS = registerBlock("packed_mud_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PACKED_MUD, () -> ESPCorners.PACKED_MUD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PACKED_MUD)));

	// WOOL
	public static final RegistryObject<Block> WHITE_WOOL_STAIRS = registerBlock("white_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.WHITE_WOOL, () -> ESPCorners.WHITE_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> ORANGE_WOOL_STAIRS = registerBlock("orange_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.ORANGE_WOOL, () -> ESPCorners.ORANGE_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.ORANGE_WOOL)));
	public static final RegistryObject<Block> MAGENTA_WOOL_STAIRS = registerBlock("magenta_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.MAGENTA_WOOL, () -> ESPCorners.MAGENTA_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.MAGENTA_WOOL)));
	public static final RegistryObject<Block> LIGHT_BLUE_WOOL_STAIRS = registerBlock("light_blue_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.LIGHT_BLUE_WOOL, () -> ESPCorners.LIGHT_BLUE_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_BLUE_WOOL)));
	public static final RegistryObject<Block> YELLOW_WOOL_STAIRS = registerBlock("yellow_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.YELLOW_WOOL, () -> ESPCorners.YELLOW_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.YELLOW_WOOL)));
	public static final RegistryObject<Block> LIME_WOOL_STAIRS = registerBlock("lime_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.LIME_WOOL, () -> ESPCorners.LIME_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIME_WOOL)));
	public static final RegistryObject<Block> PINK_WOOL_STAIRS = registerBlock("pink_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.PINK_WOOL, () -> ESPCorners.PINK_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PINK_WOOL)));
	public static final RegistryObject<Block> GRAY_WOOL_STAIRS = registerBlock("gray_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.GRAY_WOOL, () -> ESPCorners.GRAY_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GRAY_WOOL)));
	public static final RegistryObject<Block> LIGHT_GRAY_WOOL_STAIRS = registerBlock("light_gray_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.LIGHT_GRAY_WOOL, () -> ESPCorners.LIGHT_GRAY_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_GRAY_WOOL)));
	public static final RegistryObject<Block> CYAN_WOOL_STAIRS = registerBlock("cyan_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.CYAN_WOOL, () -> ESPCorners.CYAN_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CYAN_WOOL)));
	public static final RegistryObject<Block> PURPLE_WOOL_STAIRS = registerBlock("purple_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.PURPLE_WOOL, () -> ESPCorners.PURPLE_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PURPLE_WOOL)));
	public static final RegistryObject<Block> BLUE_WOOL_STAIRS = registerBlock("blue_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.BLUE_WOOL, () -> ESPCorners.BLUE_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLUE_WOOL)));
	public static final RegistryObject<Block> BROWN_WOOL_STAIRS = registerBlock("brown_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.BROWN_WOOL, () -> ESPCorners.BROWN_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BROWN_WOOL)));
	public static final RegistryObject<Block> GREEN_WOOL_STAIRS = registerBlock("green_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.GREEN_WOOL, () -> ESPCorners.GREEN_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GREEN_WOOL)));
	public static final RegistryObject<Block> RED_WOOL_STAIRS = registerBlock("red_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.RED_WOOL, () -> ESPCorners.RED_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.RED_WOOL)));
	public static final RegistryObject<Block> BLACK_WOOL_STAIRS = registerBlock("black_wool_stairs", () -> new ESPStairBlock(tag(BlockTags.WOOL), Blocks.BLACK_WOOL, () -> ESPCorners.BLACK_WOOL_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLACK_WOOL)));

	// CONCRETE_POWDER
	public static final RegistryObject<Block> WHITE_CONCRETE_POWDER_STAIRS = registerBlock("white_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.WHITE_CONCRETE_POWDER, () -> ESPCorners.WHITE_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> ORANGE_CONCRETE_POWDER_STAIRS = registerBlock("orange_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.ORANGE_CONCRETE_POWDER, () -> ESPCorners.ORANGE_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.ORANGE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> MAGENTA_CONCRETE_POWDER_STAIRS = registerBlock("magenta_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.MAGENTA_CONCRETE_POWDER, () -> ESPCorners.MAGENTA_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.MAGENTA_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_POWDER_STAIRS = registerBlock("light_blue_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIGHT_BLUE_CONCRETE_POWDER, () -> ESPCorners.LIGHT_BLUE_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> YELLOW_CONCRETE_POWDER_STAIRS = registerBlock("yellow_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.YELLOW_CONCRETE_POWDER, () -> ESPCorners.YELLOW_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.YELLOW_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIME_CONCRETE_POWDER_STAIRS = registerBlock("lime_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIME_CONCRETE_POWDER, () -> ESPCorners.LIME_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIME_CONCRETE_POWDER)));
	public static final RegistryObject<Block> PINK_CONCRETE_POWDER_STAIRS = registerBlock("pink_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.PINK_CONCRETE_POWDER, () -> ESPCorners.PINK_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PINK_CONCRETE_POWDER)));
	public static final RegistryObject<Block> GRAY_CONCRETE_POWDER_STAIRS = registerBlock("gray_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GRAY_CONCRETE_POWDER, () -> ESPCorners.GRAY_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GRAY_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_POWDER_STAIRS = registerBlock("light_gray_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIGHT_GRAY_CONCRETE_POWDER, () -> ESPCorners.LIGHT_GRAY_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE_POWDER)));
	public static final RegistryObject<Block> CYAN_CONCRETE_POWDER_STAIRS = registerBlock("cyan_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.CYAN_CONCRETE_POWDER, () -> ESPCorners.CYAN_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CYAN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> PURPLE_CONCRETE_POWDER_STAIRS = registerBlock("purple_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.PURPLE_CONCRETE_POWDER, () -> ESPCorners.PURPLE_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PURPLE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BLUE_CONCRETE_POWDER_STAIRS = registerBlock("blue_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BLUE_CONCRETE_POWDER, () -> ESPCorners.BLUE_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLUE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BROWN_CONCRETE_POWDER_STAIRS = registerBlock("brown_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BROWN_CONCRETE_POWDER, () -> ESPCorners.BROWN_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BROWN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> GREEN_CONCRETE_POWDER_STAIRS = registerBlock("green_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GREEN_CONCRETE_POWDER, () -> ESPCorners.GREEN_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GREEN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> RED_CONCRETE_POWDER_STAIRS = registerBlock("red_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.RED_CONCRETE_POWDER, () -> ESPCorners.RED_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.RED_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BLACK_CONCRETE_POWDER_STAIRS = registerBlock("black_concrete_powder_stairs", () -> new FallingStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BLACK_CONCRETE_POWDER, () -> ESPCorners.BLACK_CONCRETE_POWDER_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLACK_CONCRETE_POWDER)));

	// CONCRETE
	public static final RegistryObject<Block> WHITE_CONCRETE_STAIRS = registerBlock("white_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_CONCRETE, () -> ESPCorners.WHITE_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_CONCRETE)));
	public static final RegistryObject<Block> ORANGE_CONCRETE_STAIRS = registerBlock("orange_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_CONCRETE, () -> ESPCorners.ORANGE_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.ORANGE_CONCRETE)));
	public static final RegistryObject<Block> MAGENTA_CONCRETE_STAIRS = registerBlock("magenta_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_CONCRETE, () -> ESPCorners.MAGENTA_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.MAGENTA_CONCRETE)));
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_STAIRS = registerBlock("light_blue_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_CONCRETE, () -> ESPCorners.LIGHT_BLUE_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE)));
	public static final RegistryObject<Block> YELLOW_CONCRETE_STAIRS = registerBlock("yellow_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_CONCRETE, () -> ESPCorners.YELLOW_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.YELLOW_CONCRETE)));
	public static final RegistryObject<Block> LIME_CONCRETE_STAIRS = registerBlock("lime_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_CONCRETE, () -> ESPCorners.LIME_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIME_CONCRETE)));
	public static final RegistryObject<Block> PINK_CONCRETE_STAIRS = registerBlock("pink_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_CONCRETE, () -> ESPCorners.PINK_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PINK_CONCRETE)));
	public static final RegistryObject<Block> GRAY_CONCRETE_STAIRS = registerBlock("gray_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_CONCRETE, () -> ESPCorners.GRAY_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GRAY_CONCRETE)));
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_STAIRS = registerBlock("light_gray_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_CONCRETE, () -> ESPCorners.LIGHT_GRAY_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE)));
	public static final RegistryObject<Block> CYAN_CONCRETE_STAIRS = registerBlock("cyan_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_CONCRETE, () -> ESPCorners.CYAN_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CYAN_CONCRETE)));
	public static final RegistryObject<Block> PURPLE_CONCRETE_STAIRS = registerBlock("purple_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_CONCRETE, () -> ESPCorners.PURPLE_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PURPLE_CONCRETE)));
	public static final RegistryObject<Block> BLUE_CONCRETE_STAIRS = registerBlock("blue_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_CONCRETE, () -> ESPCorners.BLUE_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLUE_CONCRETE)));
	public static final RegistryObject<Block> BROWN_CONCRETE_STAIRS = registerBlock("brown_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_CONCRETE, () -> ESPCorners.BROWN_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BROWN_CONCRETE)));
	public static final RegistryObject<Block> GREEN_CONCRETE_STAIRS = registerBlock("green_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_CONCRETE, () -> ESPCorners.GREEN_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GREEN_CONCRETE)));
	public static final RegistryObject<Block> RED_CONCRETE_STAIRS = registerBlock("red_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_CONCRETE, () -> ESPCorners.RED_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.RED_CONCRETE)));
	public static final RegistryObject<Block> BLACK_CONCRETE_STAIRS = registerBlock("black_concrete_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_CONCRETE, () -> ESPCorners.BLACK_CONCRETE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLACK_CONCRETE)));

	// TERRACOTTA
	public static final RegistryObject<Block> CLAY_STAIRS = registerBlock("clay_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.CLAY, () -> ESPCorners.CLAY_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CLAY)));
	public static final RegistryObject<Block> TERRACOTTA_STAIRS = registerBlock("terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.TERRACOTTA, () -> ESPCorners.TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.TERRACOTTA)));
	public static final RegistryObject<Block> WHITE_TERRACOTTA_STAIRS = registerBlock("white_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_TERRACOTTA, () -> ESPCorners.WHITE_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_TERRACOTTA)));
	public static final RegistryObject<Block> ORANGE_TERRACOTTA_STAIRS = registerBlock("orange_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_TERRACOTTA, () -> ESPCorners.ORANGE_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.ORANGE_TERRACOTTA)));
	public static final RegistryObject<Block> MAGENTA_TERRACOTTA_STAIRS = registerBlock("magenta_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_TERRACOTTA, () -> ESPCorners.MAGENTA_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.MAGENTA_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_BLUE_TERRACOTTA_STAIRS = registerBlock("light_blue_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_TERRACOTTA, () -> ESPCorners.LIGHT_BLUE_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_BLUE_TERRACOTTA)));
	public static final RegistryObject<Block> YELLOW_TERRACOTTA_STAIRS = registerBlock("yellow_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_TERRACOTTA, () -> ESPCorners.YELLOW_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.YELLOW_TERRACOTTA)));
	public static final RegistryObject<Block> LIME_TERRACOTTA_STAIRS = registerBlock("lime_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_TERRACOTTA, () -> ESPCorners.LIME_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIME_TERRACOTTA)));
	public static final RegistryObject<Block> PINK_TERRACOTTA_STAIRS = registerBlock("pink_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_TERRACOTTA, () -> ESPCorners.PINK_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PINK_TERRACOTTA)));
	public static final RegistryObject<Block> GRAY_TERRACOTTA_STAIRS = registerBlock("gray_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_TERRACOTTA, () -> ESPCorners.GRAY_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GRAY_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_GRAY_TERRACOTTA_STAIRS = registerBlock("light_gray_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_TERRACOTTA, () -> ESPCorners.LIGHT_GRAY_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_GRAY_TERRACOTTA)));
	public static final RegistryObject<Block> CYAN_TERRACOTTA_STAIRS = registerBlock("cyan_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_TERRACOTTA, () -> ESPCorners.CYAN_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CYAN_TERRACOTTA)));
	public static final RegistryObject<Block> PURPLE_TERRACOTTA_STAIRS = registerBlock("purple_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_TERRACOTTA, () -> ESPCorners.PURPLE_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PURPLE_TERRACOTTA)));
	public static final RegistryObject<Block> BLUE_TERRACOTTA_STAIRS = registerBlock("blue_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_TERRACOTTA, () -> ESPCorners.BLUE_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLUE_TERRACOTTA)));
	public static final RegistryObject<Block> BROWN_TERRACOTTA_STAIRS = registerBlock("brown_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_TERRACOTTA, () -> ESPCorners.BROWN_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BROWN_TERRACOTTA)));
	public static final RegistryObject<Block> GREEN_TERRACOTTA_STAIRS = registerBlock("green_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_TERRACOTTA, () -> ESPCorners.GREEN_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GREEN_TERRACOTTA)));
	public static final RegistryObject<Block> RED_TERRACOTTA_STAIRS = registerBlock("red_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_TERRACOTTA, () -> ESPCorners.RED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.RED_TERRACOTTA)));
	public static final RegistryObject<Block> BLACK_TERRACOTTA_STAIRS = registerBlock("black_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_TERRACOTTA, () -> ESPCorners.BLACK_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLACK_TERRACOTTA)));

	// GLAZED TERRACOTTA
	public static final RegistryObject<Block> WHITE_GLAZED_TERRACOTTA_STAIRS = registerBlock("white_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_GLAZED_TERRACOTTA, () -> ESPCorners.WHITE_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> ORANGE_GLAZED_TERRACOTTA_STAIRS = registerBlock("orange_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_GLAZED_TERRACOTTA, () -> ESPCorners.ORANGE_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.ORANGE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> MAGENTA_GLAZED_TERRACOTTA_STAIRS = registerBlock("magenta_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_GLAZED_TERRACOTTA, () -> ESPCorners.MAGENTA_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.MAGENTA_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS = registerBlock("light_blue_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, () -> ESPCorners.LIGHT_BLUE_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> YELLOW_GLAZED_TERRACOTTA_STAIRS = registerBlock("yellow_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_GLAZED_TERRACOTTA, () -> ESPCorners.YELLOW_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.YELLOW_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIME_GLAZED_TERRACOTTA_STAIRS = registerBlock("lime_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_GLAZED_TERRACOTTA, () -> ESPCorners.LIME_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIME_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> PINK_GLAZED_TERRACOTTA_STAIRS = registerBlock("pink_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_GLAZED_TERRACOTTA, () -> ESPCorners.PINK_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PINK_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> GRAY_GLAZED_TERRACOTTA_STAIRS = registerBlock("gray_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_GLAZED_TERRACOTTA, () -> ESPCorners.GRAY_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GRAY_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS = registerBlock("light_gray_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, () -> ESPCorners.LIGHT_GRAY_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> CYAN_GLAZED_TERRACOTTA_STAIRS = registerBlock("cyan_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_GLAZED_TERRACOTTA, () -> ESPCorners.CYAN_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CYAN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> PURPLE_GLAZED_TERRACOTTA_STAIRS = registerBlock("purple_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_GLAZED_TERRACOTTA, () -> ESPCorners.PURPLE_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.PURPLE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BLUE_GLAZED_TERRACOTTA_STAIRS = registerBlock("blue_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_GLAZED_TERRACOTTA, () -> ESPCorners.BLUE_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLUE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BROWN_GLAZED_TERRACOTTA_STAIRS = registerBlock("brown_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_GLAZED_TERRACOTTA, () -> ESPCorners.BROWN_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BROWN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> GREEN_GLAZED_TERRACOTTA_STAIRS = registerBlock("green_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_GLAZED_TERRACOTTA, () -> ESPCorners.GREEN_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GREEN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> RED_GLAZED_TERRACOTTA_STAIRS = registerBlock("red_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_GLAZED_TERRACOTTA, () -> ESPCorners.RED_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.RED_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BLACK_GLAZED_TERRACOTTA_STAIRS = registerBlock("black_glazed_terracotta_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_GLAZED_TERRACOTTA, () -> ESPCorners.BLACK_GLAZED_TERRACOTTA_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BLACK_GLAZED_TERRACOTTA)));

	// GLASS
	public static final RegistryObject<Block> GLASS_STAIRS = registerBlock("glass_stairs", () -> new GlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.GLASS, () -> ESPCorners.GLASS_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.GLASS)));
	public static final RegistryObject<Block> TINTED_GLASS_STAIRS = registerBlock("tinted_glass_stairs", () -> new TintedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.TINTED_GLASS, () -> ESPCorners.TINTED_GLASS_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.TINTED_GLASS)));
	public static final RegistryObject<Block> WHITE_STAINED_GLASS_STAIRS = registerBlock("white_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.WHITE_STAINED_GLASS, () -> ESPCorners.WHITE_STAINED_GLASS_CORNER.get(), DyeColor.WHITE, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> ORANGE_STAINED_GLASS_STAIRS = registerBlock("orange_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.ORANGE_STAINED_GLASS, () -> ESPCorners.ORANGE_STAINED_GLASS_CORNER.get(), DyeColor.ORANGE, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> MAGENTA_STAINED_GLASS_STAIRS = registerBlock("magenta_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.MAGENTA_STAINED_GLASS, () -> ESPCorners.MAGENTA_STAINED_GLASS_CORNER.get(), DyeColor.MAGENTA, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIGHT_BLUE_STAINED_GLASS_STAIRS = registerBlock("light_blue_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIGHT_BLUE_STAINED_GLASS, () -> ESPCorners.LIGHT_BLUE_STAINED_GLASS_CORNER.get(), DyeColor.LIGHT_BLUE, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> YELLOW_STAINED_GLASS_STAIRS = registerBlock("yellow_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.YELLOW_STAINED_GLASS, () -> ESPCorners.YELLOW_STAINED_GLASS_CORNER.get(), DyeColor.YELLOW, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIME_STAINED_GLASS_STAIRS = registerBlock("lime_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIME_STAINED_GLASS, () -> ESPCorners.LIME_STAINED_GLASS_CORNER.get(), DyeColor.LIME, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> PINK_STAINED_GLASS_STAIRS = registerBlock("pink_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.PINK_STAINED_GLASS, () -> ESPCorners.PINK_STAINED_GLASS_CORNER.get(), DyeColor.PINK, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> GRAY_STAINED_GLASS_STAIRS = registerBlock("gray_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.GRAY_STAINED_GLASS, () -> ESPCorners.GRAY_STAINED_GLASS_CORNER.get(), DyeColor.GRAY, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIGHT_GRAY_STAINED_GLASS_STAIRS = registerBlock("light_gray_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIGHT_GRAY_STAINED_GLASS, () -> ESPCorners.LIGHT_GRAY_STAINED_GLASS_CORNER.get(), DyeColor.LIGHT_GRAY, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> CYAN_STAINED_GLASS_STAIRS = registerBlock("cyan_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.CYAN_STAINED_GLASS, () -> ESPCorners.CYAN_STAINED_GLASS_CORNER.get(), DyeColor.CYAN, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> PURPLE_STAINED_GLASS_STAIRS = registerBlock("purple_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.PURPLE_STAINED_GLASS, () -> ESPCorners.PURPLE_STAINED_GLASS_CORNER.get(), DyeColor.PURPLE, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BLUE_STAINED_GLASS_STAIRS = registerBlock("blue_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.BLUE_STAINED_GLASS, () -> ESPCorners.BLUE_STAINED_GLASS_CORNER.get(), DyeColor.BLUE, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BROWN_STAINED_GLASS_STAIRS = registerBlock("brown_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.BROWN_STAINED_GLASS, () -> ESPCorners.BROWN_STAINED_GLASS_CORNER.get(), DyeColor.BROWN, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> GREEN_STAINED_GLASS_STAIRS = registerBlock("green_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.GREEN_STAINED_GLASS, () -> ESPCorners.GREEN_STAINED_GLASS_CORNER.get(), DyeColor.GREEN, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> RED_STAINED_GLASS_STAIRS = registerBlock("red_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.RED_STAINED_GLASS, () -> ESPCorners.RED_STAINED_GLASS_CORNER.get(), DyeColor.RED, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BLACK_STAINED_GLASS_STAIRS = registerBlock("black_stained_glass_stairs", () -> new StainedGlassStairBlock(tag(BlockTags.IMPERMEABLE), Blocks.BLACK_STAINED_GLASS, () -> ESPCorners.BLACK_STAINED_GLASS_CORNER.get(), DyeColor.BLACK, () -> Block.stateById(1), Block.Properties.copy(Blocks.WHITE_WOOL)));

	// SANDSTONE
	public static final RegistryObject<Block> CUT_SANDSTONE_STAIRS = registerBlock("cut_sandstone_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CUT_SANDSTONE, () -> ESPCorners.CUT_SANDSTONE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CUT_SANDSTONE)));
	public static final RegistryObject<Block> CUT_RED_SANDSTONE_STAIRS = registerBlock("cut_red_sandstone_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CUT_RED_SANDSTONE, () -> ESPCorners.CUT_RED_SANDSTONE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CUT_RED_SANDSTONE)));

	// WOOD
	public static final RegistryObject<Block> OAK_WOOD_STAIRS = registerBlock("oak_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.OAK_WOOD, () -> ESPCorners.OAK_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.OAK_WOOD)));
	public static final RegistryObject<Block> SPRUCE_WOOD_STAIRS = registerBlock("spruce_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.SPRUCE_WOOD, () -> ESPCorners.SPRUCE_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.SPRUCE_WOOD)));
	public static final RegistryObject<Block> BIRCH_WOOD_STAIRS = registerBlock("birch_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BIRCH_WOOD, () -> ESPCorners.BIRCH_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.BIRCH_WOOD)));
	public static final RegistryObject<Block> JUNGLE_WOOD_STAIRS = registerBlock("jungle_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.JUNGLE_WOOD, () -> ESPCorners.JUNGLE_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.JUNGLE_WOOD)));
	public static final RegistryObject<Block> ACACIA_WOOD_STAIRS = registerBlock("acacia_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.ACACIA_WOOD, () -> ESPCorners.ACACIA_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.ACACIA_WOOD)));
	public static final RegistryObject<Block> DARK_OAK_WOOD_STAIRS = registerBlock("dark_oak_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.DARK_OAK_WOOD, () -> ESPCorners.DARK_OAK_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.DARK_OAK_WOOD)));
	public static final RegistryObject<Block> MANGROVE_WOOD_STAIRS = registerBlock("mangrove_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.MANGROVE_WOOD, () -> ESPCorners.MANGROVE_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.MANGROVE_WOOD)));
	public static final RegistryObject<Block> CHERRY_WOOD_STAIRS = registerBlock("cherry_wood_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CHERRY_WOOD, () -> ESPCorners.CHERRY_WOOD_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CHERRY_WOOD)));
	public static final RegistryObject<Block> CRIMSON_HYPHAE_STAIRS = registerBlock("crimson_hyphae_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CRIMSON_HYPHAE, () -> ESPCorners.CRIMSON_HYPHAE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.CRIMSON_HYPHAE)));
	public static final RegistryObject<Block> WARPED_HYPHAE_STAIRS = registerBlock("warped_hyphae_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.WARPED_HYPHAE, () -> ESPCorners.WARPED_HYPHAE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.WARPED_HYPHAE)));

	// NETHER
	public static final RegistryObject<StairBlock> NETHERRACK_STAIRS = registerBlock("netherrack_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.NETHERRACK, () -> ESPCorners.NETHERRACK_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.NETHERRACK)));

	// END
	public static final RegistryObject<StairBlock> END_STONE_STAIRS = registerBlock("end_stone_stairs", () -> new ESPStairBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.END_STONE, () -> ESPCorners.END_STONE_CORNER.get(), () -> Block.stateById(1), Block.Properties.copy(Blocks.END_STONE)));

	public static <B extends Block> RegistryObject<B> registerBlock(String name, Supplier<? extends B> supplier) {
		RegistryObject<B> block = BLOCKS.register(name, supplier);
		ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
		return block;
	}

	public static Collection<RegistryObject<Item>> orderedItems() {
		return ITEMS.getEntries();
	}
}
