package com.blackout.extendedslabs.init;

import com.blackout.extendedslabs.ExtendedSlabs;
import com.blackout.extendedslabs.blocks.ESPVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.copper.WeatheringCopperVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.falling.FallingVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.glass.GlassVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.glass.StainedGlassVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.glass.TintedGlassVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.path.PathVerticalSlabBlock;
import net.minecraft.core.BlockPos;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.WeatheringCopper;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.Collection;
import java.util.function.Supplier;

import static com.blackout.extendedslabs.blocks.IBlockCharacteristics.tag;

@Mod.EventBusSubscriber(modid = ExtendedSlabs.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ESPVerticalSlabs {
	public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, ExtendedSlabs.MODID);
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ExtendedSlabs.MODID);

	// DIRT
	public static final RegistryObject<Block> GRASS_BLOCK_VERTICAL = registerBlock("vertical_grass_block_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GRASS_BLOCK, ESPSlabs.GRASS_BLOCK_SLAB.get(), Block.Properties.copy(Blocks.GRASS_BLOCK)));
	public static final RegistryObject<Block> DIRT_VERTICAL = registerBlock("vertical_dirt_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.DIRT, ESPSlabs.DIRT_SLAB.get(), Block.Properties.copy(Blocks.DIRT)));
	public static final RegistryObject<Block> COARSE_DIRT_VERTICAL = registerBlock("vertical_coarse_dirt_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.COARSE_DIRT, ESPSlabs.COARSE_DIRT_SLAB.get(), Block.Properties.copy(Blocks.COARSE_DIRT)));
	public static final RegistryObject<Block> ROOTED_DIRT_VERTICAL = registerBlock("vertical_rooted_dirt_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.ROOTED_DIRT, ESPSlabs.ROOTED_DIRT_SLAB.get(), Block.Properties.copy(Blocks.ROOTED_DIRT)));
	public static final RegistryObject<Block> PODZOL_VERTICAL = registerBlock("vertical_podzol_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.PODZOL, ESPSlabs.PODZOL_SLAB.get(), Block.Properties.copy(Blocks.PODZOL)));
	public static final RegistryObject<Block> MYCELIUM_VERTICAL = registerBlock("vertical_mycelium_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.MYCELIUM, ESPSlabs.MYCELIUM_SLAB.get(), Block.Properties.copy(Blocks.MYCELIUM)));
	public static final RegistryObject<Block> DIRT_PATH_VERTICAL = registerBlock("vertical_dirt_path_slab", () -> new PathVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.DIRT_PATH, ESPSlabs.DIRT_PATH_SLAB.get(), Block.Properties.copy(Blocks.DIRT_PATH)));
	public static final RegistryObject<Block> SAND_VERTICAL = registerBlock("vertical_sand_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.SAND, ESPSlabs.SAND_SLAB.get(), Block.Properties.copy(Blocks.SAND)));
	public static final RegistryObject<Block> RED_SAND_VERTICAL = registerBlock("vertical_red_sand_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.RED_SAND, ESPSlabs.RED_SAND_SLAB.get(), Block.Properties.copy(Blocks.RED_SAND)));
	public static final RegistryObject<Block> GRAVEL_VERTICAL = registerBlock("vertical_gravel_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GRAVEL, ESPSlabs.GRAVEL_SLAB.get(), Block.Properties.copy(Blocks.GRAVEL)));

	// STONE
	public static final RegistryObject<Block> COBBLESTONE_VERTICAL = registerBlock("vertical_cobblestone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.COBBLESTONE, Blocks.COBBLESTONE_SLAB, Block.Properties.copy(Blocks.COBBLESTONE)));
	public static final RegistryObject<Block> STONE_VERTICAL = registerBlock("vertical_stone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.STONE, Blocks.STONE_SLAB, Block.Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> STONE_BRICK_VERTICAL = registerBlock("vertical_stone_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.STONE_BRICKS, Blocks.STONE_BRICK_SLAB, Block.Properties.copy(Blocks.STONE_BRICKS)));
	public static final RegistryObject<Block> SMOOTH_STONE_VERTICAL = registerBlock("vertical_smooth_stone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_STONE, Blocks.SMOOTH_STONE_SLAB, Block.Properties.copy(Blocks.SMOOTH_STONE)));
	public static final RegistryObject<Block> MOSSY_COBBLESTONE_VERTICAL = registerBlock("vertical_mossy_cobblestone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MOSSY_COBBLESTONE, Blocks.MOSSY_COBBLESTONE_SLAB, Block.Properties.copy(Blocks.MOSSY_COBBLESTONE)));
	public static final RegistryObject<Block> MOSSY_STONE_BRICK_VERTICAL = registerBlock("vertical_mossy_stone_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MOSSY_STONE_BRICKS, Blocks.MOSSY_STONE_BRICK_SLAB, Block.Properties.copy(Blocks.MOSSY_STONE_BRICKS)));
	public static final RegistryObject<Block> ANDESITE_VERTICAL = registerBlock("vertical_andesite_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ANDESITE, Blocks.ANDESITE_SLAB, Block.Properties.copy(Blocks.ANDESITE)));
	public static final RegistryObject<Block> POLISHED_ANDESITE_VERTICAL = registerBlock("vertical_polished_andesite_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_ANDESITE, Blocks.POLISHED_ANDESITE_SLAB, Block.Properties.copy(Blocks.POLISHED_ANDESITE)));
	public static final RegistryObject<Block> DIORITE_VERTICAL = registerBlock("vertical_diorite_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DIORITE, Blocks.DIORITE_SLAB, Block.Properties.copy(Blocks.DIORITE)));
	public static final RegistryObject<Block> POLISHED_DIORITE_VERTICAL = registerBlock("vertical_polished_diorite_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_DIORITE, Blocks.POLISHED_DIORITE_SLAB, Block.Properties.copy(Blocks.POLISHED_DIORITE)));
	public static final RegistryObject<Block> GRANITE_VERTICAL = registerBlock("vertical_granite_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRANITE, Blocks.GRANITE_SLAB, Block.Properties.copy(Blocks.GRANITE)));
	public static final RegistryObject<Block> POLISHED_GRANITE_VERTICAL = registerBlock("vertical_polished_granite_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_GRANITE, Blocks.POLISHED_GRANITE_SLAB, Block.Properties.copy(Blocks.POLISHED_GRANITE)));
	public static final RegistryObject<Block> BRICK_VERTICAL = registerBlock("vertical_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BRICKS, Blocks.BRICK_SLAB, Block.Properties.copy(Blocks.BRICKS)));
	public static final RegistryObject<Block> TUFF_VERTICAL = registerBlock("vertical_tuff_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.TUFF, ESPSlabs.TUFF_SLAB.get(), Block.Properties.copy(Blocks.TUFF)));
	public static final RegistryObject<Block> CALCITE_VERTICAL = registerBlock("vertical_calcite_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CALCITE, ESPSlabs.CALCITE_SLAB.get(), Block.Properties.copy(Blocks.CALCITE)));
	public static final RegistryObject<Block> DRIPSTONE_VERTICAL = registerBlock("vertical_dripstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DRIPSTONE_BLOCK, ESPSlabs.DRIPSTONE_SLAB.get(), Block.Properties.copy(Blocks.DRIPSTONE_BLOCK)));
	public static final RegistryObject<Block> MUD_VERTICAL = registerBlock("vertical_mud_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.MUD, ESPSlabs.MUD_SLAB.get(), Block.Properties.copy(Blocks.MUD)));
	public static final RegistryObject<Block> PACKED_MUD_VERTICAL = registerBlock("vertical_packed_mud_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PACKED_MUD, ESPSlabs.PACKED_MUD_SLAB.get(), Block.Properties.copy(Blocks.PACKED_MUD)));
	public static final RegistryObject<Block> MUD_BRICK_VERTICAL = registerBlock("vertical_mud_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MUD_BRICKS, Blocks.MUD_BRICK_SLAB, Block.Properties.copy(Blocks.MUD_BRICKS)));

	// WOOL
	public static final RegistryObject<Block> WHITE_WOOL_VERTICAL = registerBlock("vertical_white_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.WHITE_WOOL, ESPSlabs.WHITE_WOOL_SLAB.get(), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> ORANGE_WOOL_VERTICAL = registerBlock("vertical_orange_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.ORANGE_WOOL, ESPSlabs.ORANGE_WOOL_SLAB.get(), Block.Properties.copy(Blocks.ORANGE_WOOL)));
	public static final RegistryObject<Block> MAGENTA_WOOL_VERTICAL = registerBlock("vertical_magenta_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.MAGENTA_WOOL, ESPSlabs.MAGENTA_WOOL_SLAB.get(), Block.Properties.copy(Blocks.MAGENTA_WOOL)));
	public static final RegistryObject<Block> LIGHT_BLUE_WOOL_VERTICAL = registerBlock("vertical_light_blue_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.LIGHT_BLUE_WOOL, ESPSlabs.LIGHT_BLUE_WOOL_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_WOOL)));
	public static final RegistryObject<Block> YELLOW_WOOL_VERTICAL = registerBlock("vertical_yellow_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.YELLOW_WOOL, ESPSlabs.YELLOW_WOOL_SLAB.get(), Block.Properties.copy(Blocks.YELLOW_WOOL)));
	public static final RegistryObject<Block> LIME_WOOL_VERTICAL = registerBlock("vertical_lime_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.LIME_WOOL, ESPSlabs.LIME_WOOL_SLAB.get(), Block.Properties.copy(Blocks.LIME_WOOL)));
	public static final RegistryObject<Block> PINK_WOOL_VERTICAL = registerBlock("vertical_pink_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.PINK_WOOL, ESPSlabs.PINK_WOOL_SLAB.get(), Block.Properties.copy(Blocks.PINK_WOOL)));
	public static final RegistryObject<Block> GRAY_WOOL_VERTICAL = registerBlock("vertical_gray_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.GRAY_WOOL, ESPSlabs.GRAY_WOOL_SLAB.get(), Block.Properties.copy(Blocks.GRAY_WOOL)));
	public static final RegistryObject<Block> LIGHT_GRAY_WOOL_VERTICAL = registerBlock("vertical_light_gray_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.LIGHT_GRAY_WOOL, ESPSlabs.LIGHT_GRAY_WOOL_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_WOOL)));
	public static final RegistryObject<Block> CYAN_WOOL_VERTICAL = registerBlock("vertical_cyan_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.CYAN_WOOL, ESPSlabs.CYAN_WOOL_SLAB.get(), Block.Properties.copy(Blocks.CYAN_WOOL)));
	public static final RegistryObject<Block> PURPLE_WOOL_VERTICAL = registerBlock("vertical_purple_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.PURPLE_WOOL, ESPSlabs.PURPLE_WOOL_SLAB.get(), Block.Properties.copy(Blocks.PURPLE_WOOL)));
	public static final RegistryObject<Block> BLUE_WOOL_VERTICAL = registerBlock("vertical_blue_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.BLUE_WOOL, ESPSlabs.BLUE_WOOL_SLAB.get(), Block.Properties.copy(Blocks.BLUE_WOOL)));
	public static final RegistryObject<Block> BROWN_WOOL_VERTICAL = registerBlock("vertical_brown_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.BROWN_WOOL, ESPSlabs.BROWN_WOOL_SLAB.get(), Block.Properties.copy(Blocks.BROWN_WOOL)));
	public static final RegistryObject<Block> GREEN_WOOL_VERTICAL = registerBlock("vertical_green_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.GREEN_WOOL, ESPSlabs.GREEN_WOOL_SLAB.get(), Block.Properties.copy(Blocks.GREEN_WOOL)));
	public static final RegistryObject<Block> RED_WOOL_VERTICAL = registerBlock("vertical_red_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.RED_WOOL, ESPSlabs.RED_WOOL_SLAB.get(), Block.Properties.copy(Blocks.RED_WOOL)));
	public static final RegistryObject<Block> BLACK_WOOL_VERTICAL = registerBlock("vertical_black_wool_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.WOOL), Blocks.BLACK_WOOL, ESPSlabs.BLACK_WOOL_SLAB.get(), Block.Properties.copy(Blocks.BLACK_WOOL)));

	// CONCRETE_POWDER
	public static final RegistryObject<Block> WHITE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_white_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.WHITE_CONCRETE_POWDER, ESPSlabs.WHITE_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.WHITE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> ORANGE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_orange_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.ORANGE_CONCRETE_POWDER, ESPSlabs.ORANGE_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.ORANGE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> MAGENTA_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_magenta_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.MAGENTA_CONCRETE_POWDER, ESPSlabs.MAGENTA_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.MAGENTA_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_light_blue_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIGHT_BLUE_CONCRETE_POWDER, ESPSlabs.LIGHT_BLUE_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> YELLOW_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_yellow_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.YELLOW_CONCRETE_POWDER, ESPSlabs.YELLOW_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.YELLOW_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIME_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_lime_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIME_CONCRETE_POWDER, ESPSlabs.LIME_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.LIME_CONCRETE_POWDER)));
	public static final RegistryObject<Block> PINK_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_pink_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.PINK_CONCRETE_POWDER, ESPSlabs.PINK_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.PINK_CONCRETE_POWDER)));
	public static final RegistryObject<Block> GRAY_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_gray_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GRAY_CONCRETE_POWDER, ESPSlabs.GRAY_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.GRAY_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_light_gray_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIGHT_GRAY_CONCRETE_POWDER, ESPSlabs.LIGHT_GRAY_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE_POWDER)));
	public static final RegistryObject<Block> CYAN_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_cyan_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.CYAN_CONCRETE_POWDER, ESPSlabs.CYAN_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.CYAN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> PURPLE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_purple_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.PURPLE_CONCRETE_POWDER, ESPSlabs.PURPLE_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.PURPLE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BLUE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_blue_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BLUE_CONCRETE_POWDER, ESPSlabs.BLUE_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.BLUE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BROWN_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_brown_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BROWN_CONCRETE_POWDER, ESPSlabs.BROWN_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.BROWN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> GREEN_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_green_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GREEN_CONCRETE_POWDER, ESPSlabs.GREEN_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.GREEN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> RED_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_red_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.RED_CONCRETE_POWDER, ESPSlabs.RED_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.RED_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BLACK_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_black_concrete_powder_slab", () -> new FallingVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BLACK_CONCRETE_POWDER, ESPSlabs.BLACK_CONCRETE_POWDER_SLAB.get(), Block.Properties.copy(Blocks.BLACK_CONCRETE_POWDER)));

	// CONCRETE
	public static final RegistryObject<Block> WHITE_CONCRETE_VERTICAL = registerBlock("vertical_white_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_CONCRETE, ESPSlabs.WHITE_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.WHITE_CONCRETE)));
	public static final RegistryObject<Block> ORANGE_CONCRETE_VERTICAL = registerBlock("vertical_orange_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_CONCRETE, ESPSlabs.ORANGE_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.ORANGE_CONCRETE)));
	public static final RegistryObject<Block> MAGENTA_CONCRETE_VERTICAL = registerBlock("vertical_magenta_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_CONCRETE, ESPSlabs.MAGENTA_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.MAGENTA_CONCRETE)));
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_VERTICAL = registerBlock("vertical_light_blue_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_CONCRETE, ESPSlabs.LIGHT_BLUE_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE)));
	public static final RegistryObject<Block> YELLOW_CONCRETE_VERTICAL = registerBlock("vertical_yellow_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_CONCRETE, ESPSlabs.YELLOW_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.YELLOW_CONCRETE)));
	public static final RegistryObject<Block> LIME_CONCRETE_VERTICAL = registerBlock("vertical_lime_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_CONCRETE, ESPSlabs.LIME_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.LIME_CONCRETE)));
	public static final RegistryObject<Block> PINK_CONCRETE_VERTICAL = registerBlock("vertical_pink_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_CONCRETE, ESPSlabs.PINK_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.PINK_CONCRETE)));
	public static final RegistryObject<Block> GRAY_CONCRETE_VERTICAL = registerBlock("vertical_gray_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_CONCRETE, ESPSlabs.GRAY_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.GRAY_CONCRETE)));
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_VERTICAL = registerBlock("vertical_light_gray_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_CONCRETE, ESPSlabs.LIGHT_GRAY_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE)));
	public static final RegistryObject<Block> CYAN_CONCRETE_VERTICAL = registerBlock("vertical_cyan_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_CONCRETE, ESPSlabs.CYAN_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.CYAN_CONCRETE)));
	public static final RegistryObject<Block> PURPLE_CONCRETE_VERTICAL = registerBlock("vertical_purple_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_CONCRETE, ESPSlabs.PURPLE_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.PURPLE_CONCRETE)));
	public static final RegistryObject<Block> BLUE_CONCRETE_VERTICAL = registerBlock("vertical_blue_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_CONCRETE, ESPSlabs.BLUE_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.BLUE_CONCRETE)));
	public static final RegistryObject<Block> BROWN_CONCRETE_VERTICAL = registerBlock("vertical_brown_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_CONCRETE, ESPSlabs.BROWN_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.BROWN_CONCRETE)));
	public static final RegistryObject<Block> GREEN_CONCRETE_VERTICAL = registerBlock("vertical_green_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_CONCRETE, ESPSlabs.GREEN_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.GREEN_CONCRETE)));
	public static final RegistryObject<Block> RED_CONCRETE_VERTICAL = registerBlock("vertical_red_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_CONCRETE, ESPSlabs.RED_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.RED_CONCRETE)));
	public static final RegistryObject<Block> BLACK_CONCRETE_VERTICAL = registerBlock("vertical_black_concrete_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_CONCRETE, ESPSlabs.BLACK_CONCRETE_SLAB.get(), Block.Properties.copy(Blocks.BLACK_CONCRETE)));

	// TERRACOTTA
	public static final RegistryObject<Block> CLAY_VERTICAL = registerBlock("vertical_clay_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.CLAY, ESPSlabs.CLAY_SLAB.get(), Block.Properties.copy(Blocks.CLAY)));
	public static final RegistryObject<Block> TERRACOTTA_VERTICAL = registerBlock("vertical_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.TERRACOTTA, ESPSlabs.TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.TERRACOTTA)));
	public static final RegistryObject<Block> WHITE_TERRACOTTA_VERTICAL = registerBlock("vertical_white_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_TERRACOTTA, ESPSlabs.WHITE_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.WHITE_TERRACOTTA)));
	public static final RegistryObject<Block> ORANGE_TERRACOTTA_VERTICAL = registerBlock("vertical_orange_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_TERRACOTTA, ESPSlabs.ORANGE_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.ORANGE_TERRACOTTA)));
	public static final RegistryObject<Block> MAGENTA_TERRACOTTA_VERTICAL = registerBlock("vertical_magenta_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_TERRACOTTA, ESPSlabs.MAGENTA_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.MAGENTA_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_BLUE_TERRACOTTA_VERTICAL = registerBlock("vertical_light_blue_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_TERRACOTTA, ESPSlabs.LIGHT_BLUE_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_TERRACOTTA)));
	public static final RegistryObject<Block> YELLOW_TERRACOTTA_VERTICAL = registerBlock("vertical_yellow_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_TERRACOTTA, ESPSlabs.YELLOW_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.YELLOW_TERRACOTTA)));
	public static final RegistryObject<Block> LIME_TERRACOTTA_VERTICAL = registerBlock("vertical_lime_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_TERRACOTTA, ESPSlabs.LIME_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.LIME_TERRACOTTA)));
	public static final RegistryObject<Block> PINK_TERRACOTTA_VERTICAL = registerBlock("vertical_pink_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_TERRACOTTA, ESPSlabs.PINK_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.PINK_TERRACOTTA)));
	public static final RegistryObject<Block> GRAY_TERRACOTTA_VERTICAL = registerBlock("vertical_gray_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_TERRACOTTA, ESPSlabs.GRAY_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.GRAY_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_GRAY_TERRACOTTA_VERTICAL = registerBlock("vertical_light_gray_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_TERRACOTTA, ESPSlabs.LIGHT_GRAY_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_TERRACOTTA)));
	public static final RegistryObject<Block> CYAN_TERRACOTTA_VERTICAL = registerBlock("vertical_cyan_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_TERRACOTTA, ESPSlabs.CYAN_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.CYAN_TERRACOTTA)));
	public static final RegistryObject<Block> PURPLE_TERRACOTTA_VERTICAL = registerBlock("vertical_purple_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_TERRACOTTA, ESPSlabs.PURPLE_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.PURPLE_TERRACOTTA)));
	public static final RegistryObject<Block> BLUE_TERRACOTTA_VERTICAL = registerBlock("vertical_blue_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_TERRACOTTA, ESPSlabs.BLUE_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.BLUE_TERRACOTTA)));
	public static final RegistryObject<Block> BROWN_TERRACOTTA_VERTICAL = registerBlock("vertical_brown_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_TERRACOTTA, ESPSlabs.BROWN_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.BROWN_TERRACOTTA)));
	public static final RegistryObject<Block> GREEN_TERRACOTTA_VERTICAL = registerBlock("vertical_green_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_TERRACOTTA, ESPSlabs.GREEN_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.GREEN_TERRACOTTA)));
	public static final RegistryObject<Block> RED_TERRACOTTA_VERTICAL = registerBlock("vertical_red_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_TERRACOTTA, ESPSlabs.RED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.RED_TERRACOTTA)));
	public static final RegistryObject<Block> BLACK_TERRACOTTA_VERTICAL = registerBlock("vertical_black_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_TERRACOTTA, ESPSlabs.BLACK_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.BLACK_TERRACOTTA)));

	// GLAZED TERRACOTTA
	public static final RegistryObject<Block> WHITE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_white_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_GLAZED_TERRACOTTA, ESPSlabs.WHITE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.WHITE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> ORANGE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_orange_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_GLAZED_TERRACOTTA, ESPSlabs.ORANGE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.ORANGE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> MAGENTA_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_magenta_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_GLAZED_TERRACOTTA, ESPSlabs.MAGENTA_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.MAGENTA_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_light_blue_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, ESPSlabs.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> YELLOW_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_yellow_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_GLAZED_TERRACOTTA, ESPSlabs.YELLOW_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.YELLOW_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIME_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_lime_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_GLAZED_TERRACOTTA, ESPSlabs.LIME_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.LIME_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> PINK_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_pink_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_GLAZED_TERRACOTTA, ESPSlabs.PINK_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.PINK_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> GRAY_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_gray_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_GLAZED_TERRACOTTA, ESPSlabs.GRAY_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.GRAY_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_light_gray_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, ESPSlabs.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> CYAN_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_cyan_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_GLAZED_TERRACOTTA, ESPSlabs.CYAN_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.CYAN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> PURPLE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_purple_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_GLAZED_TERRACOTTA, ESPSlabs.PURPLE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.PURPLE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BLUE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_blue_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_GLAZED_TERRACOTTA, ESPSlabs.BLUE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.BLUE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BROWN_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_brown_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_GLAZED_TERRACOTTA, ESPSlabs.BROWN_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.BROWN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> GREEN_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_green_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_GLAZED_TERRACOTTA, ESPSlabs.GREEN_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.GREEN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> RED_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_red_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_GLAZED_TERRACOTTA, ESPSlabs.RED_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.RED_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BLACK_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_black_glazed_terracotta_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_GLAZED_TERRACOTTA, ESPSlabs.BLACK_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.copy(Blocks.BLACK_GLAZED_TERRACOTTA)));

	// GLASS
	public static final RegistryObject<Block> GLASS_VERTICAL = registerBlock("vertical_glass_slab", () -> new GlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.GLASS, ESPSlabs.GLASS_SLAB.get(), Block.Properties.copy(Blocks.GLASS)));
	public static final RegistryObject<Block> TINTED_GLASS_VERTICAL = registerBlock("vertical_tinted_glass_slab", () -> new TintedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.TINTED_GLASS, ESPSlabs.TINTED_GLASS_SLAB.get(), Block.Properties.copy(Blocks.TINTED_GLASS)));
	public static final RegistryObject<Block> WHITE_STAINED_GLASS_VERTICAL = registerBlock("vertical_white_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.WHITE_STAINED_GLASS, ESPSlabs.WHITE_STAINED_GLASS_SLAB.get(), DyeColor.WHITE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> ORANGE_STAINED_GLASS_VERTICAL = registerBlock("vertical_orange_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.ORANGE_STAINED_GLASS, ESPSlabs.ORANGE_STAINED_GLASS_SLAB.get(), DyeColor.ORANGE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> MAGENTA_STAINED_GLASS_VERTICAL = registerBlock("vertical_magenta_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.MAGENTA_STAINED_GLASS, ESPSlabs.MAGENTA_STAINED_GLASS_SLAB.get(), DyeColor.MAGENTA, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIGHT_BLUE_STAINED_GLASS_VERTICAL = registerBlock("vertical_light_blue_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIGHT_BLUE_STAINED_GLASS, ESPSlabs.LIGHT_BLUE_STAINED_GLASS_SLAB.get(), DyeColor.LIGHT_BLUE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> YELLOW_STAINED_GLASS_VERTICAL = registerBlock("vertical_yellow_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.YELLOW_STAINED_GLASS, ESPSlabs.YELLOW_STAINED_GLASS_SLAB.get(), DyeColor.YELLOW, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIME_STAINED_GLASS_VERTICAL = registerBlock("vertical_lime_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIME_STAINED_GLASS, ESPSlabs.LIME_STAINED_GLASS_SLAB.get(), DyeColor.LIME, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> PINK_STAINED_GLASS_VERTICAL = registerBlock("vertical_pink_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.PINK_STAINED_GLASS, ESPSlabs.PINK_STAINED_GLASS_SLAB.get(), DyeColor.PINK, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> GRAY_STAINED_GLASS_VERTICAL = registerBlock("vertical_gray_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.GRAY_STAINED_GLASS, ESPSlabs.GRAY_STAINED_GLASS_SLAB.get(), DyeColor.GRAY, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIGHT_GRAY_STAINED_GLASS_VERTICAL = registerBlock("vertical_light_gray_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIGHT_GRAY_STAINED_GLASS, ESPSlabs.LIGHT_GRAY_STAINED_GLASS_SLAB.get(), DyeColor.LIGHT_GRAY, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> CYAN_STAINED_GLASS_VERTICAL = registerBlock("vertical_cyan_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.CYAN_STAINED_GLASS, ESPSlabs.CYAN_STAINED_GLASS_SLAB.get(), DyeColor.CYAN, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> PURPLE_STAINED_GLASS_VERTICAL = registerBlock("vertical_purple_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.PURPLE_STAINED_GLASS, ESPSlabs.PURPLE_STAINED_GLASS_SLAB.get(), DyeColor.PURPLE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BLUE_STAINED_GLASS_VERTICAL = registerBlock("vertical_blue_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.BLUE_STAINED_GLASS, ESPSlabs.BLUE_STAINED_GLASS_SLAB.get(), DyeColor.BLUE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BROWN_STAINED_GLASS_VERTICAL = registerBlock("vertical_brown_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.BROWN_STAINED_GLASS, ESPSlabs.BROWN_STAINED_GLASS_SLAB.get(), DyeColor.BROWN, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> GREEN_STAINED_GLASS_VERTICAL = registerBlock("vertical_green_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.GREEN_STAINED_GLASS, ESPSlabs.GREEN_STAINED_GLASS_SLAB.get(), DyeColor.GREEN, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> RED_STAINED_GLASS_VERTICAL = registerBlock("vertical_red_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.RED_STAINED_GLASS, ESPSlabs.RED_STAINED_GLASS_SLAB.get(), DyeColor.RED, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BLACK_STAINED_GLASS_VERTICAL = registerBlock("vertical_black_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(tag(BlockTags.IMPERMEABLE), Blocks.BLACK_STAINED_GLASS, ESPSlabs.BLACK_STAINED_GLASS_SLAB.get(), DyeColor.BLACK, Block.Properties.copy(Blocks.WHITE_WOOL)));

	// SANDSTONE
	public static final RegistryObject<Block> SANDSTONE_VERTICAL = registerBlock("vertical_sandstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SANDSTONE, Blocks.SANDSTONE_SLAB, Block.Properties.copy(Blocks.SANDSTONE)));
	public static final RegistryObject<Block> SMOOTH_SANDSTONE_VERTICAL = registerBlock("vertical_smooth_sandstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_SANDSTONE, Blocks.SMOOTH_SANDSTONE_SLAB, Block.Properties.copy(Blocks.SMOOTH_SANDSTONE)));
	public static final RegistryObject<Block> CUT_SANDSTONE_VERTICAL = registerBlock("vertical_cut_sandstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CUT_SANDSTONE, Blocks.CUT_SANDSTONE_SLAB, Block.Properties.copy(Blocks.CUT_SANDSTONE)));
	public static final RegistryObject<Block> RED_SANDSTONE_VERTICAL = registerBlock("vertical_red_sandstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_SANDSTONE, Blocks.RED_SANDSTONE_SLAB, Block.Properties.copy(Blocks.RED_SANDSTONE)));
	public static final RegistryObject<Block> SMOOTH_RED_SANDSTONE_VERTICAL = registerBlock("vertical_smooth_red_sandstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_RED_SANDSTONE, Blocks.SMOOTH_RED_SANDSTONE_SLAB, Block.Properties.copy(Blocks.SMOOTH_RED_SANDSTONE)));
	public static final RegistryObject<Block> CUT_RED_SANDSTONE_VERTICAL = registerBlock("vertical_cut_red_sandstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CUT_RED_SANDSTONE, Blocks.CUT_RED_SANDSTONE_SLAB, Block.Properties.copy(Blocks.CUT_RED_SANDSTONE)));

	// DEEPSLATE
	public static final RegistryObject<Block> COBBLED_DEEPSLATE_VERTICAL = registerBlock("vertical_cobbled_deepslate_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.COBBLED_DEEPSLATE, Blocks.COBBLED_DEEPSLATE_SLAB, Block.Properties.copy(Blocks.COBBLED_DEEPSLATE)));
	public static final RegistryObject<Block> POLISHED_DEEPSLATE_VERTICAL = registerBlock("vertical_polished_deepslate_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_DEEPSLATE, Blocks.POLISHED_DEEPSLATE_SLAB, Block.Properties.copy(Blocks.POLISHED_DEEPSLATE)));
	public static final RegistryObject<Block> DEEPSLATE_BRICK_VERTICAL = registerBlock("vertical_deepslate_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DEEPSLATE_BRICKS, Blocks.DEEPSLATE_BRICK_SLAB, Block.Properties.copy(Blocks.DEEPSLATE_BRICKS)));
	public static final RegistryObject<Block> DEEPSLATE_TILE_VERTICAL = registerBlock("vertical_deepslate_tile_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DEEPSLATE_TILES, Blocks.DEEPSLATE_TILE_SLAB, Block.Properties.copy(Blocks.DEEPSLATE_TILES)));

	// NETHER
	public static final RegistryObject<Block> BLACKSTONE_VERTICAL = registerBlock("vertical_blackstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACKSTONE, Blocks.BLACKSTONE_SLAB, Block.Properties.copy(Blocks.BLACKSTONE)));
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_VERTICAL = registerBlock("vertical_polished_blackstone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_BLACKSTONE, Blocks.POLISHED_BLACKSTONE_SLAB, Block.Properties.copy(Blocks.POLISHED_BLACKSTONE)));
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_BRICK_VERTICAL = registerBlock("vertical_polished_blackstone_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_BLACKSTONE_BRICKS, Blocks.POLISHED_BLACKSTONE_BRICK_SLAB, Block.Properties.copy(Blocks.POLISHED_BLACKSTONE_BRICKS)));
	public static final RegistryObject<Block> NETHERRACK_VERTICAL = registerBlock("vertical_netherrack_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.NETHERRACK, ESPSlabs.NETHERRACK_SLAB.get(), Block.Properties.copy(Blocks.NETHERRACK)));
	public static final RegistryObject<Block> CRIMSON_NYLIUM_VERTICAL = registerBlock("vertical_crimson_nylium_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CRIMSON_NYLIUM, ESPSlabs.CRIMSON_NYLIUM_SLAB.get(), Block.Properties.copy(Blocks.CRIMSON_NYLIUM)));
	public static final RegistryObject<Block> WARPED_NYLIUM_VERTICAL = registerBlock("vertical_warped_nylium_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WARPED_NYLIUM, ESPSlabs.WARPED_NYLIUM_SLAB.get(), Block.Properties.copy(Blocks.WARPED_NYLIUM)));
	public static final RegistryObject<Block> NETHER_BRICK_VERTICAL = registerBlock("vertical_nether_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.NETHER_BRICKS, Blocks.NETHER_BRICK_SLAB, Block.Properties.copy(Blocks.NETHER_BRICKS)));
	public static final RegistryObject<Block> RED_NETHER_BRICK_VERTICAL = registerBlock("vertical_red_nether_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_NETHER_BRICKS, Blocks.RED_NETHER_BRICK_SLAB, Block.Properties.copy(Blocks.RED_NETHER_BRICKS)));
	public static final RegistryObject<Block> QUARTZ_VERTICAL = registerBlock("vertical_quartz_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.QUARTZ_BLOCK, Blocks.QUARTZ_SLAB, Block.Properties.copy(Blocks.QUARTZ_BLOCK)));
	public static final RegistryObject<Block> SMOOTH_QUARTZ_VERTICAL = registerBlock("vertical_smooth_quartz_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_QUARTZ, Blocks.SMOOTH_QUARTZ_SLAB, Block.Properties.copy(Blocks.SMOOTH_QUARTZ)));

	// END
	public static final RegistryObject<Block> END_STONE_VERTICAL = registerBlock("vertical_end_stone_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.END_STONE, ESPSlabs.END_STONE_SLAB.get(), Block.Properties.copy(Blocks.END_STONE)));
	public static final RegistryObject<Block> END_STONE_BRICK_VERTICAL = registerBlock("vertical_end_stone_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.END_STONE_BRICKS, Blocks.END_STONE_BRICK_SLAB, Block.Properties.copy(Blocks.END_STONE_BRICKS)));
	public static final RegistryObject<Block> PURPUR_VERTICAL = registerBlock("vertical_purpur_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPUR_BLOCK, Blocks.PURPUR_SLAB, Block.Properties.copy(Blocks.PURPUR_BLOCK)));

	// PRISMARINE
	public static final RegistryObject<Block> PRISMARINE_VERTICAL = registerBlock("vertical_prismarine_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PRISMARINE, Blocks.PRISMARINE_SLAB, Block.Properties.copy(Blocks.PRISMARINE)));
	public static final RegistryObject<Block> PRISMARINE_BRICK_VERTICAL = registerBlock("vertical_prismarine_brick_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PRISMARINE_BRICKS, Blocks.PRISMARINE_BRICK_SLAB, Block.Properties.copy(Blocks.PRISMARINE_BRICKS)));
	public static final RegistryObject<Block> DARK_PRISMARINE_VERTICAL = registerBlock("vertical_dark_prismarine_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DARK_PRISMARINE, Blocks.DARK_PRISMARINE_SLAB, Block.Properties.copy(Blocks.DARK_PRISMARINE)));

	// PLANKS
	public static final RegistryObject<Block> OAK_VERTICAL = registerBlock("vertical_oak_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Block.Properties.copy(Blocks.OAK_PLANKS)));
	public static final RegistryObject<Block> SPRUCE_VERTICAL = registerBlock("vertical_spruce_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Block.Properties.copy(Blocks.SPRUCE_PLANKS)));
	public static final RegistryObject<Block> BIRCH_VERTICAL = registerBlock("vertical_birch_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Block.Properties.copy(Blocks.BIRCH_PLANKS)));
	public static final RegistryObject<Block> JUNGLE_VERTICAL = registerBlock("vertical_jungle_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Block.Properties.copy(Blocks.JUNGLE_PLANKS)));
	public static final RegistryObject<Block> ACACIA_VERTICAL = registerBlock("vertical_acacia_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Block.Properties.copy(Blocks.ACACIA_PLANKS)));
	public static final RegistryObject<Block> DARK_OAK_VERTICAL = registerBlock("vertical_dark_oak_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Block.Properties.copy(Blocks.DARK_OAK_PLANKS)));
	public static final RegistryObject<Block> MANGROVE_VERTICAL = registerBlock("vertical_mangrove_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Block.Properties.copy(Blocks.MANGROVE_PLANKS)));
	public static final RegistryObject<Block> CHERRY_VERTICAL = registerBlock("vertical_cherry_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CHERRY_PLANKS, Blocks.CHERRY_SLAB, Block.Properties.copy(Blocks.CHERRY_PLANKS)));
	public static final RegistryObject<Block> BAMBOO_VERTICAL = registerBlock("vertical_bamboo_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_SLAB, Block.Properties.copy(Blocks.BAMBOO_PLANKS)));
	public static final RegistryObject<Block> BAMBOO_MOSAIC_VERTICAL = registerBlock("vertical_bamboo_mosaic_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_MOSAIC_SLAB, Block.Properties.copy(Blocks.BAMBOO_MOSAIC)));
	public static final RegistryObject<Block> CRIMSON_VERTICAL = registerBlock("vertical_crimson_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Block.Properties.copy(Blocks.CRIMSON_PLANKS)));
	public static final RegistryObject<Block> WARPED_VERTICAL = registerBlock("vertical_warped_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Block.Properties.copy(Blocks.WARPED_PLANKS)));

	// WOOD
	public static final RegistryObject<Block> OAK_WOOD_VERTICAL = registerBlock("vertical_oak_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.OAK_WOOD, ESPSlabs.OAK_WOOD_SLAB.get(), Block.Properties.copy(Blocks.OAK_WOOD)));
	public static final RegistryObject<Block> SPRUCE_WOOD_VERTICAL = registerBlock("vertical_spruce_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.SPRUCE_WOOD, ESPSlabs.SPRUCE_WOOD_SLAB.get(), Block.Properties.copy(Blocks.SPRUCE_WOOD)));
	public static final RegistryObject<Block> BIRCH_WOOD_VERTICAL = registerBlock("vertical_birch_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BIRCH_WOOD, ESPSlabs.BIRCH_WOOD_SLAB.get(), Block.Properties.copy(Blocks.BIRCH_WOOD)));
	public static final RegistryObject<Block> JUNGLE_WOOD_VERTICAL = registerBlock("vertical_jungle_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.JUNGLE_WOOD, ESPSlabs.JUNGLE_WOOD_SLAB.get(), Block.Properties.copy(Blocks.JUNGLE_WOOD)));
	public static final RegistryObject<Block> ACACIA_WOOD_VERTICAL = registerBlock("vertical_acacia_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.ACACIA_WOOD, ESPSlabs.ACACIA_WOOD_SLAB.get(), Block.Properties.copy(Blocks.ACACIA_WOOD)));
	public static final RegistryObject<Block> DARK_OAK_WOOD_VERTICAL = registerBlock("vertical_dark_oak_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.DARK_OAK_WOOD, ESPSlabs.DARK_OAK_WOOD_SLAB.get(), Block.Properties.copy(Blocks.DARK_OAK_WOOD)));
	public static final RegistryObject<Block> MANGROVE_WOOD_VERTICAL = registerBlock("vertical_mangrove_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.MANGROVE_WOOD, ESPSlabs.MANGROVE_WOOD_SLAB.get(), Block.Properties.copy(Blocks.MANGROVE_WOOD)));
	public static final RegistryObject<Block> CHERRY_WOOD_VERTICAL = registerBlock("vertical_cherry_wood_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CHERRY_WOOD, ESPSlabs.CHERRY_WOOD_SLAB.get(), Block.Properties.copy(Blocks.CHERRY_WOOD)));
	public static final RegistryObject<Block> CRIMSON_HYPHAE_VERTICAL = registerBlock("vertical_crimson_hyphae_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CRIMSON_HYPHAE, ESPSlabs.CRIMSON_HYPHAE_SLAB.get(), Block.Properties.copy(Blocks.CRIMSON_HYPHAE)));
	public static final RegistryObject<Block> WARPED_HYPHAE_VERTICAL = registerBlock("vertical_warped_hyphae_slab", () -> new ESPVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.WARPED_HYPHAE, ESPSlabs.WARPED_HYPHAE_SLAB.get(), Block.Properties.copy(Blocks.WARPED_HYPHAE)));

	// COPPER
	public static final RegistryObject<Block> OXIDIZED_CUT_COPPER_VERTICAL = registerBlock("vertical_oxidized_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.OXIDIZED_CUT_COPPER, Blocks.OXIDIZED_CUT_COPPER_SLAB, Block.Properties.copy(Blocks.OXIDIZED_CUT_COPPER), WeatheringCopper.WeatherState.OXIDIZED));
	public static final RegistryObject<Block> WEATHERED_CUT_COPPER_VERTICAL = registerBlock("vertical_weathered_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WEATHERED_CUT_COPPER, Blocks.WEATHERED_CUT_COPPER_SLAB, Block.Properties.copy(Blocks.WEATHERED_CUT_COPPER), WeatheringCopper.WeatherState.WEATHERED));
	public static final RegistryObject<Block> EXPOSED_CUT_COPPER_VERTICAL = registerBlock("vertical_exposed_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.EXPOSED_CUT_COPPER, Blocks.EXPOSED_CUT_COPPER_SLAB, Block.Properties.copy(Blocks.EXPOSED_CUT_COPPER), WeatheringCopper.WeatherState.EXPOSED));
	public static final RegistryObject<Block> CUT_COPPER_VERTICAL = registerBlock("vertical_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.CUT_COPPER, Blocks.CUT_COPPER_SLAB, Block.Properties.copy(Blocks.CUT_COPPER), WeatheringCopper.WeatherState.UNAFFECTED));
	public static final RegistryObject<Block> WAXED_OXIDIZED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_oxidized_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_OXIDIZED_CUT_COPPER, Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB, Block.Properties.copy(Blocks.WAXED_OXIDIZED_CUT_COPPER), WeatheringCopper.WeatherState.OXIDIZED));
	public static final RegistryObject<Block> WAXED_WEATHERED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_weathered_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_WEATHERED_CUT_COPPER, Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB, Block.Properties.copy(Blocks.WAXED_WEATHERED_CUT_COPPER), WeatheringCopper.WeatherState.WEATHERED));
	public static final RegistryObject<Block> WAXED_EXPOSED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_exposed_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_EXPOSED_CUT_COPPER, Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB, Block.Properties.copy(Blocks.WAXED_EXPOSED_CUT_COPPER), WeatheringCopper.WeatherState.EXPOSED));
	public static final RegistryObject<Block> WAXED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_CUT_COPPER, Blocks.WAXED_CUT_COPPER_SLAB, Block.Properties.copy(Blocks.WAXED_CUT_COPPER), WeatheringCopper.WeatherState.UNAFFECTED));

	public static <B extends Block> RegistryObject<B> registerBlock(String name, Supplier<? extends B> supplier) {
		RegistryObject<B> block = BLOCKS.register(name, supplier);
		ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
		return block;
	}

	public static Collection<RegistryObject<Item>> orderedItems() {
		return ITEMS.getEntries();
	}

	private static boolean never(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos) {
		return false;
	}

	private static Boolean never(BlockState p_50779_, BlockGetter p_50780_, BlockPos p_50781_, EntityType<?> p_50782_) {
		return false;
	}
}
