package com.blackout.extendedslabs.init;

import com.blackout.extendedslabs.ExtendedSlabs;
import com.blackout.extendedslabs.blocks.VerticalSlabBlock;
import com.blackout.extendedslabs.blocks.copper.WeatheringCopperVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.falling.FallingVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.glass.GlassVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.glass.StainedGlassVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.glass.TintedGlassVerticalSlabBlock;
import com.blackout.extendedslabs.blocks.path.PathVerticalSlabBlock;
import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.WeatheringCopper;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.MaterialColor;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

@Mod.EventBusSubscriber(modid = ExtendedSlabs.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ESPVerticalSlabs {
	public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, ExtendedSlabs.MODID);
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ExtendedSlabs.MODID);

	// DIRT
	public static final RegistryObject<Block> GRASS_BLOCK_VERTICAL = registerBlock("vertical_grass_block_slab", () -> new VerticalSlabBlock(Blocks.GRASS_BLOCK, ESPSlabs.GRASS_BLOCK_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_GRASS, MaterialColor.GRASS).randomTicks().strength(0.6F).sound(SoundType.GRASS)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DIRT_VERTICAL = registerBlock("vertical_dirt_slab", () -> new VerticalSlabBlock(Blocks.DIRT, ESPSlabs.DIRT_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_DIRT, MaterialColor.DIRT).strength(0.5F).sound(SoundType.GRAVEL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> COARSE_DIRT_VERTICAL = registerBlock("vertical_coarse_dirt_slab", () -> new VerticalSlabBlock(Blocks.COARSE_DIRT, ESPSlabs.COARSE_DIRT_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_DIRT, MaterialColor.DIRT).strength(0.5F).sound(SoundType.GRAVEL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ROOTED_DIRT_VERTICAL = registerBlock("vertical_rooted_dirt_slab", () -> new VerticalSlabBlock(Blocks.ROOTED_DIRT, ESPSlabs.ROOTED_DIRT_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_DIRT, MaterialColor.DIRT).strength(0.5F).sound(SoundType.ROOTED_DIRT)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PODZOL_VERTICAL = registerBlock("vertical_podzol_slab", () -> new VerticalSlabBlock(Blocks.PODZOL, ESPSlabs.PODZOL_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_DIRT, MaterialColor.PODZOL).strength(0.5F).sound(SoundType.GRAVEL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MYCELIUM_VERTICAL = registerBlock("vertical_mycelium_slab", () -> new VerticalSlabBlock(Blocks.MYCELIUM, ESPSlabs.MYCELIUM_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_GRASS, MaterialColor.COLOR_PURPLE).randomTicks().strength(0.6F).sound(SoundType.GRASS)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DIRT_PATH_VERTICAL = registerBlock("vertical_dirt_path_slab", () -> new PathVerticalSlabBlock(Blocks.DIRT_PATH, ESPSlabs.DIRT_PATH_SLAB.get(), BlockBehaviour.Properties.of(ESPMaterial.SHOVEL_DIRT, MaterialColor.DIRT).strength(0.65F).sound(SoundType.GRASS).isViewBlocking(ESPVerticalSlabs::always).isSuffocating(ESPVerticalSlabs::always)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> SAND_VERTICAL = registerBlock("vertical_sand_slab", () -> new FallingVerticalSlabBlock(Blocks.SAND, ESPSlabs.SAND_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, MaterialColor.SAND).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_SAND_VERTICAL = registerBlock("vertical_red_sand_slab", () -> new FallingVerticalSlabBlock(Blocks.RED_SAND, ESPSlabs.RED_SAND_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, MaterialColor.COLOR_ORANGE).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRAVEL_VERTICAL = registerBlock("vertical_gravel_slab", () -> new FallingVerticalSlabBlock(Blocks.GRAVEL, ESPSlabs.GRAVEL_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, MaterialColor.STONE).strength(0.6F).sound(SoundType.GRAVEL)), ExtendedSlabs.GROUP);

	// STONE
	public static final RegistryObject<Block> COBBLESTONE_VERTICAL = registerBlock("vertical_cobblestone_slab", () -> new VerticalSlabBlock(Blocks.COBBLESTONE, Blocks.COBBLESTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> STONE_VERTICAL = registerBlock("vertical_stone_slab", () -> new VerticalSlabBlock(Blocks.STONE, Blocks.STONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> STONE_BRICK_VERTICAL = registerBlock("vertical_stone_brick_slab", () -> new VerticalSlabBlock(Blocks.STONE_BRICKS, Blocks.STONE_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> SMOOTH_STONE_VERTICAL = registerBlock("vertical_smooth_stone_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_STONE, Blocks.SMOOTH_STONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MOSSY_COBBLESTONE_VERTICAL = registerBlock("vertical_mossy_cobblestone_slab", () -> new VerticalSlabBlock(Blocks.MOSSY_COBBLESTONE, Blocks.MOSSY_COBBLESTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MOSSY_STONE_BRICK_VERTICAL = registerBlock("vertical_mossy_stone_brick_slab", () -> new VerticalSlabBlock(Blocks.MOSSY_STONE_BRICKS, Blocks.MOSSY_STONE_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ANDESITE_VERTICAL = registerBlock("vertical_andesite_slab", () -> new VerticalSlabBlock(Blocks.ANDESITE, Blocks.ANDESITE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> POLISHED_ANDESITE_VERTICAL = registerBlock("vertical_polished_andesite_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_ANDESITE, Blocks.POLISHED_ANDESITE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.STONE).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DIORITE_VERTICAL = registerBlock("vertical_diorite_slab", () -> new VerticalSlabBlock(Blocks.DIORITE, Blocks.DIORITE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.QUARTZ).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> POLISHED_DIORITE_VERTICAL = registerBlock("vertical_polished_diorite_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DIORITE, Blocks.POLISHED_DIORITE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.QUARTZ).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRANITE_VERTICAL = registerBlock("vertical_granite_slab", () -> new VerticalSlabBlock(Blocks.GRANITE, Blocks.GRANITE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DIRT).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> POLISHED_GRANITE_VERTICAL = registerBlock("vertical_polished_granite_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_GRANITE, Blocks.POLISHED_GRANITE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DIRT).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BRICK_VERTICAL = registerBlock("vertical_brick_slab", () -> new VerticalSlabBlock(Blocks.BRICKS, Blocks.BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_RED).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> TUFF_VERTICAL = registerBlock("vertical_tuff_slab", () -> new VerticalSlabBlock(Blocks.TUFF, ESPSlabs.TUFF_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_GRAY).sound(SoundType.TUFF).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CALCITE_VERTICAL = registerBlock("vertical_calcite_slab", () -> new VerticalSlabBlock(Blocks.CALCITE, ESPSlabs.CALCITE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_WHITE).sound(SoundType.CALCITE).requiresCorrectToolForDrops().strength(0.75F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DRIPSTONE_VERTICAL = registerBlock("vertical_dripstone_slab", () -> new VerticalSlabBlock(Blocks.DRIPSTONE_BLOCK, ESPSlabs.DRIPSTONE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_BROWN).sound(SoundType.DRIPSTONE_BLOCK).requiresCorrectToolForDrops().strength(1.5F, 1.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MUD_VERTICAL = registerBlock("vertical_mud_slab", () -> new VerticalSlabBlock(Blocks.MUD, ESPSlabs.MUD_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_DIRT, MaterialColor.TERRACOTTA_CYAN).strength(0.5F).isValidSpawn(ESPVerticalSlabs::always).isRedstoneConductor(ESPVerticalSlabs::always).isViewBlocking(ESPVerticalSlabs::always).isSuffocating(ESPVerticalSlabs::always).sound(SoundType.MUD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PACKED_MUD_VERTICAL = registerBlock("vertical_packed_mud_slab", () -> new VerticalSlabBlock(Blocks.PACKED_MUD, ESPSlabs.PACKED_MUD_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_MUD, MaterialColor.DIRT).strength(1.0F, 3.0F).sound(SoundType.PACKED_MUD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MUD_BRICK_VERTICAL = registerBlock("vertical_mud_brick_slab", () -> new VerticalSlabBlock(Blocks.MUD_BRICKS, Blocks.MUD_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(1.5F, 3.0F).sound(SoundType.MUD_BRICKS)), ExtendedSlabs.GROUP);

	// WOOL
	public static final RegistryObject<Block> WHITE_WOOL_VERTICAL = registerBlock("vertical_white_wool_slab", () -> new VerticalSlabBlock(Blocks.WHITE_WOOL, ESPSlabs.WHITE_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.SNOW).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ORANGE_WOOL_VERTICAL = registerBlock("vertical_orange_wool_slab", () -> new VerticalSlabBlock(Blocks.ORANGE_WOOL, ESPSlabs.ORANGE_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_ORANGE).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MAGENTA_WOOL_VERTICAL = registerBlock("vertical_magenta_wool_slab", () -> new VerticalSlabBlock(Blocks.MAGENTA_WOOL, ESPSlabs.MAGENTA_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_MAGENTA).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_BLUE_WOOL_VERTICAL = registerBlock("vertical_light_blue_wool_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_BLUE_WOOL, ESPSlabs.LIGHT_BLUE_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_LIGHT_BLUE).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> YELLOW_WOOL_VERTICAL = registerBlock("vertical_yellow_wool_slab", () -> new VerticalSlabBlock(Blocks.YELLOW_WOOL, ESPSlabs.YELLOW_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_YELLOW).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIME_WOOL_VERTICAL = registerBlock("vertical_lime_wool_slab", () -> new VerticalSlabBlock(Blocks.LIME_WOOL, ESPSlabs.LIME_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_LIGHT_GREEN).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PINK_WOOL_VERTICAL = registerBlock("vertical_pink_wool_slab", () -> new VerticalSlabBlock(Blocks.PINK_WOOL, ESPSlabs.PINK_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_PINK).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRAY_WOOL_VERTICAL = registerBlock("vertical_gray_wool_slab", () -> new VerticalSlabBlock(Blocks.GRAY_WOOL, ESPSlabs.GRAY_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_GRAY).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_GRAY_WOOL_VERTICAL = registerBlock("vertical_light_gray_wool_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_GRAY_WOOL, ESPSlabs.LIGHT_GRAY_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_LIGHT_GRAY).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CYAN_WOOL_VERTICAL = registerBlock("vertical_cyan_wool_slab", () -> new VerticalSlabBlock(Blocks.CYAN_WOOL, ESPSlabs.CYAN_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_CYAN).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PURPLE_WOOL_VERTICAL = registerBlock("vertical_purple_wool_slab", () -> new VerticalSlabBlock(Blocks.PURPLE_WOOL, ESPSlabs.PURPLE_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_PURPLE).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLUE_WOOL_VERTICAL = registerBlock("vertical_blue_wool_slab", () -> new VerticalSlabBlock(Blocks.BLUE_WOOL, ESPSlabs.BLUE_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_BLUE).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BROWN_WOOL_VERTICAL = registerBlock("vertical_brown_wool_slab", () -> new VerticalSlabBlock(Blocks.BROWN_WOOL, ESPSlabs.BROWN_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_BROWN).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GREEN_WOOL_VERTICAL = registerBlock("vertical_green_wool_slab", () -> new VerticalSlabBlock(Blocks.GREEN_WOOL, ESPSlabs.GREEN_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_GREEN).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_WOOL_VERTICAL = registerBlock("vertical_red_wool_slab", () -> new VerticalSlabBlock(Blocks.RED_WOOL, ESPSlabs.RED_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_RED).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLACK_WOOL_VERTICAL = registerBlock("vertical_black_wool_slab", () -> new VerticalSlabBlock(Blocks.BLACK_WOOL, ESPSlabs.BLACK_WOOL_SLAB.get(), Block.Properties.of(ESPMaterial.WOOL, MaterialColor.COLOR_BLACK).strength(0.8F).sound(SoundType.WOOL)), ExtendedSlabs.GROUP);

	// CONCRETE_POWDER
	public static final RegistryObject<Block> WHITE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_white_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.WHITE_CONCRETE_POWDER, ESPSlabs.WHITE_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.WHITE).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ORANGE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_orange_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.ORANGE_CONCRETE_POWDER, ESPSlabs.ORANGE_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.ORANGE).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MAGENTA_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_magenta_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.MAGENTA_CONCRETE_POWDER, ESPSlabs.MAGENTA_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.MAGENTA).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_light_blue_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.LIGHT_BLUE_CONCRETE_POWDER, ESPSlabs.LIGHT_BLUE_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.LIGHT_BLUE).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> YELLOW_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_yellow_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.YELLOW_CONCRETE_POWDER, ESPSlabs.YELLOW_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.YELLOW).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIME_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_lime_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.LIME_CONCRETE_POWDER, ESPSlabs.LIME_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.LIME).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PINK_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_pink_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.PINK_CONCRETE_POWDER, ESPSlabs.PINK_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.PINK).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRAY_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_gray_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.GRAY_CONCRETE_POWDER, ESPSlabs.GRAY_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.GRAY).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_light_gray_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.LIGHT_GRAY_CONCRETE_POWDER, ESPSlabs.LIGHT_GRAY_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.LIGHT_GRAY).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CYAN_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_cyan_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.CYAN_CONCRETE_POWDER, ESPSlabs.CYAN_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.CYAN).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PURPLE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_purple_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.PURPLE_CONCRETE_POWDER, ESPSlabs.PURPLE_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.PURPLE).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLUE_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_blue_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.BLUE_CONCRETE_POWDER, ESPSlabs.BLUE_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.BLUE).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BROWN_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_brown_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.BROWN_CONCRETE_POWDER, ESPSlabs.BROWN_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.BROWN).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GREEN_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_green_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.GREEN_CONCRETE_POWDER, ESPSlabs.GREEN_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.GREEN).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_red_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.RED_CONCRETE_POWDER, ESPSlabs.RED_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.RED).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLACK_CONCRETE_POWDER_VERTICAL = registerBlock("vertical_black_concrete_powder_slab", () -> new FallingVerticalSlabBlock(Blocks.BLACK_CONCRETE_POWDER, ESPSlabs.BLACK_CONCRETE_POWDER_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_SAND, DyeColor.BLACK).strength(0.5F).sound(SoundType.SAND)), ExtendedSlabs.GROUP);

	// CONCRETE
	public static final RegistryObject<Block> WHITE_CONCRETE_VERTICAL = registerBlock("vertical_white_concrete_slab", () -> new VerticalSlabBlock(Blocks.WHITE_CONCRETE, ESPSlabs.WHITE_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.WHITE).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ORANGE_CONCRETE_VERTICAL = registerBlock("vertical_orange_concrete_slab", () -> new VerticalSlabBlock(Blocks.ORANGE_CONCRETE, ESPSlabs.ORANGE_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.ORANGE).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MAGENTA_CONCRETE_VERTICAL = registerBlock("vertical_magenta_concrete_slab", () -> new VerticalSlabBlock(Blocks.MAGENTA_CONCRETE, ESPSlabs.MAGENTA_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.MAGENTA).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_VERTICAL = registerBlock("vertical_light_blue_concrete_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_BLUE_CONCRETE, ESPSlabs.LIGHT_BLUE_CONCRETE_SLAB.get(), BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.LIGHT_BLUE).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> YELLOW_CONCRETE_VERTICAL = registerBlock("vertical_yellow_concrete_slab", () -> new VerticalSlabBlock(Blocks.YELLOW_CONCRETE, ESPSlabs.YELLOW_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.YELLOW).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIME_CONCRETE_VERTICAL = registerBlock("vertical_lime_concrete_slab", () -> new VerticalSlabBlock(Blocks.LIME_CONCRETE, ESPSlabs.LIME_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.LIME).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PINK_CONCRETE_VERTICAL = registerBlock("vertical_pink_concrete_slab", () -> new VerticalSlabBlock(Blocks.PINK_CONCRETE, ESPSlabs.PINK_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.PINK).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRAY_CONCRETE_VERTICAL = registerBlock("vertical_gray_concrete_slab", () -> new VerticalSlabBlock(Blocks.GRAY_CONCRETE, ESPSlabs.GRAY_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.GRAY).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_VERTICAL = registerBlock("vertical_light_gray_concrete_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_GRAY_CONCRETE, ESPSlabs.LIGHT_GRAY_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.LIGHT_GRAY).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CYAN_CONCRETE_VERTICAL = registerBlock("vertical_cyan_concrete_slab", () -> new VerticalSlabBlock(Blocks.CYAN_CONCRETE, ESPSlabs.CYAN_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.CYAN).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PURPLE_CONCRETE_VERTICAL = registerBlock("vertical_purple_concrete_slab", () -> new VerticalSlabBlock(Blocks.PURPLE_CONCRETE, ESPSlabs.PURPLE_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.PURPLE).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLUE_CONCRETE_VERTICAL = registerBlock("vertical_blue_concrete_slab", () -> new VerticalSlabBlock(Blocks.BLUE_CONCRETE, ESPSlabs.BLUE_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.BLUE).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BROWN_CONCRETE_VERTICAL = registerBlock("vertical_brown_concrete_slab", () -> new VerticalSlabBlock(Blocks.BROWN_CONCRETE, ESPSlabs.BROWN_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.BROWN).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GREEN_CONCRETE_VERTICAL = registerBlock("vertical_green_concrete_slab", () -> new VerticalSlabBlock(Blocks.GREEN_CONCRETE, ESPSlabs.GREEN_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.GREEN).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_CONCRETE_VERTICAL = registerBlock("vertical_red_concrete_slab", () -> new VerticalSlabBlock(Blocks.RED_CONCRETE, ESPSlabs.RED_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.RED).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLACK_CONCRETE_VERTICAL = registerBlock("vertical_black_concrete_slab", () -> new VerticalSlabBlock(Blocks.BLACK_CONCRETE, ESPSlabs.BLACK_CONCRETE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.BLACK).requiresCorrectToolForDrops().strength(1.8F)), ExtendedSlabs.GROUP);

	// TERRACOTTA
	public static final RegistryObject<Block> CLAY_VERTICAL = registerBlock("vertical_clay_slab", () -> new VerticalSlabBlock(Blocks.CLAY, ESPSlabs.CLAY_SLAB.get(), Block.Properties.of(ESPMaterial.SHOVEL_CLAY, MaterialColor.CLAY).strength(0.6F).sound(SoundType.GRAVEL)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> TERRACOTTA_VERTICAL = registerBlock("vertical_terracotta_slab", () -> new VerticalSlabBlock(Blocks.TERRACOTTA, ESPSlabs.TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WHITE_TERRACOTTA_VERTICAL = registerBlock("vertical_white_terracotta_slab", () -> new VerticalSlabBlock(Blocks.WHITE_TERRACOTTA, ESPSlabs.WHITE_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_WHITE).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ORANGE_TERRACOTTA_VERTICAL = registerBlock("vertical_orange_terracotta_slab", () -> new VerticalSlabBlock(Blocks.ORANGE_TERRACOTTA, ESPSlabs.ORANGE_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_ORANGE).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MAGENTA_TERRACOTTA_VERTICAL = registerBlock("vertical_magenta_terracotta_slab", () -> new VerticalSlabBlock(Blocks.MAGENTA_TERRACOTTA, ESPSlabs.MAGENTA_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_MAGENTA).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_BLUE_TERRACOTTA_VERTICAL = registerBlock("vertical_light_blue_terracotta_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_BLUE_TERRACOTTA, ESPSlabs.LIGHT_BLUE_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_LIGHT_BLUE).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> YELLOW_TERRACOTTA_VERTICAL = registerBlock("vertical_yellow_terracotta_slab", () -> new VerticalSlabBlock(Blocks.YELLOW_TERRACOTTA, ESPSlabs.YELLOW_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_YELLOW).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIME_TERRACOTTA_VERTICAL = registerBlock("vertical_lime_terracotta_slab", () -> new VerticalSlabBlock(Blocks.LIME_TERRACOTTA, ESPSlabs.LIME_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_LIGHT_GREEN).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PINK_TERRACOTTA_VERTICAL = registerBlock("vertical_pink_terracotta_slab", () -> new VerticalSlabBlock(Blocks.PINK_TERRACOTTA, ESPSlabs.PINK_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_PINK).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRAY_TERRACOTTA_VERTICAL = registerBlock("vertical_gray_terracotta_slab", () -> new VerticalSlabBlock(Blocks.GRAY_TERRACOTTA, ESPSlabs.GRAY_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_GRAY).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_GRAY_TERRACOTTA_VERTICAL = registerBlock("vertical_light_gray_terracotta_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_GRAY_TERRACOTTA, ESPSlabs.LIGHT_GRAY_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CYAN_TERRACOTTA_VERTICAL = registerBlock("vertical_cyan_terracotta_slab", () -> new VerticalSlabBlock(Blocks.CYAN_TERRACOTTA, ESPSlabs.CYAN_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_CYAN).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PURPLE_TERRACOTTA_VERTICAL = registerBlock("vertical_purple_terracotta_slab", () -> new VerticalSlabBlock(Blocks.PURPLE_TERRACOTTA, ESPSlabs.PURPLE_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_PURPLE).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLUE_TERRACOTTA_VERTICAL = registerBlock("vertical_blue_terracotta_slab", () -> new VerticalSlabBlock(Blocks.BLUE_TERRACOTTA, ESPSlabs.BLUE_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_BLUE).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BROWN_TERRACOTTA_VERTICAL = registerBlock("vertical_brown_terracotta_slab", () -> new VerticalSlabBlock(Blocks.BROWN_TERRACOTTA, ESPSlabs.BROWN_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_BROWN).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GREEN_TERRACOTTA_VERTICAL = registerBlock("vertical_green_terracotta_slab", () -> new VerticalSlabBlock(Blocks.GREEN_TERRACOTTA, ESPSlabs.GREEN_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_GREEN).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_TERRACOTTA_VERTICAL = registerBlock("vertical_red_terracotta_slab", () -> new VerticalSlabBlock(Blocks.RED_TERRACOTTA, ESPSlabs.RED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_RED).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLACK_TERRACOTTA_VERTICAL = registerBlock("vertical_black_terracotta_slab", () -> new VerticalSlabBlock(Blocks.BLACK_TERRACOTTA, ESPSlabs.BLACK_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.TERRACOTTA_BLACK).requiresCorrectToolForDrops().strength(1.25F, 4.2F)), ExtendedSlabs.GROUP);

	// GLAZED TERRACOTTA
	public static final RegistryObject<Block> WHITE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_white_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.WHITE_GLAZED_TERRACOTTA, ESPSlabs.WHITE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.WHITE).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ORANGE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_orange_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.ORANGE_GLAZED_TERRACOTTA, ESPSlabs.ORANGE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.ORANGE).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MAGENTA_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_magenta_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.MAGENTA_GLAZED_TERRACOTTA, ESPSlabs.MAGENTA_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.MAGENTA).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_BLUE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_light_blue_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, ESPSlabs.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.LIGHT_BLUE).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> YELLOW_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_yellow_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.YELLOW_GLAZED_TERRACOTTA, ESPSlabs.YELLOW_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.YELLOW).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIME_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_lime_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.LIME_GLAZED_TERRACOTTA, ESPSlabs.LIME_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.LIME).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PINK_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_pink_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.PINK_GLAZED_TERRACOTTA, ESPSlabs.PINK_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.PINK).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRAY_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_gray_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.GRAY_GLAZED_TERRACOTTA, ESPSlabs.GRAY_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.GRAY).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_GRAY_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_light_gray_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, ESPSlabs.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.LIGHT_GRAY).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CYAN_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_cyan_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.CYAN_GLAZED_TERRACOTTA, ESPSlabs.CYAN_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.CYAN).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PURPLE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_purple_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.PURPLE_GLAZED_TERRACOTTA, ESPSlabs.PURPLE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.PURPLE).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLUE_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_blue_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.BLUE_GLAZED_TERRACOTTA, ESPSlabs.BLUE_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.BLUE).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BROWN_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_brown_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.BROWN_GLAZED_TERRACOTTA, ESPSlabs.BROWN_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.BROWN).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GREEN_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_green_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.GREEN_GLAZED_TERRACOTTA, ESPSlabs.GREEN_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.GREEN).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_red_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.RED_GLAZED_TERRACOTTA, ESPSlabs.RED_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.RED).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLACK_GLAZED_TERRACOTTA_VERTICAL = registerBlock("vertical_black_glazed_terracotta_slab", () -> new VerticalSlabBlock(Blocks.BLACK_GLAZED_TERRACOTTA, ESPSlabs.BLACK_GLAZED_TERRACOTTA_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, DyeColor.BLACK).requiresCorrectToolForDrops().strength(1.4F)), ExtendedSlabs.GROUP);

	// GLASS
	public static final RegistryObject<Block> GLASS_VERTICAL = registerBlock("vertical_glass_slab", () -> new GlassVerticalSlabBlock(Blocks.GLASS, ESPSlabs.GLASS_SLAB.get(), Block.Properties.of(ESPMaterial.GLASS).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> TINTED_GLASS_VERTICAL = registerBlock("vertical_tinted_glass_slab", () -> new TintedGlassVerticalSlabBlock(Blocks.TINTED_GLASS, ESPSlabs.TINTED_GLASS_SLAB.get(), Block.Properties.of(ESPMaterial.GLASS, MaterialColor.COLOR_GRAY).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WHITE_STAINED_GLASS_VERTICAL = registerBlock("vertical_white_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.WHITE_STAINED_GLASS, ESPSlabs.WHITE_STAINED_GLASS_SLAB.get(), DyeColor.WHITE, Block.Properties.of(ESPMaterial.GLASS, DyeColor.WHITE).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ORANGE_STAINED_GLASS_VERTICAL = registerBlock("vertical_orange_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.ORANGE_STAINED_GLASS, ESPSlabs.ORANGE_STAINED_GLASS_SLAB.get(), DyeColor.ORANGE, Block.Properties.of(ESPMaterial.GLASS, DyeColor.ORANGE).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MAGENTA_STAINED_GLASS_VERTICAL = registerBlock("vertical_magenta_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.MAGENTA_STAINED_GLASS, ESPSlabs.MAGENTA_STAINED_GLASS_SLAB.get(), DyeColor.MAGENTA, Block.Properties.of(ESPMaterial.GLASS, DyeColor.MAGENTA).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_BLUE_STAINED_GLASS_VERTICAL = registerBlock("vertical_light_blue_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.LIGHT_BLUE_STAINED_GLASS, ESPSlabs.LIGHT_BLUE_STAINED_GLASS_SLAB.get(), DyeColor.LIGHT_BLUE, Block.Properties.of(ESPMaterial.GLASS, DyeColor.LIGHT_BLUE).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> YELLOW_STAINED_GLASS_VERTICAL = registerBlock("vertical_yellow_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.YELLOW_STAINED_GLASS, ESPSlabs.YELLOW_STAINED_GLASS_SLAB.get(), DyeColor.YELLOW, Block.Properties.of(ESPMaterial.GLASS, DyeColor.YELLOW).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIME_STAINED_GLASS_VERTICAL = registerBlock("vertical_lime_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.LIME_STAINED_GLASS, ESPSlabs.LIME_STAINED_GLASS_SLAB.get(), DyeColor.LIME, Block.Properties.of(ESPMaterial.GLASS, DyeColor.LIME).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PINK_STAINED_GLASS_VERTICAL = registerBlock("vertical_pink_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.PINK_STAINED_GLASS, ESPSlabs.PINK_STAINED_GLASS_SLAB.get(), DyeColor.PINK, Block.Properties.of(ESPMaterial.GLASS, DyeColor.PINK).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GRAY_STAINED_GLASS_VERTICAL = registerBlock("vertical_gray_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.GRAY_STAINED_GLASS, ESPSlabs.GRAY_STAINED_GLASS_SLAB.get(), DyeColor.GRAY, Block.Properties.of(ESPMaterial.GLASS, DyeColor.GRAY).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> LIGHT_GRAY_STAINED_GLASS_VERTICAL = registerBlock("vertical_light_gray_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.LIGHT_GRAY_STAINED_GLASS, ESPSlabs.LIGHT_GRAY_STAINED_GLASS_SLAB.get(), DyeColor.LIGHT_GRAY, Block.Properties.of(ESPMaterial.GLASS, DyeColor.LIGHT_GRAY).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CYAN_STAINED_GLASS_VERTICAL = registerBlock("vertical_cyan_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.CYAN_STAINED_GLASS, ESPSlabs.CYAN_STAINED_GLASS_SLAB.get(), DyeColor.CYAN, Block.Properties.of(ESPMaterial.GLASS, DyeColor.CYAN).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PURPLE_STAINED_GLASS_VERTICAL = registerBlock("vertical_purple_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.PURPLE_STAINED_GLASS, ESPSlabs.PURPLE_STAINED_GLASS_SLAB.get(), DyeColor.PURPLE, Block.Properties.of(ESPMaterial.GLASS, DyeColor.PURPLE).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLUE_STAINED_GLASS_VERTICAL = registerBlock("vertical_blue_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.BLUE_STAINED_GLASS, ESPSlabs.BLUE_STAINED_GLASS_SLAB.get(), DyeColor.BLUE, Block.Properties.of(ESPMaterial.GLASS, DyeColor.BLUE).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BROWN_STAINED_GLASS_VERTICAL = registerBlock("vertical_brown_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.BROWN_STAINED_GLASS, ESPSlabs.BROWN_STAINED_GLASS_SLAB.get(), DyeColor.BROWN, Block.Properties.of(ESPMaterial.GLASS, DyeColor.BROWN).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> GREEN_STAINED_GLASS_VERTICAL = registerBlock("vertical_green_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.GREEN_STAINED_GLASS, ESPSlabs.GREEN_STAINED_GLASS_SLAB.get(), DyeColor.GREEN, Block.Properties.of(ESPMaterial.GLASS, DyeColor.GREEN).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_STAINED_GLASS_VERTICAL = registerBlock("vertical_red_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.RED_STAINED_GLASS, ESPSlabs.RED_STAINED_GLASS_SLAB.get(), DyeColor.RED, Block.Properties.of(ESPMaterial.GLASS, DyeColor.RED).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BLACK_STAINED_GLASS_VERTICAL = registerBlock("vertical_black_stained_glass_slab", () -> new StainedGlassVerticalSlabBlock(Blocks.BLACK_STAINED_GLASS, ESPSlabs.BLACK_STAINED_GLASS_SLAB.get(), DyeColor.BLACK, Block.Properties.of(ESPMaterial.GLASS, DyeColor.BLACK).strength(0.3F).sound(SoundType.GLASS).noOcclusion().isValidSpawn(ESPVerticalSlabs::never).isRedstoneConductor(ESPVerticalSlabs::never).isSuffocating(ESPVerticalSlabs::never).isViewBlocking(ESPVerticalSlabs::never)), ExtendedSlabs.GROUP);

	// SANDSTONE
	public static final RegistryObject<Block> SANDSTONE_VERTICAL = registerBlock("vertical_sandstone_slab", () -> new VerticalSlabBlock(Blocks.SANDSTONE, Blocks.SANDSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.SAND).requiresCorrectToolForDrops().strength(0.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> SMOOTH_SANDSTONE_VERTICAL = registerBlock("vertical_smooth_sandstone_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_SANDSTONE, Blocks.SMOOTH_SANDSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.SAND).requiresCorrectToolForDrops().strength(0.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CUT_SANDSTONE_VERTICAL = registerBlock("vertical_cut_sandstone_slab", () -> new VerticalSlabBlock(Blocks.CUT_SANDSTONE, Blocks.CUT_SANDSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.SAND).requiresCorrectToolForDrops().strength(0.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_SANDSTONE_VERTICAL = registerBlock("vertical_red_sandstone_slab", () -> new VerticalSlabBlock(Blocks.RED_SANDSTONE, Blocks.RED_SANDSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(0.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> SMOOTH_RED_SANDSTONE_VERTICAL = registerBlock("vertical_smooth_red_sandstone_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_RED_SANDSTONE, Blocks.SMOOTH_RED_SANDSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(0.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CUT_RED_SANDSTONE_VERTICAL = registerBlock("vertical_cut_red_sandstone_slab", () -> new VerticalSlabBlock(Blocks.CUT_RED_SANDSTONE, Blocks.CUT_RED_SANDSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(0.8F)), ExtendedSlabs.GROUP);

	// DEEPSLATE
	public static final RegistryObject<Block> COBBLED_DEEPSLATE_VERTICAL = registerBlock("vertical_cobbled_deepslate_slab", () -> new VerticalSlabBlock(Blocks.COBBLED_DEEPSLATE, Blocks.COBBLED_DEEPSLATE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DEEPSLATE).requiresCorrectToolForDrops().strength(3.5F, 6.0F).sound(SoundType.DEEPSLATE)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> POLISHED_DEEPSLATE_VERTICAL = registerBlock("vertical_polished_deepslate_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_DEEPSLATE, Blocks.POLISHED_DEEPSLATE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DEEPSLATE).requiresCorrectToolForDrops().strength(3.5F, 6.0F).sound(SoundType.POLISHED_DEEPSLATE)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DEEPSLATE_BRICK_VERTICAL = registerBlock("vertical_deepslate_brick_slab", () -> new VerticalSlabBlock(Blocks.DEEPSLATE_BRICKS, Blocks.DEEPSLATE_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DEEPSLATE).requiresCorrectToolForDrops().strength(3.5F, 6.0F).sound(SoundType.DEEPSLATE_BRICKS)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DEEPSLATE_TILE_VERTICAL = registerBlock("vertical_deepslate_tile_slab", () -> new VerticalSlabBlock(Blocks.DEEPSLATE_TILES, Blocks.DEEPSLATE_TILE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DEEPSLATE).requiresCorrectToolForDrops().strength(3.5F, 6.0F).sound(SoundType.DEEPSLATE_TILES)), ExtendedSlabs.GROUP);

	// NETHER
	public static final RegistryObject<Block> BLACKSTONE_VERTICAL = registerBlock("vertical_blackstone_slab", () -> new VerticalSlabBlock(Blocks.BLACKSTONE, Blocks.BLACKSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_VERTICAL = registerBlock("vertical_polished_blackstone_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_BLACKSTONE, Blocks.POLISHED_BLACKSTONE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_BRICK_VERTICAL = registerBlock("vertical_polished_blackstone_brick_slab", () -> new VerticalSlabBlock(Blocks.POLISHED_BLACKSTONE_BRICKS, Blocks.POLISHED_BLACKSTONE_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> NETHERRACK_VERTICAL = registerBlock("vertical_netherrack_slab", () -> new VerticalSlabBlock(Blocks.NETHERRACK, ESPSlabs.NETHERRACK_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.NETHER).requiresCorrectToolForDrops().strength(0.4F).sound(SoundType.NETHERRACK)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CRIMSON_NYLIUM_VERTICAL = registerBlock("vertical_crimson_nylium_slab", () -> new VerticalSlabBlock(Blocks.CRIMSON_NYLIUM, ESPSlabs.CRIMSON_NYLIUM_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.CRIMSON_NYLIUM).requiresCorrectToolForDrops().strength(0.4F).sound(SoundType.NYLIUM).randomTicks()), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WARPED_NYLIUM_VERTICAL = registerBlock("vertical_warped_nylium_slab", () -> new VerticalSlabBlock(Blocks.WARPED_NYLIUM, ESPSlabs.WARPED_NYLIUM_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(0.4F).sound(SoundType.NYLIUM).randomTicks()), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> NETHER_BRICK_VERTICAL = registerBlock("vertical_nether_brick_slab", () -> new VerticalSlabBlock(Blocks.NETHER_BRICKS, Blocks.NETHER_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.NETHER).requiresCorrectToolForDrops().strength(2.0F, 6.0F).sound(SoundType.NETHER_BRICKS)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> RED_NETHER_BRICK_VERTICAL = registerBlock("vertical_red_nether_brick_slab", () -> new VerticalSlabBlock(Blocks.RED_NETHER_BRICKS, Blocks.RED_NETHER_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.NETHER).requiresCorrectToolForDrops().strength(2.0F, 6.0F).sound(SoundType.NETHER_BRICKS)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> QUARTZ_VERTICAL = registerBlock("vertical_quartz_slab", () -> new VerticalSlabBlock(Blocks.QUARTZ_BLOCK, Blocks.QUARTZ_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.QUARTZ).requiresCorrectToolForDrops().strength(0.8F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> SMOOTH_QUARTZ_VERTICAL = registerBlock("vertical_smooth_quartz_slab", () -> new VerticalSlabBlock(Blocks.SMOOTH_QUARTZ, Blocks.SMOOTH_QUARTZ_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.QUARTZ).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ExtendedSlabs.GROUP);

	// END
	public static final RegistryObject<Block> END_STONE_VERTICAL = registerBlock("vertical_end_stone_slab", () -> new VerticalSlabBlock(Blocks.END_STONE, ESPSlabs.END_STONE_SLAB.get(), Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 9.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> END_STONE_BRICK_VERTICAL = registerBlock("vertical_end_stone_brick_slab", () -> new VerticalSlabBlock(Blocks.END_STONE_BRICKS, Blocks.END_STONE_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.SAND).requiresCorrectToolForDrops().strength(3.0F, 9.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PURPUR_VERTICAL = registerBlock("vertical_purpur_slab", () -> new VerticalSlabBlock(Blocks.PURPUR_BLOCK, Blocks.PURPUR_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_MAGENTA).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);

	// PRISMARINE
	public static final RegistryObject<Block> PRISMARINE_VERTICAL = registerBlock("vertical_prismarine_slab", () -> new VerticalSlabBlock(Blocks.PRISMARINE, Blocks.PRISMARINE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.COLOR_CYAN).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PRISMARINE_BRICK_VERTICAL = registerBlock("vertical_prismarine_brick_slab", () -> new VerticalSlabBlock(Blocks.PRISMARINE_BRICKS, Blocks.PRISMARINE_BRICK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DIAMOND).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DARK_PRISMARINE_VERTICAL = registerBlock("vertical_dark_prismarine_slab", () -> new VerticalSlabBlock(Blocks.DARK_PRISMARINE, Blocks.DARK_PRISMARINE_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.DIAMOND).requiresCorrectToolForDrops().strength(1.5F, 6.0F)), ExtendedSlabs.GROUP);

	// PLANKS
	public static final RegistryObject<Block> OAK_VERTICAL = registerBlock("vertical_oak_slab", () -> new VerticalSlabBlock(Blocks.OAK_PLANKS, Blocks.OAK_SLAB, Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.WOOD).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> SPRUCE_VERTICAL = registerBlock("vertical_spruce_slab", () -> new VerticalSlabBlock(Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_SLAB, Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.PODZOL).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BIRCH_VERTICAL = registerBlock("vertical_birch_slab", () -> new VerticalSlabBlock(Blocks.BIRCH_PLANKS, Blocks.BIRCH_SLAB, Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.SAND).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> JUNGLE_VERTICAL = registerBlock("vertical_jungle_slab", () -> new VerticalSlabBlock(Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_SLAB, Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.DIRT).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ACACIA_VERTICAL = registerBlock("vertical_acacia_slab", () -> new VerticalSlabBlock(Blocks.ACACIA_PLANKS, Blocks.ACACIA_SLAB, Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.COLOR_ORANGE).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DARK_OAK_VERTICAL = registerBlock("vertical_dark_oak_slab", () -> new VerticalSlabBlock(Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_SLAB, Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.COLOR_BROWN).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MANGROVE_VERTICAL = registerBlock("vertical_mangrove_slab", () -> new VerticalSlabBlock(Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_SLAB, Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.COLOR_RED).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CRIMSON_VERTICAL = registerBlock("vertical_crimson_slab", () -> new VerticalSlabBlock(Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_SLAB, Block.Properties.of(ESPMaterial.AXE_NETHER_WOOD, MaterialColor.CRIMSON_STEM).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WARPED_VERTICAL = registerBlock("vertical_warped_slab", () -> new VerticalSlabBlock(Blocks.WARPED_PLANKS, Blocks.WARPED_SLAB, Block.Properties.of(ESPMaterial.AXE_NETHER_WOOD, MaterialColor.WARPED_STEM).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> PETRIFIED_OAK_VERTICAL = registerBlock("vertical_petrified_oak_slab", () -> new VerticalSlabBlock(null, Blocks.PETRIFIED_OAK_SLAB, Block.Properties.of(ESPMaterial.PICKAXE_STONE, MaterialColor.WOOD).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ExtendedSlabs.GROUP);

	// WOOD
	public static final RegistryObject<Block> OAK_WOOD_VERTICAL = registerBlock("vertical_oak_wood_slab", () -> new VerticalSlabBlock(Blocks.OAK_WOOD, ESPSlabs.OAK_WOOD_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.WOOD).strength(2.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> SPRUCE_WOOD_VERTICAL = registerBlock("vertical_spruce_wood_slab", () -> new VerticalSlabBlock(Blocks.SPRUCE_WOOD, ESPSlabs.SPRUCE_WOOD_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.PODZOL).strength(2.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> BIRCH_WOOD_VERTICAL = registerBlock("vertical_birch_wood_slab", () -> new VerticalSlabBlock(Blocks.BIRCH_WOOD, ESPSlabs.BIRCH_WOOD_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.SAND).strength(2.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> JUNGLE_WOOD_VERTICAL = registerBlock("vertical_jungle_wood_slab", () -> new VerticalSlabBlock(Blocks.JUNGLE_WOOD, ESPSlabs.JUNGLE_WOOD_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.DIRT).strength(2.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> ACACIA_WOOD_VERTICAL = registerBlock("vertical_acacia_wood_slab", () -> new VerticalSlabBlock(Blocks.ACACIA_WOOD, ESPSlabs.ACACIA_WOOD_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.COLOR_ORANGE).strength(2.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> DARK_OAK_WOOD_VERTICAL = registerBlock("vertical_dark_oak_wood_slab", () -> new VerticalSlabBlock(Blocks.DARK_OAK_WOOD, ESPSlabs.DARK_OAK_WOOD_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.COLOR_BROWN).strength(2.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> MANGROVE_WOOD_VERTICAL = registerBlock("vertical_mangrove_wood_slab", () -> new VerticalSlabBlock(Blocks.MANGROVE_WOOD, ESPSlabs.MANGROVE_WOOD_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_WOOD, MaterialColor.COLOR_RED).strength(2.0F).sound(SoundType.WOOD)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CRIMSON_HYPHAE_VERTICAL = registerBlock("vertical_crimson_hyphae_slab", () -> new VerticalSlabBlock(Blocks.CRIMSON_HYPHAE, ESPSlabs.CRIMSON_HYPHAE_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_NETHER_WOOD, MaterialColor.CRIMSON_HYPHAE).strength(2.0F).sound(SoundType.STEM)), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WARPED_HYPHAE_VERTICAL = registerBlock("vertical_warped_hyphae_slab", () -> new VerticalSlabBlock(Blocks.WARPED_HYPHAE, ESPSlabs.WARPED_HYPHAE_SLAB.get(), Block.Properties.of(ESPMaterial.AXE_NETHER_WOOD, MaterialColor.WARPED_HYPHAE).strength(2.0F).sound(SoundType.STEM)), ExtendedSlabs.GROUP);

	// COPPER
	public static final RegistryObject<Block> OXIDIZED_CUT_COPPER_VERTICAL = registerBlock("vertical_oxidized_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.OXIDIZED_CUT_COPPER, Blocks.OXIDIZED_CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.OXIDIZED), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WEATHERED_CUT_COPPER_VERTICAL = registerBlock("vertical_weathered_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.WEATHERED_CUT_COPPER, Blocks.WEATHERED_CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.WEATHERED), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> EXPOSED_CUT_COPPER_VERTICAL = registerBlock("vertical_exposed_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.EXPOSED_CUT_COPPER, Blocks.EXPOSED_CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.EXPOSED), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> CUT_COPPER_VERTICAL = registerBlock("vertical_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.CUT_COPPER, Blocks.CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.UNAFFECTED), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WAXED_OXIDIZED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_oxidized_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.WAXED_OXIDIZED_CUT_COPPER, Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.OXIDIZED), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WAXED_WEATHERED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_weathered_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.WAXED_WEATHERED_CUT_COPPER, Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.WEATHERED), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WAXED_EXPOSED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_exposed_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.WAXED_EXPOSED_CUT_COPPER, Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.EXPOSED), ExtendedSlabs.GROUP);
	public static final RegistryObject<Block> WAXED_CUT_COPPER_VERTICAL = registerBlock("vertical_waxed_cut_copper_slab", () -> new WeatheringCopperVerticalSlabBlock(Blocks.WAXED_CUT_COPPER, Blocks.WAXED_CUT_COPPER_SLAB, BlockBehaviour.Properties.of(ESPMaterial.PICKAXE_METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundType.COPPER), WeatheringCopper.WeatherState.UNAFFECTED), ExtendedSlabs.GROUP);

	public static <B extends Block> RegistryObject<B> registerBlock(String name, Supplier<? extends B> supplier, CreativeModeTab itemGroup) {
		RegistryObject<B> block = ESPVerticalSlabs.BLOCKS.register(name, supplier);
		ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties().tab(itemGroup)));
		return block;
	}

	private static boolean always(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos) {
		return true;
	}

	private static Boolean always(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos, EntityType<?> entityType) {
		return true;
	}

	private static boolean never(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos) {
		return false;
	}

	private static Boolean never(BlockState p_50779_, BlockGetter p_50780_, BlockPos p_50781_, EntityType<?> p_50782_) {
		return false;
	}
}
