package com.blackout.extendedslabs.registry;

import com.blackout.extendedslabs.ExtendedSlabs;
import com.blackout.extendedslabs.blocks.ESPCornerBlock;
import com.blackout.extendedslabs.blocks.copper.WeatheringCopperCornerBlock;
import com.blackout.extendedslabs.blocks.falling.FallingCornerBlock;
import com.blackout.extendedslabs.blocks.glass.GlassCornerBlock;
import com.blackout.extendedslabs.blocks.glass.StainedGlassCornerBlock;
import com.blackout.extendedslabs.blocks.glass.TintedGlassCornerBlock;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.WeatheringCopper;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.Collection;
import java.util.function.Supplier;

import static com.blackout.extendedslabs.blocks.IBlockCharacteristics.tag;

@Mod.EventBusSubscriber(modid = ExtendedSlabs.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ESPCorners {
	public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, ExtendedSlabs.MODID);
	public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ExtendedSlabs.MODID);

	// DIRT
	public static final RegistryObject<Block> DIRT_CORNER = registerBlock("dirt_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.DIRT, ESPStairs.DIRT_STAIRS.get(), Block.Properties.copy(Blocks.DIRT)));
	public static final RegistryObject<Block> COARSE_DIRT_CORNER = registerBlock("coarse_dirt_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.COARSE_DIRT, ESPStairs.COARSE_DIRT_STAIRS.get(), Block.Properties.copy(Blocks.COARSE_DIRT)));
	public static final RegistryObject<Block> ROOTED_DIRT_CORNER = registerBlock("rooted_dirt_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.ROOTED_DIRT, ESPStairs.ROOTED_DIRT_STAIRS.get(), Block.Properties.copy(Blocks.ROOTED_DIRT)));
	public static final RegistryObject<Block> SAND_CORNER = registerBlock("sand_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.SAND, ESPStairs.SAND_STAIRS.get(), Block.Properties.copy(Blocks.SAND)));
	public static final RegistryObject<Block> RED_SAND_CORNER = registerBlock("red_sand_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.RED_SAND, ESPStairs.RED_SAND_STAIRS.get(), Block.Properties.copy(Blocks.RED_SAND)));
	public static final RegistryObject<Block> GRAVEL_CORNER = registerBlock("gravel_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GRAVEL, ESPStairs.GRAVEL_STAIRS.get(), Block.Properties.copy(Blocks.GRAVEL)));

	// STONE
	public static final RegistryObject<Block> COBBLESTONE_CORNER = registerBlock("cobblestone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.COBBLESTONE, Blocks.COBBLESTONE_STAIRS, Block.Properties.copy(Blocks.COBBLESTONE)));
	public static final RegistryObject<Block> STONE_CORNER = registerBlock("stone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.STONE, Blocks.STONE_STAIRS, Block.Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> STONE_BRICK_CORNER = registerBlock("stone_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.STONE_BRICKS, Blocks.STONE_BRICK_STAIRS, Block.Properties.copy(Blocks.STONE_BRICKS)));
	public static final RegistryObject<Block> SMOOTH_STONE_CORNER = registerBlock("smooth_stone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_STONE, ESPStairs.SMOOTH_STONE_STAIRS.get(), Block.Properties.copy(Blocks.SMOOTH_STONE)));
	public static final RegistryObject<Block> MOSSY_COBBLESTONE_CORNER = registerBlock("mossy_cobblestone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MOSSY_COBBLESTONE, Blocks.MOSSY_COBBLESTONE_STAIRS, Block.Properties.copy(Blocks.MOSSY_COBBLESTONE)));
	public static final RegistryObject<Block> MOSSY_STONE_BRICK_CORNER = registerBlock("mossy_stone_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MOSSY_STONE_BRICKS, Blocks.MOSSY_STONE_BRICK_STAIRS, Block.Properties.copy(Blocks.MOSSY_STONE_BRICKS)));
	public static final RegistryObject<Block> ANDESITE_CORNER = registerBlock("andesite_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ANDESITE, Blocks.ANDESITE_STAIRS, Block.Properties.copy(Blocks.ANDESITE)));
	public static final RegistryObject<Block> POLISHED_ANDESITE_CORNER = registerBlock("polished_andesite_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_ANDESITE, Blocks.POLISHED_ANDESITE_STAIRS, Block.Properties.copy(Blocks.POLISHED_ANDESITE)));
	public static final RegistryObject<Block> DIORITE_CORNER = registerBlock("diorite_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DIORITE, Blocks.DIORITE_STAIRS, Block.Properties.copy(Blocks.DIORITE)));
	public static final RegistryObject<Block> POLISHED_DIORITE_CORNER = registerBlock("polished_diorite_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_DIORITE, Blocks.POLISHED_DIORITE_STAIRS, Block.Properties.copy(Blocks.POLISHED_DIORITE)));
	public static final RegistryObject<Block> GRANITE_CORNER = registerBlock("granite_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRANITE, Blocks.GRANITE_STAIRS, Block.Properties.copy(Blocks.GRANITE)));
	public static final RegistryObject<Block> POLISHED_GRANITE_CORNER = registerBlock("polished_granite_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_GRANITE, Blocks.POLISHED_GRANITE_STAIRS, Block.Properties.copy(Blocks.POLISHED_GRANITE)));
	public static final RegistryObject<Block> BRICK_CORNER = registerBlock("brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BRICKS, Blocks.BRICK_STAIRS, Block.Properties.copy(Blocks.BRICKS)));
	public static final RegistryObject<Block> TUFF_CORNER = registerBlock("tuff_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.TUFF, ESPStairs.TUFF_STAIRS.get(), Block.Properties.copy(Blocks.TUFF)));
	public static final RegistryObject<Block> CALCITE_CORNER = registerBlock("calcite_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CALCITE, ESPStairs.CALCITE_STAIRS.get(), Block.Properties.copy(Blocks.CALCITE)));
	public static final RegistryObject<Block> DRIPSTONE_CORNER = registerBlock("dripstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DRIPSTONE_BLOCK, ESPStairs.DRIPSTONE_STAIRS.get(), Block.Properties.copy(Blocks.DRIPSTONE_BLOCK)));
	public static final RegistryObject<Block> MUD_CORNER = registerBlock("mud_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.MUD, ESPStairs.MUD_STAIRS.get(), Block.Properties.copy(Blocks.MUD)));
	public static final RegistryObject<Block> PACKED_MUD_CORNER = registerBlock("packed_mud_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PACKED_MUD, ESPStairs.PACKED_MUD_STAIRS.get(), Block.Properties.copy(Blocks.PACKED_MUD)));
	public static final RegistryObject<Block> MUD_BRICK_CORNER = registerBlock("mud_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MUD_BRICKS, Blocks.MUD_BRICK_STAIRS, Block.Properties.copy(Blocks.MUD_BRICKS)));

	// WOOL
	public static final RegistryObject<Block> WHITE_WOOL_CORNER = registerBlock("white_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.WHITE_WOOL, ESPStairs.WHITE_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> ORANGE_WOOL_CORNER = registerBlock("orange_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.ORANGE_WOOL, ESPStairs.ORANGE_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.ORANGE_WOOL)));
	public static final RegistryObject<Block> MAGENTA_WOOL_CORNER = registerBlock("magenta_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.MAGENTA_WOOL, ESPStairs.MAGENTA_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.MAGENTA_WOOL)));
	public static final RegistryObject<Block> LIGHT_BLUE_WOOL_CORNER = registerBlock("light_blue_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.LIGHT_BLUE_WOOL, ESPStairs.LIGHT_BLUE_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_WOOL)));
	public static final RegistryObject<Block> YELLOW_WOOL_CORNER = registerBlock("yellow_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.YELLOW_WOOL, ESPStairs.YELLOW_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.YELLOW_WOOL)));
	public static final RegistryObject<Block> LIME_WOOL_CORNER = registerBlock("lime_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.LIME_WOOL, ESPStairs.LIME_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.LIME_WOOL)));
	public static final RegistryObject<Block> PINK_WOOL_CORNER = registerBlock("pink_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.PINK_WOOL, ESPStairs.PINK_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.PINK_WOOL)));
	public static final RegistryObject<Block> GRAY_WOOL_CORNER = registerBlock("gray_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.GRAY_WOOL, ESPStairs.GRAY_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.GRAY_WOOL)));
	public static final RegistryObject<Block> LIGHT_GRAY_WOOL_CORNER = registerBlock("light_gray_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.LIGHT_GRAY_WOOL, ESPStairs.LIGHT_GRAY_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_WOOL)));
	public static final RegistryObject<Block> CYAN_WOOL_CORNER = registerBlock("cyan_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.CYAN_WOOL, ESPStairs.CYAN_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.CYAN_WOOL)));
	public static final RegistryObject<Block> PURPLE_WOOL_CORNER = registerBlock("purple_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.PURPLE_WOOL, ESPStairs.PURPLE_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.PURPLE_WOOL)));
	public static final RegistryObject<Block> BLUE_WOOL_CORNER = registerBlock("blue_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.BLUE_WOOL, ESPStairs.BLUE_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.BLUE_WOOL)));
	public static final RegistryObject<Block> BROWN_WOOL_CORNER = registerBlock("brown_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.BROWN_WOOL, ESPStairs.BROWN_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.BROWN_WOOL)));
	public static final RegistryObject<Block> GREEN_WOOL_CORNER = registerBlock("green_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.GREEN_WOOL, ESPStairs.GREEN_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.GREEN_WOOL)));
	public static final RegistryObject<Block> RED_WOOL_CORNER = registerBlock("red_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.RED_WOOL, ESPStairs.RED_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.RED_WOOL)));
	public static final RegistryObject<Block> BLACK_WOOL_CORNER = registerBlock("black_wool_corner", () -> new ESPCornerBlock(tag(BlockTags.WOOL), Blocks.BLACK_WOOL, ESPStairs.BLACK_WOOL_STAIRS.get(), Block.Properties.copy(Blocks.BLACK_WOOL)));

	// CONCRETE_POWDER
	public static final RegistryObject<Block> WHITE_CONCRETE_POWDER_CORNER = registerBlock("white_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.WHITE_CONCRETE_POWDER, ESPStairs.WHITE_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.WHITE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> ORANGE_CONCRETE_POWDER_CORNER = registerBlock("orange_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.ORANGE_CONCRETE_POWDER, ESPStairs.ORANGE_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.ORANGE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> MAGENTA_CONCRETE_POWDER_CORNER = registerBlock("magenta_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.MAGENTA_CONCRETE_POWDER, ESPStairs.MAGENTA_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.MAGENTA_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_POWDER_CORNER = registerBlock("light_blue_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIGHT_BLUE_CONCRETE_POWDER, ESPStairs.LIGHT_BLUE_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> YELLOW_CONCRETE_POWDER_CORNER = registerBlock("yellow_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.YELLOW_CONCRETE_POWDER, ESPStairs.YELLOW_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.YELLOW_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIME_CONCRETE_POWDER_CORNER = registerBlock("lime_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIME_CONCRETE_POWDER, ESPStairs.LIME_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.LIME_CONCRETE_POWDER)));
	public static final RegistryObject<Block> PINK_CONCRETE_POWDER_CORNER = registerBlock("pink_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.PINK_CONCRETE_POWDER, ESPStairs.PINK_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.PINK_CONCRETE_POWDER)));
	public static final RegistryObject<Block> GRAY_CONCRETE_POWDER_CORNER = registerBlock("gray_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GRAY_CONCRETE_POWDER, ESPStairs.GRAY_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.GRAY_CONCRETE_POWDER)));
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_POWDER_CORNER = registerBlock("light_gray_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.LIGHT_GRAY_CONCRETE_POWDER, ESPStairs.LIGHT_GRAY_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE_POWDER)));
	public static final RegistryObject<Block> CYAN_CONCRETE_POWDER_CORNER = registerBlock("cyan_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.CYAN_CONCRETE_POWDER, ESPStairs.CYAN_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.CYAN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> PURPLE_CONCRETE_POWDER_CORNER = registerBlock("purple_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.PURPLE_CONCRETE_POWDER, ESPStairs.PURPLE_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.PURPLE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BLUE_CONCRETE_POWDER_CORNER = registerBlock("blue_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BLUE_CONCRETE_POWDER, ESPStairs.BLUE_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.BLUE_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BROWN_CONCRETE_POWDER_CORNER = registerBlock("brown_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BROWN_CONCRETE_POWDER, ESPStairs.BROWN_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.BROWN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> GREEN_CONCRETE_POWDER_CORNER = registerBlock("green_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.GREEN_CONCRETE_POWDER, ESPStairs.GREEN_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.GREEN_CONCRETE_POWDER)));
	public static final RegistryObject<Block> RED_CONCRETE_POWDER_CORNER = registerBlock("red_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.RED_CONCRETE_POWDER, ESPStairs.RED_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.RED_CONCRETE_POWDER)));
	public static final RegistryObject<Block> BLACK_CONCRETE_POWDER_CORNER = registerBlock("black_concrete_powder_corner", () -> new FallingCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.BLACK_CONCRETE_POWDER, ESPStairs.BLACK_CONCRETE_POWDER_STAIRS.get(), Block.Properties.copy(Blocks.BLACK_CONCRETE_POWDER)));

	// CONCRETE
	public static final RegistryObject<Block> WHITE_CONCRETE_CORNER = registerBlock("white_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_CONCRETE, ESPStairs.WHITE_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.WHITE_CONCRETE)));
	public static final RegistryObject<Block> ORANGE_CONCRETE_CORNER = registerBlock("orange_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_CONCRETE, ESPStairs.ORANGE_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.ORANGE_CONCRETE)));
	public static final RegistryObject<Block> MAGENTA_CONCRETE_CORNER = registerBlock("magenta_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_CONCRETE, ESPStairs.MAGENTA_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.MAGENTA_CONCRETE)));
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_CORNER = registerBlock("light_blue_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_CONCRETE, ESPStairs.LIGHT_BLUE_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_CONCRETE)));
	public static final RegistryObject<Block> YELLOW_CONCRETE_CORNER = registerBlock("yellow_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_CONCRETE, ESPStairs.YELLOW_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.YELLOW_CONCRETE)));
	public static final RegistryObject<Block> LIME_CONCRETE_CORNER = registerBlock("lime_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_CONCRETE, ESPStairs.LIME_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.LIME_CONCRETE)));
	public static final RegistryObject<Block> PINK_CONCRETE_CORNER = registerBlock("pink_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_CONCRETE, ESPStairs.PINK_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.PINK_CONCRETE)));
	public static final RegistryObject<Block> GRAY_CONCRETE_CORNER = registerBlock("gray_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_CONCRETE, ESPStairs.GRAY_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.GRAY_CONCRETE)));
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_CORNER = registerBlock("light_gray_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_CONCRETE, ESPStairs.LIGHT_GRAY_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_CONCRETE)));
	public static final RegistryObject<Block> CYAN_CONCRETE_CORNER = registerBlock("cyan_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_CONCRETE, ESPStairs.CYAN_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.CYAN_CONCRETE)));
	public static final RegistryObject<Block> PURPLE_CONCRETE_CORNER = registerBlock("purple_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_CONCRETE, ESPStairs.PURPLE_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.PURPLE_CONCRETE)));
	public static final RegistryObject<Block> BLUE_CONCRETE_CORNER = registerBlock("blue_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_CONCRETE, ESPStairs.BLUE_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.BLUE_CONCRETE)));
	public static final RegistryObject<Block> BROWN_CONCRETE_CORNER = registerBlock("brown_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_CONCRETE, ESPStairs.BROWN_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.BROWN_CONCRETE)));
	public static final RegistryObject<Block> GREEN_CONCRETE_CORNER = registerBlock("green_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_CONCRETE, ESPStairs.GREEN_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.GREEN_CONCRETE)));
	public static final RegistryObject<Block> RED_CONCRETE_CORNER = registerBlock("red_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_CONCRETE, ESPStairs.RED_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.RED_CONCRETE)));
	public static final RegistryObject<Block> BLACK_CONCRETE_CORNER = registerBlock("black_concrete_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_CONCRETE, ESPStairs.BLACK_CONCRETE_STAIRS.get(), Block.Properties.copy(Blocks.BLACK_CONCRETE)));

	// TERRACOTTA
	public static final RegistryObject<Block> CLAY_CORNER = registerBlock("clay_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_SHOVEL), Blocks.CLAY, ESPStairs.CLAY_STAIRS.get(), Block.Properties.copy(Blocks.CLAY)));
	public static final RegistryObject<Block> TERRACOTTA_CORNER = registerBlock("terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.TERRACOTTA, ESPStairs.TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.TERRACOTTA)));
	public static final RegistryObject<Block> WHITE_TERRACOTTA_CORNER = registerBlock("white_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_TERRACOTTA, ESPStairs.WHITE_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.WHITE_TERRACOTTA)));
	public static final RegistryObject<Block> ORANGE_TERRACOTTA_CORNER = registerBlock("orange_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_TERRACOTTA, ESPStairs.ORANGE_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.ORANGE_TERRACOTTA)));
	public static final RegistryObject<Block> MAGENTA_TERRACOTTA_CORNER = registerBlock("magenta_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_TERRACOTTA, ESPStairs.MAGENTA_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.MAGENTA_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_BLUE_TERRACOTTA_CORNER = registerBlock("light_blue_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_TERRACOTTA, ESPStairs.LIGHT_BLUE_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_TERRACOTTA)));
	public static final RegistryObject<Block> YELLOW_TERRACOTTA_CORNER = registerBlock("yellow_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_TERRACOTTA, ESPStairs.YELLOW_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.YELLOW_TERRACOTTA)));
	public static final RegistryObject<Block> LIME_TERRACOTTA_CORNER = registerBlock("lime_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_TERRACOTTA, ESPStairs.LIME_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.LIME_TERRACOTTA)));
	public static final RegistryObject<Block> PINK_TERRACOTTA_CORNER = registerBlock("pink_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_TERRACOTTA, ESPStairs.PINK_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.PINK_TERRACOTTA)));
	public static final RegistryObject<Block> GRAY_TERRACOTTA_CORNER = registerBlock("gray_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_TERRACOTTA, ESPStairs.GRAY_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.GRAY_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_GRAY_TERRACOTTA_CORNER = registerBlock("light_gray_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_TERRACOTTA, ESPStairs.LIGHT_GRAY_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_TERRACOTTA)));
	public static final RegistryObject<Block> CYAN_TERRACOTTA_CORNER = registerBlock("cyan_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_TERRACOTTA, ESPStairs.CYAN_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.CYAN_TERRACOTTA)));
	public static final RegistryObject<Block> PURPLE_TERRACOTTA_CORNER = registerBlock("purple_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_TERRACOTTA, ESPStairs.PURPLE_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.PURPLE_TERRACOTTA)));
	public static final RegistryObject<Block> BLUE_TERRACOTTA_CORNER = registerBlock("blue_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_TERRACOTTA, ESPStairs.BLUE_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.BLUE_TERRACOTTA)));
	public static final RegistryObject<Block> BROWN_TERRACOTTA_CORNER = registerBlock("brown_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_TERRACOTTA, ESPStairs.BROWN_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.BROWN_TERRACOTTA)));
	public static final RegistryObject<Block> GREEN_TERRACOTTA_CORNER = registerBlock("green_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_TERRACOTTA, ESPStairs.GREEN_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.GREEN_TERRACOTTA)));
	public static final RegistryObject<Block> RED_TERRACOTTA_CORNER = registerBlock("red_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_TERRACOTTA, ESPStairs.RED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.RED_TERRACOTTA)));
	public static final RegistryObject<Block> BLACK_TERRACOTTA_CORNER = registerBlock("black_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_TERRACOTTA, ESPStairs.BLACK_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.BLACK_TERRACOTTA)));

	// GLAZED TERRACOTTA
	public static final RegistryObject<Block> WHITE_GLAZED_TERRACOTTA_CORNER = registerBlock("white_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.WHITE_GLAZED_TERRACOTTA, ESPStairs.WHITE_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.WHITE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> ORANGE_GLAZED_TERRACOTTA_CORNER = registerBlock("orange_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.ORANGE_GLAZED_TERRACOTTA, ESPStairs.ORANGE_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.ORANGE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> MAGENTA_GLAZED_TERRACOTTA_CORNER = registerBlock("magenta_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.MAGENTA_GLAZED_TERRACOTTA, ESPStairs.MAGENTA_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.MAGENTA_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_BLUE_GLAZED_TERRACOTTA_CORNER = registerBlock("light_blue_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, ESPStairs.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> YELLOW_GLAZED_TERRACOTTA_CORNER = registerBlock("yellow_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.YELLOW_GLAZED_TERRACOTTA, ESPStairs.YELLOW_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.YELLOW_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIME_GLAZED_TERRACOTTA_CORNER = registerBlock("lime_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIME_GLAZED_TERRACOTTA, ESPStairs.LIME_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.LIME_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> PINK_GLAZED_TERRACOTTA_CORNER = registerBlock("pink_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PINK_GLAZED_TERRACOTTA, ESPStairs.PINK_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.PINK_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> GRAY_GLAZED_TERRACOTTA_CORNER = registerBlock("gray_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GRAY_GLAZED_TERRACOTTA, ESPStairs.GRAY_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.GRAY_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> LIGHT_GRAY_GLAZED_TERRACOTTA_CORNER = registerBlock("light_gray_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, ESPStairs.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> CYAN_GLAZED_TERRACOTTA_CORNER = registerBlock("cyan_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CYAN_GLAZED_TERRACOTTA, ESPStairs.CYAN_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.CYAN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> PURPLE_GLAZED_TERRACOTTA_CORNER = registerBlock("purple_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPLE_GLAZED_TERRACOTTA, ESPStairs.PURPLE_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.PURPLE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BLUE_GLAZED_TERRACOTTA_CORNER = registerBlock("blue_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLUE_GLAZED_TERRACOTTA, ESPStairs.BLUE_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.BLUE_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BROWN_GLAZED_TERRACOTTA_CORNER = registerBlock("brown_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BROWN_GLAZED_TERRACOTTA, ESPStairs.BROWN_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.BROWN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> GREEN_GLAZED_TERRACOTTA_CORNER = registerBlock("green_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.GREEN_GLAZED_TERRACOTTA, ESPStairs.GREEN_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.GREEN_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> RED_GLAZED_TERRACOTTA_CORNER = registerBlock("red_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_GLAZED_TERRACOTTA, ESPStairs.RED_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.RED_GLAZED_TERRACOTTA)));
	public static final RegistryObject<Block> BLACK_GLAZED_TERRACOTTA_CORNER = registerBlock("black_glazed_terracotta_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACK_GLAZED_TERRACOTTA, ESPStairs.BLACK_GLAZED_TERRACOTTA_STAIRS.get(), Block.Properties.copy(Blocks.BLACK_GLAZED_TERRACOTTA)));

	// GLASS
	public static final RegistryObject<Block> GLASS_CORNER = registerBlock("glass_corner", () -> new GlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.GLASS, ESPStairs.GLASS_STAIRS.get(), Block.Properties.copy(Blocks.GLASS)));
	public static final RegistryObject<Block> TINTED_GLASS_CORNER = registerBlock("tinted_glass_corner", () -> new TintedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.TINTED_GLASS, ESPStairs.TINTED_GLASS_STAIRS.get(), Block.Properties.copy(Blocks.TINTED_GLASS)));
	public static final RegistryObject<Block> WHITE_STAINED_GLASS_CORNER = registerBlock("white_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.WHITE_STAINED_GLASS, ESPStairs.WHITE_STAINED_GLASS_STAIRS.get(), DyeColor.WHITE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> ORANGE_STAINED_GLASS_CORNER = registerBlock("orange_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.ORANGE_STAINED_GLASS, ESPStairs.ORANGE_STAINED_GLASS_STAIRS.get(), DyeColor.ORANGE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> MAGENTA_STAINED_GLASS_CORNER = registerBlock("magenta_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.MAGENTA_STAINED_GLASS, ESPStairs.MAGENTA_STAINED_GLASS_STAIRS.get(), DyeColor.MAGENTA, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIGHT_BLUE_STAINED_GLASS_CORNER = registerBlock("light_blue_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIGHT_BLUE_STAINED_GLASS, ESPStairs.LIGHT_BLUE_STAINED_GLASS_STAIRS.get(), DyeColor.LIGHT_BLUE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> YELLOW_STAINED_GLASS_CORNER = registerBlock("yellow_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.YELLOW_STAINED_GLASS, ESPStairs.YELLOW_STAINED_GLASS_STAIRS.get(), DyeColor.YELLOW, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIME_STAINED_GLASS_CORNER = registerBlock("lime_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIME_STAINED_GLASS, ESPStairs.LIME_STAINED_GLASS_STAIRS.get(), DyeColor.LIME, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> PINK_STAINED_GLASS_CORNER = registerBlock("pink_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.PINK_STAINED_GLASS, ESPStairs.PINK_STAINED_GLASS_STAIRS.get(), DyeColor.PINK, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> GRAY_STAINED_GLASS_CORNER = registerBlock("gray_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.GRAY_STAINED_GLASS, ESPStairs.GRAY_STAINED_GLASS_STAIRS.get(), DyeColor.GRAY, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> LIGHT_GRAY_STAINED_GLASS_CORNER = registerBlock("light_gray_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.LIGHT_GRAY_STAINED_GLASS, ESPStairs.LIGHT_GRAY_STAINED_GLASS_STAIRS.get(), DyeColor.LIGHT_GRAY, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> CYAN_STAINED_GLASS_CORNER = registerBlock("cyan_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.CYAN_STAINED_GLASS, ESPStairs.CYAN_STAINED_GLASS_STAIRS.get(), DyeColor.CYAN, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> PURPLE_STAINED_GLASS_CORNER = registerBlock("purple_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.PURPLE_STAINED_GLASS, ESPStairs.PURPLE_STAINED_GLASS_STAIRS.get(), DyeColor.PURPLE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BLUE_STAINED_GLASS_CORNER = registerBlock("blue_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.BLUE_STAINED_GLASS, ESPStairs.BLUE_STAINED_GLASS_STAIRS.get(), DyeColor.BLUE, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BROWN_STAINED_GLASS_CORNER = registerBlock("brown_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.BROWN_STAINED_GLASS, ESPStairs.BROWN_STAINED_GLASS_STAIRS.get(), DyeColor.BROWN, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> GREEN_STAINED_GLASS_CORNER = registerBlock("green_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.GREEN_STAINED_GLASS, ESPStairs.GREEN_STAINED_GLASS_STAIRS.get(), DyeColor.GREEN, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> RED_STAINED_GLASS_CORNER = registerBlock("red_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.RED_STAINED_GLASS, ESPStairs.RED_STAINED_GLASS_STAIRS.get(), DyeColor.RED, Block.Properties.copy(Blocks.WHITE_WOOL)));
	public static final RegistryObject<Block> BLACK_STAINED_GLASS_CORNER = registerBlock("black_stained_glass_corner", () -> new StainedGlassCornerBlock(tag(BlockTags.IMPERMEABLE), Blocks.BLACK_STAINED_GLASS, ESPStairs.BLACK_STAINED_GLASS_STAIRS.get(), DyeColor.BLACK, Block.Properties.copy(Blocks.WHITE_WOOL)));

	// SANDSTONE
	public static final RegistryObject<Block> SANDSTONE_CORNER = registerBlock("sandstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SANDSTONE, Blocks.SANDSTONE_STAIRS, Block.Properties.copy(Blocks.SANDSTONE)));
	public static final RegistryObject<Block> SMOOTH_SANDSTONE_CORNER = registerBlock("smooth_sandstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_SANDSTONE, Blocks.SMOOTH_SANDSTONE_STAIRS, Block.Properties.copy(Blocks.SMOOTH_SANDSTONE)));
	public static final RegistryObject<Block> CUT_SANDSTONE_CORNER = registerBlock("cut_sandstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CUT_SANDSTONE, ESPStairs.CUT_SANDSTONE_STAIRS.get(), Block.Properties.copy(Blocks.CUT_SANDSTONE)));
	public static final RegistryObject<Block> RED_SANDSTONE_CORNER = registerBlock("red_sandstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_SANDSTONE, Blocks.RED_SANDSTONE_STAIRS, Block.Properties.copy(Blocks.RED_SANDSTONE)));
	public static final RegistryObject<Block> SMOOTH_RED_SANDSTONE_CORNER = registerBlock("smooth_red_sandstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_RED_SANDSTONE, Blocks.SMOOTH_RED_SANDSTONE_STAIRS, Block.Properties.copy(Blocks.SMOOTH_RED_SANDSTONE)));
	public static final RegistryObject<Block> CUT_RED_SANDSTONE_CORNER = registerBlock("cut_red_sandstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.CUT_RED_SANDSTONE, ESPStairs.CUT_RED_SANDSTONE_STAIRS.get(), Block.Properties.copy(Blocks.CUT_RED_SANDSTONE)));

	// DEEPSLATE
	public static final RegistryObject<Block> COBBLED_DEEPSLATE_CORNER = registerBlock("cobbled_deepslate_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.COBBLED_DEEPSLATE, Blocks.COBBLED_DEEPSLATE_STAIRS, Block.Properties.copy(Blocks.COBBLED_DEEPSLATE)));
	public static final RegistryObject<Block> POLISHED_DEEPSLATE_CORNER = registerBlock("polished_deepslate_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_DEEPSLATE, Blocks.POLISHED_DEEPSLATE_STAIRS, Block.Properties.copy(Blocks.POLISHED_DEEPSLATE)));
	public static final RegistryObject<Block> DEEPSLATE_BRICK_CORNER = registerBlock("deepslate_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DEEPSLATE_BRICKS, Blocks.DEEPSLATE_BRICK_STAIRS, Block.Properties.copy(Blocks.DEEPSLATE_BRICKS)));
	public static final RegistryObject<Block> DEEPSLATE_TILE_CORNER = registerBlock("deepslate_tile_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DEEPSLATE_TILES, Blocks.DEEPSLATE_TILE_STAIRS, Block.Properties.copy(Blocks.DEEPSLATE_TILES)));

	// NETHER
	public static final RegistryObject<Block> BLACKSTONE_CORNER = registerBlock("blackstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.BLACKSTONE, Blocks.BLACKSTONE_STAIRS, Block.Properties.copy(Blocks.BLACKSTONE)));
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_CORNER = registerBlock("polished_blackstone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_BLACKSTONE, Blocks.POLISHED_BLACKSTONE_STAIRS, Block.Properties.copy(Blocks.POLISHED_BLACKSTONE)));
	public static final RegistryObject<Block> POLISHED_BLACKSTONE_BRICK_CORNER = registerBlock("polished_blackstone_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.POLISHED_BLACKSTONE_BRICKS, Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS, Block.Properties.copy(Blocks.POLISHED_BLACKSTONE_BRICKS)));
	public static final RegistryObject<Block> NETHERRACK_CORNER = registerBlock("netherrack_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.NETHERRACK, ESPStairs.NETHERRACK_STAIRS.get(), Block.Properties.copy(Blocks.NETHERRACK)));
	public static final RegistryObject<Block> NETHER_BRICK_CORNER = registerBlock("nether_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.NETHER_BRICKS, Blocks.NETHER_BRICK_STAIRS, Block.Properties.copy(Blocks.NETHER_BRICKS)));
	public static final RegistryObject<Block> RED_NETHER_BRICK_CORNER = registerBlock("red_nether_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.RED_NETHER_BRICKS, Blocks.RED_NETHER_BRICK_STAIRS, Block.Properties.copy(Blocks.RED_NETHER_BRICKS)));
	public static final RegistryObject<Block> QUARTZ_CORNER = registerBlock("quartz_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.QUARTZ_BLOCK, Blocks.QUARTZ_STAIRS, Block.Properties.copy(Blocks.QUARTZ_BLOCK)));
	public static final RegistryObject<Block> SMOOTH_QUARTZ_CORNER = registerBlock("smooth_quartz_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.SMOOTH_QUARTZ, Blocks.SMOOTH_QUARTZ_STAIRS, Block.Properties.copy(Blocks.SMOOTH_QUARTZ)));

	// END
	public static final RegistryObject<Block> END_STONE_CORNER = registerBlock("end_stone_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.END_STONE, ESPStairs.END_STONE_STAIRS.get(), Block.Properties.copy(Blocks.END_STONE)));
	public static final RegistryObject<Block> END_STONE_BRICK_CORNER = registerBlock("end_stone_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.END_STONE_BRICKS, Blocks.END_STONE_BRICK_STAIRS, Block.Properties.copy(Blocks.END_STONE_BRICKS)));
	public static final RegistryObject<Block> PURPUR_CORNER = registerBlock("purpur_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PURPUR_BLOCK, Blocks.PURPUR_STAIRS, Block.Properties.copy(Blocks.PURPUR_BLOCK)));

	// PRISMARINE
	public static final RegistryObject<Block> PRISMARINE_CORNER = registerBlock("prismarine_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PRISMARINE, Blocks.PRISMARINE_STAIRS, Block.Properties.copy(Blocks.PRISMARINE)));
	public static final RegistryObject<Block> PRISMARINE_BRICK_CORNER = registerBlock("prismarine_brick_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.PRISMARINE_BRICKS, Blocks.PRISMARINE_BRICK_STAIRS, Block.Properties.copy(Blocks.PRISMARINE_BRICKS)));
	public static final RegistryObject<Block> DARK_PRISMARINE_CORNER = registerBlock("dark_prismarine_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE), Blocks.DARK_PRISMARINE, Blocks.DARK_PRISMARINE_STAIRS, Block.Properties.copy(Blocks.DARK_PRISMARINE)));

	// PLANKS
	public static final RegistryObject<Block> OAK_CORNER = registerBlock("oak_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.OAK_PLANKS, Blocks.OAK_STAIRS, Block.Properties.copy(Blocks.OAK_PLANKS)));
	public static final RegistryObject<Block> SPRUCE_CORNER = registerBlock("spruce_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.SPRUCE_PLANKS, Blocks.SPRUCE_STAIRS, Block.Properties.copy(Blocks.SPRUCE_PLANKS)));
	public static final RegistryObject<Block> BIRCH_CORNER = registerBlock("birch_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BIRCH_PLANKS, Blocks.BIRCH_STAIRS, Block.Properties.copy(Blocks.BIRCH_PLANKS)));
	public static final RegistryObject<Block> JUNGLE_CORNER = registerBlock("jungle_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.JUNGLE_PLANKS, Blocks.JUNGLE_STAIRS, Block.Properties.copy(Blocks.JUNGLE_PLANKS)));
	public static final RegistryObject<Block> ACACIA_CORNER = registerBlock("acacia_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.ACACIA_PLANKS, Blocks.ACACIA_STAIRS, Block.Properties.copy(Blocks.ACACIA_PLANKS)));
	public static final RegistryObject<Block> DARK_OAK_CORNER = registerBlock("dark_oak_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.DARK_OAK_PLANKS, Blocks.DARK_OAK_STAIRS, Block.Properties.copy(Blocks.DARK_OAK_PLANKS)));
	public static final RegistryObject<Block> MANGROVE_CORNER = registerBlock("mangrove_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.MANGROVE_PLANKS, Blocks.MANGROVE_STAIRS, Block.Properties.copy(Blocks.MANGROVE_PLANKS)));
	public static final RegistryObject<Block> CHERRY_CORNER = registerBlock("cherry_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CHERRY_PLANKS, Blocks.CHERRY_STAIRS, Block.Properties.copy(Blocks.CHERRY_PLANKS)));
	public static final RegistryObject<Block> BAMBOO_CORNER = registerBlock("bamboo_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BAMBOO_PLANKS, Blocks.BAMBOO_STAIRS, Block.Properties.copy(Blocks.BAMBOO_PLANKS)));
	public static final RegistryObject<Block> BAMBOO_MOSAIC_CORNER = registerBlock("bamboo_mosaic_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BAMBOO_MOSAIC, Blocks.BAMBOO_MOSAIC_STAIRS, Block.Properties.copy(Blocks.BAMBOO_MOSAIC)));
	public static final RegistryObject<Block> CRIMSON_CORNER = registerBlock("crimson_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CRIMSON_PLANKS, Blocks.CRIMSON_STAIRS, Block.Properties.copy(Blocks.CRIMSON_PLANKS)));
	public static final RegistryObject<Block> WARPED_CORNER = registerBlock("warped_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.WARPED_PLANKS, Blocks.WARPED_STAIRS, Block.Properties.copy(Blocks.WARPED_PLANKS)));

	// WOOD
	public static final RegistryObject<Block> OAK_WOOD_CORNER = registerBlock("oak_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.OAK_WOOD, ESPStairs.OAK_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.OAK_WOOD)));
	public static final RegistryObject<Block> SPRUCE_WOOD_CORNER = registerBlock("spruce_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.SPRUCE_WOOD, ESPStairs.SPRUCE_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.SPRUCE_WOOD)));
	public static final RegistryObject<Block> BIRCH_WOOD_CORNER = registerBlock("birch_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.BIRCH_WOOD, ESPStairs.BIRCH_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.BIRCH_WOOD)));
	public static final RegistryObject<Block> JUNGLE_WOOD_CORNER = registerBlock("jungle_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.JUNGLE_WOOD, ESPStairs.JUNGLE_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.JUNGLE_WOOD)));
	public static final RegistryObject<Block> ACACIA_WOOD_CORNER = registerBlock("acacia_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.ACACIA_WOOD, ESPStairs.ACACIA_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.ACACIA_WOOD)));
	public static final RegistryObject<Block> DARK_OAK_WOOD_CORNER = registerBlock("dark_oak_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.DARK_OAK_WOOD, ESPStairs.DARK_OAK_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.DARK_OAK_WOOD)));
	public static final RegistryObject<Block> MANGROVE_WOOD_CORNER = registerBlock("mangrove_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.MANGROVE_WOOD, ESPStairs.MANGROVE_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.MANGROVE_WOOD)));
	public static final RegistryObject<Block> CHERRY_WOOD_CORNER = registerBlock("cherry_wood_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CHERRY_WOOD, ESPStairs.CHERRY_WOOD_STAIRS.get(), Block.Properties.copy(Blocks.CHERRY_WOOD)));
	public static final RegistryObject<Block> CRIMSON_HYPHAE_CORNER = registerBlock("crimson_hyphae_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.CRIMSON_HYPHAE, ESPStairs.CRIMSON_HYPHAE_STAIRS.get(), Block.Properties.copy(Blocks.CRIMSON_HYPHAE)));
	public static final RegistryObject<Block> WARPED_HYPHAE_CORNER = registerBlock("warped_hyphae_corner", () -> new ESPCornerBlock(tag(BlockTags.MINEABLE_WITH_AXE), Blocks.WARPED_HYPHAE, ESPStairs.WARPED_HYPHAE_STAIRS.get(), Block.Properties.copy(Blocks.WARPED_HYPHAE)));

	// COPPER
	public static final RegistryObject<Block> OXIDIZED_CUT_COPPER_CORNER = registerBlock("oxidized_cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.OXIDIZED_CUT_COPPER, Blocks.OXIDIZED_CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.OXIDIZED_CUT_COPPER), WeatheringCopper.WeatherState.OXIDIZED));
	public static final RegistryObject<Block> WEATHERED_CUT_COPPER_CORNER = registerBlock("weathered_cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WEATHERED_CUT_COPPER, Blocks.WEATHERED_CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.WEATHERED_CUT_COPPER), WeatheringCopper.WeatherState.WEATHERED));
	public static final RegistryObject<Block> EXPOSED_CUT_COPPER_CORNER = registerBlock("exposed_cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.EXPOSED_CUT_COPPER, Blocks.EXPOSED_CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.EXPOSED_CUT_COPPER), WeatheringCopper.WeatherState.EXPOSED));
	public static final RegistryObject<Block> CUT_COPPER_CORNER = registerBlock("cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.CUT_COPPER, Blocks.CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.CUT_COPPER), WeatheringCopper.WeatherState.UNAFFECTED));
	public static final RegistryObject<Block> WAXED_OXIDIZED_CUT_COPPER_CORNER = registerBlock("waxed_oxidized_cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_OXIDIZED_CUT_COPPER, Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.WAXED_OXIDIZED_CUT_COPPER), WeatheringCopper.WeatherState.OXIDIZED));
	public static final RegistryObject<Block> WAXED_WEATHERED_CUT_COPPER_CORNER = registerBlock("waxed_weathered_cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_WEATHERED_CUT_COPPER, Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.WAXED_WEATHERED_CUT_COPPER), WeatheringCopper.WeatherState.WEATHERED));
	public static final RegistryObject<Block> WAXED_EXPOSED_CUT_COPPER_CORNER = registerBlock("waxed_exposed_cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_EXPOSED_CUT_COPPER, Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.WAXED_EXPOSED_CUT_COPPER), WeatheringCopper.WeatherState.EXPOSED));
	public static final RegistryObject<Block> WAXED_CUT_COPPER_CORNER = registerBlock("waxed_cut_copper_corner", () -> new WeatheringCopperCornerBlock(tag(BlockTags.MINEABLE_WITH_PICKAXE, BlockTags.NEEDS_STONE_TOOL), Blocks.WAXED_CUT_COPPER, Blocks.WAXED_CUT_COPPER_STAIRS, Block.Properties.copy(Blocks.WAXED_CUT_COPPER), WeatheringCopper.WeatherState.UNAFFECTED));

	public static <B extends Block> RegistryObject<B> registerBlock(String name, Supplier<? extends B> supplier) {
		RegistryObject<B> block = BLOCKS.register(name, supplier);
		ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
		return block;
	}

	public static Collection<RegistryObject<Item>> orderedItems() {
		return ITEMS.getEntries();
	}
}